#+REVEAL_ROOT: https://cdn.jsdelivr.net/npm/reveal.js
#+REVEAL_REVEAL_JS_VERSION: 4
#+REVEAL_TRANS: linear
#+REVEAL_THEME: moon
#+OPTIONS: timestamp:nil toc:nil num:nil
#+Title: Mostra Nacional das Feiras de Ciência - Let's Bora
#+Email: englishclubcg@gmail.com
#+Author:
** https://luispengler.github.io/site/doc/images/mostra.jpg
** Criação de Conteúdo Digital a partir dos encontros Let's Bora
#+ATTR_REVEAL: :frag (appear)
+ Instituto Federal de Mato Grosso do Sul, campus Campo Grande
+ Projeto: English Club
+ Integrantes:  Luís Spengler, Mariana Lopes, Natanael Teixeira
+ Coordenação: Profa. Me. Fernanda Belarmino de Santana Scaini
** Primeiro Encontro (13/01/2021)
#+ATTR_HTML: :width 75% :align center
https://luispengler.github.io/site/doc/images/primeiro-letsbora.jpg
** Let's bora nos últimos meses
O Let's Bora está sendo o nosso jeito de manter aqueles que querem melhorar seu inglês bem aquecidos durante a quarentena!
** E tem dado certo!
#+ATTR_REVEAL: :frag (appear)
41 edições do Let's Bora até hoje...
| Data              | Let's Bora nº |
|-------------------+---------------|
| 13/01/21          |             1 |
| 20/01/21          |             2 |
| 27/01/21          |             3 |
| ................. |            .. |
| 10/11/21          |            39 |
| 17/11/21          |            40 |
| 08/12/21          |            41 |
#+BEGIN_NOTES
  Essas são as edições de Let's Bora que aconteceram até o dia de hoje, 19 de novembro.
#+END_NOTES
* INTRODUÇÃO
** Criação de Conteúdo
#+ATTR_REVEAL: :frag (appear)
#+BEGIN_NOTES
Como não é surpresa para ninguém, muita gente começou a criar conteúdo para as redes socias depois que a pandemia começou...
#+END_NOTES

** O nascimento do Let's Bora
#+REVEAL: split
Você na pandemia indo ao Let's Bora:
#+ATTR_HTML: :height 35% :width 35% :align center
https://luispengler.github.io/site/doc/images/monalisa-mask.jpg

#+BEGIN_NOTES
A gente tem o Let's Bora. Um projeto que nasceu depois de várias reuniões com nosso staff e em janeiro desse ano, a gente começou com os encontros online.
E deu resultados viu?
#+END_NOTES

** Como resultado do Let's Bora...
Vimos que poderiamos aproveitar os mesmos conteúdos abordados nos encontros de conversação para desenvolvimento de conteúdo digital no Instagram e Telegram.

#+BEGIN_NOTES
A gente percebeu que podia usar os mesmos conteúdos abordados nos encontros, pra criar conteúdo.
#+END_NOTES
* DESENVOLVIMENTO DE CONTEÚDO DIGITAL
#+ATTR_REVEAL: :frag (appear)
#+BEGIN_NOTES
O planejamento das ações que deveriam ser feitas durante as semanas aconteciam durante as reuniões de equipe e o controle era feito a partir de uma planilha de controle no google sheets
Agora a Mariana vai falar um pouco sobre o conteúdo que a gente cria para as plataformas do Instagram e do Telegram
#+END_NOTES
#+REVEAL: split
#+ATTR_HTML: :width 65% :align center
https://luispengler.github.io/site/doc/images/editorial.png

* CONTEÚDOS NO INSTAGRAM E TELEGRAM
#+REVEAL: split
#+ATTR_REVEAL: :frag (appear)
#+BEGIN_NOTES
-Como o Luís mencionou, os conteúdos digitais eram baseados nos nossos encontros do Let's Bora e a função de criar determinada ideia dependia de como eram escaladas as funções da semana.
-(Fale um pouco da sua experiência)
-Aqui a gente tem alguns exemplos do tipo de conteúdo que a gente criava
#+END_NOTES

Criação de conteúdo nos Stories do Instagram a partir de discussão sobre a sigla "PB" em um encontro do Let's Bora
#+ATTR_HTML: :height 25% :width 25% :align center
https://luispengler.github.io/site/doc/images/PB.jpg
#+REVEAL: split
Criação de conteúdo nos Stories do Instagram a partir de discussão sobre a expressão "Down the drain" em um encontro do Let's Bora
#+ATTR_HTML: :height 25% :width 25% :align center
https://luispengler.github.io/site/doc/images/quizz.png
* RESULTADOS E ANÁLISE
** Numeros desde a criação
#+BEGIN_NOTES
A gente busca ter uma presença ativa nas redes socias, principalmente no instagram desde o inicio da pandemia.
#+END_NOTES
#+REVEAL: split
Desde a criação do nosso instagram, 25 de março de 2020, temos em nosso perfil...
#+REVEAL: split
#+ATTR_HTML: :height 55% :width 55% :align center
https://luispengler.github.io/site/doc/images/reels.png

18 reels
#+REVEAL: split
#+ATTR_HTML: :height 65% :width 65% :align center
https://luispengler.github.io/site/doc/images/videos.png

11 videos
#+REVEAL: split
#+ATTR_HTML: :height 55% :width 55% :align center
https://luispengler.github.io/site/doc/images/posts.png

80 posts
#+BEGIN_NOTES
Esses posts tem conteudos variados, como convites para os encontros de conversação, vocalubário, citações, dicas de como estudar inglês, datas comemorativas e oportunidades para estudar fora.
#+END_NOTES
* CONSIDERAÇÕES FINAIS
#+BEGIN_NOTES
A gente aprendeu que é possivel apoiar os alunos que precisam perder o medo de falar inglês, seja por meio do Let's Bora ou pela criação de conteúdo digital.
#+END_NOTES
* Prêmio melhor projeto a nível médio, FECINTEC 2021
#+ATTR_HTML: :height 35% :width 35% :align center
https://luispengler.github.io/site/doc/images/prize.png
* REFERÊNCIAS
+ CASTELLS, Manuel. A sociedade em rede. São Paulo: Paz e Terra, 2006.
+ KNOBEL, Michele; LANKSHEAR, Colin (Eds.). A New
+ Literacies Sampler. Vol. 29. New York: Peter Lang, 2007.
* Follow us!
- Instagram: @englishclubcg
