#+REVEAL_ROOT: https://cdn.jsdelivr.net/npm/reveal.js
#+REVEAL_REVEAL_JS_VERSION: 4
#+REVEAL_TRANS: linear
#+REVEAL_THEME: moon
#+OPTIONS: timestamp:nil toc:nil num:nil
#+Title: Let's Bora no II Encontro de Linguagens
#+Email: englishclubcg@gmail.com
#+Author:
* O Let's Bora
#+ATTR_REVEAL: :frag (appear)
** Primeiro Encontro (13/01/2021)
#+ATTR_HTML: :width 75% :align center
https://luispengler.github.io/site/doc/images/primeiro-letsbora.jpg
** Let's bora nos últimos meses
O Let's Bora está sendo o nosso jeito de manter aqueles que querem melhorar seu inglês bem aquecidos durante a quarentena!
** E tem dado certo!
#+ATTR_REVEAL: :frag (appear)
40 edições do Let's Bora até hoje...
| Data              | Let's Bora nº |
|-------------------+---------------|
| 13/01/21          |             1 |
| 20/01/21          |             2 |
| 27/01/21          |             3 |
| ................. |            .. |
| 03/11/21          |            38 |
| 10/11/21          |            39 |
| 17/11/21          |            40 |
#+BEGIN_NOTES
  Essas são as edições de Let's Bora que aconteceram até o dia de hoje.
#+END_NOTES
* INTRODUÇÃO
** Criação de Conteúdo
#+ATTR_REVEAL: :frag (appear)
#+BEGIN_NOTES
Como não é surpresa para ninguém, muita gente começou a criar conteúdo para as redes socias depois que a pandemia começou...
#+END_NOTES

#+ATTR_HTML: :width 65% :align center
https://luispengler.github.io/site/doc/images/max.jpg

#+BEGIN_NOTES
Essa foto é de um clipe de um artista alemão e no clipe da música dele aparecem dezenas de pessoas, que submeteram vídeos deles cantando a música. O nome da música é Nie starker als jetz, que significa, Nunca fomos tão fortes quanto agora.
#+END_NOTES

** O nascimento do Let's Bora
Você na pandemia indo ao Let's Bora:
#+ATTR_HTML: :height 35% :width 35% :align center
https://luispengler.github.io/site/doc/images/monalisa-mask.jpg

#+BEGIN_NOTES
E com o Let's Bora não podia ser diferente. Depois de várias reuniões com nosso staff, nasce o Let's Bora no janeiro desse ano.
#+END_NOTES

** Como resultado do Let's Bora...
Vimos que poderiamos aproveitar os mesmos conteúdos abordados nos encontros de conversação para desenvolvimento de conteúdo digital no Instagram e Telegram.

* Desenvolvimento de conteúdo digital
#+ATTR_REVEAL: :frag (appear)
O planejamento das ações que deveriam ser feitas durante as semanas aconteciam durante as reuniões de equipe e o controle era feito a partir de uma planilha no google sheets
#+ATTR_HTML: :width 65% :align center
https://luispengler.github.io/site/doc/images/editorial.png

** Conteúdos criados no Instagram e Telegram
#+BEGIN_NOTES
Como dito anteriormente, os conteúdos digitais eram baseados em encontros de conversação passados e as ideias eram discutidos e atribuídas ao integrante responsável pela criação digital que foi escalado no cronograma semanal.
#+END_NOTES
Criação de conteúdo nos Stories do Instagram a partir de discussão sobre a sigla "PB" em um encontro do Let's Bora
#+ATTR_HTML: :width 65% :align center
https://luispengler.github.io/site/doc/images/PB.jpg

Criação de conteúdo nos Stories do Instagram a partir de discussão sobre a expressão "Down the drain" em um encontro do Let's Bora
#+ATTR_HTML: :width 65% :align center
https://luispengler.github.io/site/doc/images/quizz.png

* CONSIDERAÇÕES FINAIS
* REFERÊNCIAS
* Follow English Club
- Web: [YOUR WEBSITE]
- Twitter: [YOUR TWITTER HANDLE]
- Blog: [YOUR BLOG]
