#+TITLE: Relatório Estágio Interno
#+DESCRIPTION: Relatório Estágio Interno
#+SETUPFILE:  https://luispengler.github.io/site/org-html-themes/org/theme-readtheorg.setup
#+OPTIONS: toc:nil

* Algumas considerações
Estamos registrados para começar o estágio às 13h... batemos o ponto normalmente. No entanto, nosso professor orientador só começa a nos dar instruções a partir das 14h. Por esse motivo, todos os registros do relatório diário começam a partir das 14h.

* Relatório Diário
=(07/06 -> 14h-17h)= Arrumamos a mesa do lab B105, removendo quatro computadores e alocando-os em mesas próximas. Preparamos a fonte de bancada, multímetro de bancada, gerador de frequência para uso. Montamos três kits de protoboard. O objetivo é dar início a preparação da sala B105. Tivemos facilidade em realizar a tarefa de realocação, assim como ajuste dos instrumentos de laboratório. No entanto, tivemos maior dificuldade em montar os kits de protoboard, pois a ordem das peças que faziam o borne às vezes nos era confusa.

=(10/06 -> 14h-17h)= Com o auxílio de uma serra tico-tico cortamos um tampo de madeira para que coubesse na diferença da área existente em uma mesa para cadeirantes, visando entesourar outra madeira, que estava sendo utilizando como tampão, para uso posterior. O objetivo também era aproveitar material, a madeira, a qual é um recurso precioso no campus. A maior dificuldade foi fazer a marcação para os cortes corretamente. A facilidade estava em apenas segurar a madeira com a mão, enquanto o professor cortava.

#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style float:left;margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/cutting-wood.jpg

=(14/06 -> 13h-17h)= Fixamos o tampo de madeira cortado anteriormente. Alguns painéis solares para kits também chegaram. Trocamos as pilhas de aprox. 9. alicates amperímetros e atestamos seu correto funcionamento. O objetivo é ter instrumento de medição pronto para uso. Tivemos um pouco de dificuldade em fixar o tampo de madeira, no entanto, trocar as pilhas dos alicates foi fácil.
#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: 900px;
https://luispengler.github.io/site/doc/images/estagio/fixed-wood.jpg


#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/solarp-inbox.jpg


#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/solarp-inbox1.jpg

=(17/06 -> 13h-16h)= Separamos as ferramentas a serem utilizadas em cada bancada de laboratório do curso de energia fotovoltaica. A ideia é criar um painel de ferramentas na parede para utilização. Lixamos as placas de MDF a serem utilizadas como painel de ferramentas e criamos o layout de organização do painel. Tivemos facilidade em melhorar o acabamento do MDF, mas não ficou perfeito porque ele já possuía bastante umidade.
#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/tools-panel.jpg

#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/tools-panel-layout.jpg

=(20/06 -> 13h-17h30)=
Cortamos 4 barras roscadas para o kit de painéis solares semi-fixo para que fosse possível ajustar o ângulo de incidência da luz na placa. O Bruno organizou disjuntores em caixas.
#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/cutting-iron.jpg


#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/bars.jpg

#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/fixed-iron.jpg


#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/bruno-organizing.jpg

#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/disjuntores-boxes.jpg

=(24/06 -> 13h-17h)=
Montei o design e cortei 9 tiras de MDF para o kit dos painéis. Posteriormente, montei o design, cortei e auxiliei na montagem de 5 suportes de controles de ar-condicionado para o campus.

#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/tiras-design.jpg

#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/tiras.jpg

#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/disassembled-cases.jpg

#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/caixas-montadas.jpg

=(27/06 -> 13h-17h30)=
Terminamos o primeiro painel de ferramentas para o laboratório de energia fotovoltaica (energif). Foram pregados 39 pregos para fixação das 39 ferramentas vista na imagem abaixo. Note que as tiras do dia 24/06 já estão coladas, isso sendo obra do Bruno. Depois, auxiliei na fixação do kit na parede. O objetivo do painel é diminuir o tempo na hora de buscar as ferramentas que o aluno precisa, além de ser mais organizado e esteticamente agradável que muitas ferramentas esparramadas pela mesa. Talvez pregar alinhadamente seja a parte mais difícil deste trabalho, além da organização do layout. Colocar o painel na parede com fita foi bem fácil, embora ele esteja empenado.
#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/kit-done.jpg

=(28/06 -> 13h-17h)=
Esse dia eu fiquei um pouco de assistente. Auxiliei a estagiária Jéssica no corte de 4 suportes de controle de ar-condicionado. Auxiliei os estagiários Daniel e Lukas no layout dos componentes no kit de painéis solares semi-fixo.

#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/jessica-cases.jpg

#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/daniel-design.jpg

#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/kit-components.jpg

=(01/07 -> 13h-17h)=
Tiramos as medidas para o corte na cortadora a laser do painel MDF que entra no kit de painéis solares semi-fixo. O objetivo é que o painel MDF entre na caixa de distribuição do kit. A parte mais difícil foi projetar matematicamente como os cantos seriam, suas representações no software Inkscape, no entanto, foi a parte mais fácil.
#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/moldeforkit.jpg

=(04/07 -> 9h30-15h30)=
Pegamos as placas de MDF de 6 mm e cortamos na cortadora a laser seguindo as especificações do dia 01/07. Foram cortados 5 painéis.
#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/moldecortado.png

=(05/07 -> 9h30-15h30)=
Seguindo o esquema de instalações feito dia 28/06, e utilizando um dos painéis cortados do dia anterior (04/07) realizamos a instalação de testes do primeiro kit de painel solar semi-fixo. O objetivo do teste é observar na prática o funcionamento do sistema. A parte mais difícil era manter os componentes no lugar: eles eram colados com fita em um painel na vertical. Foi muito fácil parafusar os cabos nos seus lugares devidos.
#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/kitquaseinstalado.png

#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/kitinstalado.png

=(06/07 -> 13h-17h)=
Realizamos testes com resultados promissórios com o kit montado no dia anterior (05/07). O objetivo também é o mesmo do dia 05/07. A parte mais difícil, no entanto, foi ligar alguns tipos de carga, assim como a dependência das placas da luz solar. Também foi difícil entender o funcionamento do controlador de carga, a princípio. Tivemos grande facilidade com trazer o sistema para a porta traseira do bloco B.
#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/testkit1.jpg

#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/testkit2.jpg

=(04/08 -> 13h-17h)=
Auxiliei o Jorcinei no corte da sobra dos parafusos dos soquetes das lâmpadas no kit de lâmpadas. O objetivo era não deixar nenhuma ponta que machucasse o usuário, tanto fisicamente, pois era afiada, como eletricamente, pois a corrente poderia fluir pelo metal do parafuso. A parte mais fácil foi trazer esse painel para o Jorcinei lá da sala B105 e a mais difícil foi acertarmos um corte perfeitamente reto no parafuso.

#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/04-08.jpg

=(10/08 -> 14h-17h)=
Nesse dia não fui muito produtivo. Observei a Jéssica fazer as etiquetas de componentes no software LibreOffice. Enquanto isso, conversava com o professor sobre uma ideia de limpador com arduino.

#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/10-08.jpg

=(18/08 -> 13h-17h)=
Instalamos o terra no DPS, para que sua atuação se desse corretamente. A parte mais fácil foi claro, parafusar o fio verde do terra no DPS, mas entender como isso funcionaria no kit do painel solar semi-fixo foi difícil.

#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/18-08.jpg

=(24/08 -> 14h-17h)=
Criamos o sistema de divisão do circuito com letras e números para facilitar no guia da montagem dos kits pelos alunos. A letra 1 simboliza CC do painel sendo dividido em partes a, b, c. A cada componente que o circuito 1 passa, ele se divide em uma letra até chegar no controlador de carga. Do controlador de carga sai o 2 para a bateria, sem nenhuma letra, pois nenhum componente divide o 2. O 3 sai do lado da carga do controlador de carga, dividido entre a e b até chegar no inversor de frequência. A parte mais difícil foi ter a ideia inicial desse sistema, que embora simples, nada era que imaginarei estar fazendo. Foi fácil, no entanto, colar tiras nos cabos já cortados simbolizando cada componente desse sistema de divisão elétrico.


#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/24-08.jpg

#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/24-08(1).jpg

=(25/08 -> 14h-17h)=
Colocamos o circuito que dividimos através do sistema do dia 24/08 no quadro elétrico do kit dele. Também montamos outro painel idêntico, exceto por modelos de peças diferentes. O objetivo era deixar mais de um painel pronto para os alunos poderem utilizar. A parte mais difícil foi montar rapidamente outro painel. A mais fácil, foi ter colocado o painel já pronto no lugar certo.

#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/25-08.jpg

#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/25-08(1).jpg

#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/25-08(2).jpg

#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/25-08(3).jpg

=(01/09 -> 13h-17h)=
Demos início a construção do manual de montagem, mas com o Bruno tentando fazer o circuito no AutoCad. O objetivo é auxiliar os estudantes na montagem dos kits. A parte mais fácil foi pensar em como isso poderia ser trazido em um manual, no entanto, a escrita disso no AutoCad se provou a parte mais difícil.

#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/01-09.jpg

#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/01-09(1).jpg

=(08/09 -> 13h-18h)=
Continuação do dia 01/09.

#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/08-09.jpg


#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/08-09(1).jpg


#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/08-09(2).jpg


#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/08-09(3).jpg

=(09/09 -> 14h-16h)=
Dessa vez o Bruno não veio então tive que continuar a elaboração do tutorial de montagem sozinho. O professor disse que poderia ser uma coisa mais rápida mesmo e que por hora não precisaria utilizar o AutoCad. Então escrevi um documento no LibreOffice referente ao tutorial de montagem. A parte mais difícil foi ter a ideia de como elaborar esse documento. Uma vez com a ideia, foi bem fácil utilizar minhas habilidades no software para escrever o documento.

=(14/09 -> 13h-17h)=
Finalizo o tutorial de montagem, mas apenas depois que tirei a foto de cada componente e inclui a descrição de cada um no tutorial de montagem, coisa que estava faltando no dia 08/09. Foi difícil conseguir fotos claras de alguns componentes e tive que utilizar o celular do professor Cortez às vezes. Foi fácil importar e formatar as imagens no software, no entanto.

=(20/09 -> 14h-18h)=
Esse dia foi a primeira aula de corte a laser que dei, auxiliando o professor Newton. Demonstrei os processos básicos de desenho no Inkscape para a turma 249, deixando como atividade de aula a elaboração do desenho que seria utilizado para o corte na aula prática do dia 27/09. Na primeira aula com a turma, estava um pouco nervoso, mais fui me soltando e senti que a aula dada foi ótima. No início foi difícil não estar nervoso. Posteriormente, tive que guardar o desenho de todos então pedi que me mandassem por e-mail, o que foi fácil para mim, já que só precisaria baixar e os ter no pendrive para a aula do dia 27/09.

=(21/09 -> 13h-17h)=
Realizamos testes com os painéis de lâmpadas que aprontamos dia 04/08. O objetivo era assegurar a geração de energia de todos os painéis de kit semi-fixo já instalados. A parte fácil foi simplesmente pegar o painel de lâmpadas e aproximar dos painéis fotovoltaicos. A parte difícil, no entanto, foi organizar o sistema de geração de energia. Os painéis de 30W seriam ligados em série, paralelo? A corrente/tensão seriam suficientes para o controlador de carga carregar a bateria e demonstrar isso aos estudantes?

#+attr_html: alt: modelo padrão :title modelo padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/21-09.jpg


#+attr_html: alt: modelo padrão :title modelo padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/21-09(1).jpg

=(27/09 -> 14h-18h)=
Nesse dia, achei que continuaria tutorando eles e como fazer os cortes na cortadora. No entanto, o professor Célio tomou conta e explicou tudo. Apenas tive que levar o pendrive com os desenhos e observar o resultado de cada um que havia observado na tela do meu computador. Foi difícil aceitar que minha última aula havia sido semana passada, mas a parte mais fácil foi apenas assistir o Célio demonstrar seu conhecimento de cortadoras a laser.

=(29/09 -> 13h-17h)=
Foi me proposto, pelo professor Cortez, a elaboração de caixas de componentes em MDF através da cortadora a laser. Consegui, facilmente passar as medidas das caixas para o modelo a ser impresso, já que existia programa que fazia isso. No entanto, foi difícil montar as caixas, já que algumas apresentavam erros de corte que só percebemos posteriormente. Os erros faziam a gente imprimir muito mais força no encaixe das peças e que nem sempre dava certo. Então, cortei menos peças por lote e os erros pararam de acontecer. Durante os próximos dias do estágio, me dediquei a montagem dessas caixas de componentes e foi esta a última atividade que efetuei durante o estágio.

#+attr_html: alt: modelo padrão :title modelo padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/29-09.jpg

#+attr_html: alt: modelo padrão :title modelo padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/29-09(1).jpg

#+attr_html: alt: modelo padrão :title modelo padrão :style margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/estagio/29-09(2).jpg

=(Finalização)=
As principais atividades relacionados ao meu curso foram a calibragem e montagem de equipamentos. Montagem de sistemas elétricos e fotovoltaicos. Dimensionamento de componentes e emendas. Coordenação e tutoramento de atividades.
