#+TITLE: Annotations

+ Create a schedule to study (you and your brother) - that means strictly defining your goals for what's to come
+ 3+2 double major is not the same as double degree
+ CSS Profile non-custodial waiver (explain why vc n tem contato - documentos judiciais servem)
+ Think about somone in the school to be your consuler (to talk about your bad grade - contextualizar)
+ Apply to Brasa in the second semester (ajuda financeira)
+ Keep an eye on "Design in the command line: Recipes for tasty outcomes" Imagemagick + ffmpeg + bash to create animation for LP work (https://erase.artdel.net/ )
+ Keep an eye on "Living in freedom with GNU Emacs"
+ Course on Open Source applications (Living in freedom with GNU emacs is a good idea!)
+ 42 chapters must be read (physics)
+ Dois prótons e um café: https://www.youtube.com/channel/UCW0Eyk1RrjIWFjgjBy_RR_g, Physikós: https://www.youtube.com/channel/UCIyM6oBSv0qHwxVpCl5Rehw

* Lucas nos eua 1
+ Alguma das 5 mil faculdades vai te dar uma bolsa, mas qual é a certa pra vc?
+ 85% das 5mil faculdades tem mais de 50% de taxa de aceitação
+ 2 Reach, 5 Match, 3 Safety: Estratégia conservadora

** Provando seu amor
+ Feiras de faculs abertas ao público
+ Webinars
+ Solicitando entrevistas e bate papos
+ Emails
+ Receber cartas físicas e posters
+ Tour virtual
+ Aplicar Early

** Oglethrope University (GA) e Trinity University (TX)
+ Exemplos de EA

** Os 4 fits
+ Acadêmico
  - Procure Recursos/Tamanho
  - Olho na grade curricular (Conteúdo é essencial)
+ Cultural
  - Pesquisar experiência/vivência/indenpendência/networking
  - Tamanho/Localização/Clima
  - Dormitórios/Campus/Serviços
  - Clubes/Organizações/Vida Social
+ Financeiro
  - Quantos alunos recebem bolsa?
  - Quantos de bolsa recebem?/Brasileiros?
+ Carreira
  - Procurar career fairs
  - Ver os ex-alumni

** Mínimo-ideal-sonho
+ Mínimo
+ Ideal
+ Sonho

* Lucas nos eua 2
+ Tenha um kit de stalker completo: cada site é uma ferramenta
+ Quem procura acha: estudar cada faculdade (fuçar e clicar)
+ A fila anda: pesquisar faculdades o mais cedo possível

** Tops sites de pesquisa
+ Ranking: [[https://www.usnews.com/best-colleges?int=top_nav_Colleges][US News]]
+ Filtragem: [[https://collegesearch.collegeboard.org/home][Big Future]]
senha: arroz

* Wichita State University
+ Info on telegram

* Marcohort
+ Literally explain metaphors
+ Follow up + Weekly things + Examples reading + Three short essays

* Education USA
+ 99% universities will have financial aid, but it is important to understand what kind of it
+ It is not university tution you need to worry about (there is also books & supplies, health insurance, room & board, misecellaneous living expenses)
+ Lecture number 4 is really useful (common mistakes to avoid in your application)
+ Additional Information: I NEED TO USE THIS
** Kinds of need
+ Need based: scholarships given based on need (based on family income)
+ Merit based: students receive this based on their special skills, competitiveness, etc
+ Need blind: applicants financial status don't affect their admittion
+ Need aware: applicants financial status affect their admittion
+ Unmet need: the amout you need to pay after the scholarship is applied (what the scholarship doesn't cover)

* New idea
+ Define this "club" goal...
+ "Computação Quântica - Plano de aula com enfoque para o Ensino Médio" will work for thinking about creating the IFMS QC course, but it can be improved...
+ This project should involve particle physics too!
+ Building OPEN SOURCE detectors (particle physics), the Pauli teta QC (wow!)
+ This project may be done in 3 different tracks... classical physics, particle physics and quantum mechanics focused on quantum computing
+ Building a photonics quantum computer (School builds quantum computer to teach students...), but why..

** The why
+ It is scalable
+ It is robust
+ Practical (room temperature, can be easily integrated infrastucturely)
** Materials
+ Optical Table
+ 2 Lasers (One class four, another class 1)
+ EPI for Lasers
+ 1 KDP (monopotassium phosphate) crystal
+ 3 Polarized Beam Splitter (2 for breaking the entanglement + 1 for identification of the measurement)
+ 2 Mirrors (for breakign the entanglement)
+ 1 Photomultiplier Tube (for measurement)
*** Gates
+ 3 Rx gate (1 Rx gate will work as an X gate + 1 Rx gate will work as an H gate + 1 Rx gate will work as a real Rx gate)

* Marcohort 2
+ I don't get how music is applied into your life (how you feel), and give the example. He doesn't illustrate how it is important music in his context... <- Just Add things in another color, don't delete;
+ The music story will probably not become a personal statement, probably something for a supplemental essay
+ They cycling thing (the imposed limitation here... how?) and the autoimmune disease (focus on how you life were before and how you had to adjust, what you had to do differently like mentally, etc - how did you feel about it? - some limitations were imposed on me, how you feel about it?)

* New idea
+ Create a palce (it can be a website) for people to share real world problems
+ I am tired of looking at my country and seeing only problems. I start thinking of a way I could fix them, but it is just too much for one person
+ So I decided to create this place where anyone can share a problem their community have. Someone can come and propose a solution
+ Maybe a social media???????????????


* Colleges test
Suggested Schools: Science: California Institute of Technology, Clarkson University, Georgia Institute of Technology, Harvey Mudd College, Massachusetts Institute of Technology, New Mexico Institute of Mining and Technology, Rensselaer Polytechnic Institute, Texas Tech University Not science: UCLA, University of North Carolina, Penn State, or Michigan State

+ Arduino ATmega328

* Marcohort 3
+ "Since I was a child..." - Explain better the consequences of the disease (BE MORE IMPACTFUL) + Explain how you adjusted to your new life (Introduce Linux!!! Explain it is a different kind of freedom, and you get that, my disease allowed me to develop passion for tech - idea: having a change of scnerio, being excited differently)
+ In the story 3 second paragraph, maybe explain what freedom means for you now
+ Perguntar sobre o histórico parcial na escola

* LOA
+ Usar mais o quadro-negro como um retorno visual -> a ideia é parecer mais uma aula
+ Outro com aviãozinho (melhorar a volta do avião) e o like é top
+ Pode ser uma boa ideia ter o titulo embaixo da final da intro

* ACT
+ Questão bem geral: A gente aqui no marcohort estamos no processo de escrever histórias que vão levar a gente a escrever um personal statement. Eu também acredito que você deve ter escrito sobre alguns assuntos diferentes antes de ter chego ao tema principal da sua personal statement. O negócio é que eu meio que já estou vendo um caminho claro pra escrita do meu, mas ao ler seu personal statement eu também acabei me identificando com alguns pontos em específico, mesmo que sendo parte de mim, este não encaixaria nessa minha ideia. A pergunta é como tu conseguiu focar pra falar desse assunto?
+ Se o escritor também seja de exatas (Wangheley Soares Martins, Adeildo Viera Silva Neto - CS and physics!, João Vitor Boeachat Torrest Botelho - CS student!): Minha pergunta é simples: como você escreve tão bem? Porque eu tenho a impressão que o pessoal de exatas só sabe números, ou mexer com equipamentos, etc. Eu sempre tive um medo da lingua portuguesa me comer vivo, mas só depois que eu tinha 14 anos e comecei a aprender ingles que eu aprendi a gosta de linguas, e mesmo sendo apaixonado por física e ciência da computação, agora fazendo curso técnico em eletrotécnica, eu tenho que saber me comunicar: seja pra escrever um artigo científico ou pedir uma pizza. Pedir uma pizza ainda é meio dificil, mas eu já entendi a necessidade. Reformulando minha pergunta: como você escreve um texto sobre si considerando possíveis dificuldades linguísticas
+ Dica da Aisha: Listar coisas pra ir escrevendo - coisas que eu to fazendo e porque eu gosto de fazer isso. Colocar pontos de vc que a pessoa que está lendo entenda quem você é! É bom ambientar a galera - a pessoa lendo se sente como você (em um onibus lotado, você se sente limitado... posso fazer algo sobre isso? isso me levou a fazer tal coisa... o quanto vc luta pra se fazer ser ouvido em um espaço limitado, invisibilizado... ou então fazer o contraste desse lugar de injustiça com o que acontece no resto do seu dia). A redação do Boeachat fez ela pensar em como ela pode mostrar as montanhas que ela moveria pra estudar no ensino superior

* English Club
+ 07/05 (Saturday) at 9am - encontro com possíveis novos participantes
+ Encontros afternoon: 13h15-14h
+ Encontros morning: Por enquanto não teremos porque apenas a Estela está disponível
+ Estela ficou responsável pela arte (até 02/05), Natanael ficou responsável pela divulgação no Instagram, Luis ficou responsável pela divulgação no campus por meio dos cartazes da Estela
+ Próximo retorno do Let's Bora 09/05 at 13h15
+ Procurar informações sobre concurso de logos (concursos similares, cores, cabe em um formato circular, valor de prêmio)
+ Em maio, possivelmente divulgaremos nas salas os cursos CENID
+ Em junho, podemos planejar um encontro no parque das nações, possivelmente dia 11/06

* Marcohort 4
+ In paragraph 4, be more clear/straitforward "To add up, I could not go outside yet. Sun was boiling eggs in the pavement, and Covid-19 was running rampant. So, I stay in my room, quiet and alone. I press a button, and a beast silently awakens. I keep staring at the screen, as if the shiny letters could hurt my reality even more. But all it does is ask who I am. As I prompt my user data, I am reminded how trustworthy the system I modified is, and I could also use, study, improve, and share it as I pleased." Try using less metaphors and ryme less, because you already used them in the beginning.
+ You have to be very clear that coding is very important
+ Have a final paragraph saying you can't cycle and it sucks (even though my freedom was removed), but this issue allowed me to discover something else, to explore more about this world.
+ I will need my parcial transcript + transcript

Luís Guilherme Miranda Spengler is currently a High School senior, taking electrotechnology vocational program at Instituto Federal do Mato Grosso do Sul. He is very engaged in the activities from his school, and takes great interest in activities involving research, volunteering and teaching.

During the pandemic, Luís was one of the most engaged students from his school, where he developed research, and coordinated at English Club. As a result of this, his team won Fecintec and were invited to participate in Mostra Nacional Itinerante das Feiras de Ciências. As a 1-year Quantum Computing student at the Qubit by Qubit program for high school students, he could learn more about an exciting career that is changing the world for the better, with its state-of-the-art innovations. He makes it his personal goal to somehow contribute to the Quantum Computing field.

Currently, he is preparing for the application process with the help of EducationUSA Application Tracker project. Meanwhile, he works on other projects he knows will also make an impact on his community, and hopes US colleges will notice his hard work and dedication.



* UNESCO Center for Peace
+ They will give a letter to apply for VISA - A visa of tourist is already enough
+ They conver absolutely everything, except for plan ticket to US and VISA
+ They have a facilitator for Brazil
+ Jorge Gonzales number: +5215568560371; Paloma: (+57) 3017787345; Shurabe: smercado@unescocenterforpeace.org

* Mobfog
** Materiais base de lançamento
+ 80cm de cano 20mm (para confecção de 3 canos de 20cm e 20 de 10cm)
+ 1 T de 20mm
+ 2 Cotovelos de 20mm
+ 2 caps de 20mm
+ 1 válvula de camara de bicicleta
+ 1 pedaço de camara de bicileta (pra ajudar na vedação)
+ 1 pedaço de mangueira de áquario (pra ajudar em caso de emergência)
+ 1 cola de PVC
+ 1 balão 6,5
+ 1 espaladrapo largo
+ 4 abraçadeiras de nylon (largua +- 3,6mm)
+ 1 abraçadeira 1cm diametro
+ 1 cano de esgoto 4cm diametro com 3cm de comprimento
** Materiais para o foguete
+ 2 Garrafa PET com o mesmo diâmetro ao longo da sua extensão (600mL - 2L)
  - A primeira garrafa terá as empenas, a segunda garrafa será removida o fundo e ficará em cima da primeira para que tenha mais aerodinâmica
+ Pasta Polionda para as empenas (3-4 empenas)
+ Parafuso de 1/4 de polegada para peso

+ Fanta 2L é 8,5
+ Suco Scheppes é 4,5

** Materiais - Base de lançamento opção 1
+ (15cm + 15cm + 15cm + 15cm + 40cm + 40cm + 25cm + 25cm + 26,5m 2,165m) 2,165m de cano PVC 25mm
+ 22 cm de cano PVC 20mm
+ 1 pedaço (5,5cm) de cano de 40mm
+ 2 Joelhos pra cano 25mm (Temos)
+ 5 Tês para cano 25mm
+ 1 cap para cano 25mm
+ 1 bucha de redução 25mm para 20mm (Temos)
+ 1 abraçadeira de metal
+ 1 manômetro de 150 PSI pra cima
+ 1 espaladrapo (Temos)
+ 8 enforca gato (4 pra válvula e o resto pra apertar) (Temos)
*** Additional
+ Registro esfera 25 mm soldável
+ 2 arruela de vedação 1/4
+ 1 Cap 25mm
+ 1 porca 1/4
+ 1 abraçadeira anel
+ 1 luva de redução 25 para 20mm
** Materiais - Foguete opção 2
** Materiais que não precisarão ser comprados
- serra
- veda rosca
- varetas de churrasco (obrigatórias)
- vaselina
- joelhos de pvc 25mm
- enforca gato
- esparadrapo
- estilete
- fita isolante
- balão (não sei o tamanho)
- garrafa pesa 39,4g
- 9,93cm
- altura 34cm


* ACT
** School Documents
+ Pedir para usar email institucional
+ Pedir para usar cabeçalho da escola ou logo
+ Pedir para assinarem os documentos (principalmente cartas de recomendação)
+ Todos os documentos devem ser traduzidas para inglês
+ Não tem problema os recomendadores não poderem escrever em inglês, o ACT poderá traduzi-los

** Transcripts
+ Históricos oficiais da escola (precisam ter suas notas do 9th grade a 12th)
+ Precisa ser assinado pelo school counseler/director

** School Profile
+ Helps admissions officers interpret the transcript for classes offered, rigor, grading policies and more
+ Também possui informação sobre a escola, administração, tipo de escola, número de estudantes graduando, curriculo, processo de admissão, atividades extracurriculares, etc
+ Que fique claro que o técnico integrado é diferente de escolas normais -- explicar como essas materias funcionam e que tipo de conteúdo que é ensinado
+ Devem ser traduzidos em inglês, mas não precisam ser assinados
+ Pergunta: Como funciona para quem mudou de escola no nono ano?

** Cartas de recomendação
+ Pedir para pessoas que te acompanharam de perto
+ Escolha seus recommenders sabiamente, mande um email perguntando se eles podem ser seus recommenders, explicar porque escolheu eles, explicar para eles que vc está aplicando para US Colleges, explicar sobre o EducationUS -- application tracker e que o meu mentor pode auxiliar ele na correção de algumas coisas, etc e qualquer dificuldade que você tiver
+ Escreva uma lista de coisas que possa ser destacada na carta -- refresque a memória deles!
+ Possible names: H-Fernanda, H-Flávio, S-Hilton, S-José Ricardo, S-Marco, S-Simone (1 humanities teacher, 1 stem teacher, 1 additional teacher, 1 counseler, 1 peer letter, 1 additional recommender (Iago))
+ As cartas devem contextualizar o candidato no ambiente escolar, por tanto seus recommenders devem compartilhar suas percepções sobre você seja dentro da sala de aula, fora dela ou em um projeto
+ Papel da carta do Counseler: Highlight any special program, how prominent are acitivites/impact in school, any family or personal context we should be aware of, context for student and entire graduating class - A carta do counseler não vai repetir o school profile, mas sim focará em você, no entanto é importante ter em mente o que foi dito no school profile
+ Papel da carta do Professor: Provide a brief introduction of the class for context, Outline academic performance, Highlight distinguishing performance, Be specific and use examples, evitem usar templates (geralmente levam a erros com pronomes) e compartilhar modelos de cartas inteiras.
+ O professor pode utilizar o "Bullet letter of recommendation"

** Homework
+ Contact your recommenders via e-mail (and other modes of communication)
+ Make a list of events that occurred in the recommender classroom or during a project
+ Explain them you are applying to U.S. Colleges. For now, it is necessary to write the letters of recommendation,

* Marcohort 5
+ Think about the connections between the "As I recovered..." "My interest..." bringing people together - how? what did you participate in? in this virtual world or whatever
+ Also try introducing the community first
+ Also try coming back to cycling more like at the bottom of "As I recovered" paragraph
+ At the end, try modifying something as you see fit

* ACT
** Extracurriculars, Honors & Add Info
+ ECAs don't need to have a social impact to be in the application
+ ECAs are simply activities that are not part of the usual school or college course
+ Through them, you showcase abilities you've developed in the past years -> ECAs also tell a lot about who you are
+ ECAs can be any activity that tells you apart
+ Hobbies: Roleplaying, Horticulture club
+ Music: Choir, Musical Interest club, Solo music, Singing lessons, Bands
+ Arts: Writing, annimation, paiting, choreography, puppetry, community theater club, drama club, photography, cartooning, poetry clubs, dance
+ Sports and Recreation: Soccer, Swimming, Ping pong, sports club, martial arts, cheerleading, gymnastics
+ Na hora de elencar as ECAs no common app, colocar as mais relevantes pois só tem 10 vagas...
+ Competitions: Spelling Contest, Poetry Contest, Math Olympiad, Science Olympiad, Language Contest, Essay Contest, Triathlon
+ Language: English clubs, Latin American Studies
+ Discussions and Political Interest: Model UN, Debate Club, Model Congress Club, Parlamento Jovem Brasileiro
+ Programs: improve english, learn/hone general skills, learn about different cultures, engage in special activities, campus visits, special classes, be equipped with leadership skills -> this also justifies a gap year
+ Volunteering: Mentoring, Local Charity, Animal Rescue, International Volunteer Programs, Online/remote volunteering
+ Paid-work interships
+ Research Projects, Extension Projects, Scientific Initiation
+ Some applications may accept portfolios - like MIT
+ Github and website are valid, but you may want to put them on additional information

* Marcohort 6
+ Everything, everwhere at once -> movie recommendation
+ There are lot of "software" words repetition software, freedom... (be mindful of the uses) -> refine it in terms of vocabulary
+ Get the 5th semester grades
+ Start the extracurricular activities and additional information docs
+ Search about universities (Duke, Dartmouth college, Rice university, Northwestern university, tarnford) search about the labs?

* Marcohort 7
+ Use maybe a parelel between programming and cycling, and recover something you said in the text -> create a new last paragraph and put it at the bottom
+ Add additional information in the additional information document -DONE
+ How many people have been impacted since the beginning of it? -DONE
+ Don't use "low-income" use underprevileged -DONE
+ Add the rocket -DONE
+ Duke University Press is not student led -DONE
+ What does IHouse do? -DONE
+ What does Bryan center -DONE
+ Talk more about the quantum center -DONE
+ Research about Duke research abroad universities -WHAT
+ Find more things about research - what do they do there?
+ Relate something to what you are doing to what they are doing -- for instance, the part from Jungsang Kim -DONE

* Ideas
** 1st and 2nd semester
+ Firstly, apply to the research programs. If you don't suceed, go straight to the Linux research (AND FIND A RESEARCHER FROM U.S. TO HELP YOU) <- Very important!
+ In paralel, continue the research with Hilton <- Very important!
+ Also, try your best with Cortez <- Very important!
** 2nd semester
+ Conduct the physics club experiments <- Very important!
+ Improve your rocket! <- Very important!
+ Improve EC! <- Very important!
+ Spend time with Linux (wisely)... <- Very important!
** Future
+ Raspberry pi...

* ACT
** Vocabulary
+ Aid Policy, Financial Aid Office, Need-Blind Policy, Need-Aware Policy, Need-Based Scholarships, Merit-Based Scholarships, Loans, Grants, Work-Study, Endowments, Tuition, Room & Board, Health Insurance, Other Fees, Cost of Attendance
*** Documents
+ Bank Statement, Individual Income Tax Return, Non-filer Tax Return Form, Annual Income Statement, Employer Letter, Pay checks
*** Searching
+ University Grants, Outside Scholarships, Merit Scholarships Programs

** Examples
*** Villanova University
+ Merit-Based Scholarships, Need-based grants, private education loans
+ They are Need-Aware
**** Merit-Based Scholarships
+ Presidential Scholarship
**** Documents
+ CSS Profile, Employer Letter, Bank Statement -> IDOC service and not the office of financial assistance
Merit-based:

Presidential Scholarship
valued at tuition, general fee, room, board and books for eight consecutive semesters)

Due to the high number of eligible applicants, not all students who meet the minimum criteria are offered scholarships

Need-based:

Although a student applying for aid may be academically admissible, not all students will be awarded financial aid due to the limited availability of funding. In addition, all students receiving funds are expected to contribute personally toward educational and personal expenses while attending Villanova University.

+ Imposto de Renda (Exercício 202 | Ano Calendário 2021) ou Declaração Anual de Rendimentos (Exercício 202 | Ano Calendário 2021) para dia 12/06

* Marco
+ 20D

* Marcohort
+ Yo Cientificx info about your interviews...
+ 9th grade honors go into additional information AND all the strikethrough
+ Research the other universities
* Olympiads
** May
+ 07/05 -> 5h (OBA + MOBFOG)
+ 08/05 -> 5h40min (OBA + MOBFOG)
+ 09/05 -> 4h50min (OBA + MOBFOG)
+ 10/05 -> 1h30min (OBA + MOBFOG)
+ 11/05 -> 30min (OBA + MOBFOG)
+ 12/05 -> 3h (OBA + MOBFOG)
+ 13/05 -> 5h30min (OBA + MOBFOG)
+ 14/05 -> 9h30min (OBA + MOBFOG)
+ 15/05 -> 9h (OBA + MOBFOG)
+ 16/05 -> 6h (OBA + MOBFOG)
+ 17/05 -> 5h (OBA + MOBFOG)
+ 18/05 -> 30min (OBA + MOBFOG)
+ 19/05 -> 3h (OBA + MOBFOG)
** June
+ 03/06 -> 3h (OBI)
+ 04/06 -> 3h (OBI)
+ 05/06 -> 2h (OBI) + 1h (OBMEP)
+ 06/06 ->

* English Club
** Registro Escrito
+ Talking about weeks...
+ "Keep calm" "Yesterday yesterday...", "Fracasso...", "Defame", "Bad words - cursing"

* Chemestry apresentation
+ Pesquisas emergentes no campo de estudo de polímeros naturais
