#+TITLE: Annotations

+ Create a schedule to study (you and your brother) - that means strictly defining your goals for what's to come
+ 3+2 double major is not the same as double degree
+ CSS Profile non-custodial waiver (explain why vc n tem contato - documentos judiciais servem)
+ Think about somone in the school to be your consuler (to talk about your bad grade - contextualizar)
+ Apply to Brasa in the second semester (ajuda financeira)
+ Keep an eye on "Design in the command line: Recipes for tasty outcomes" Imagemagick + ffmpeg + bash to create animation for LP work (https://erase.artdel.net/ )
+ Keep an eye on "Living in freedom with GNU Emacs"
+ Course on Open Source applications (Living in freedom with GNU emacs is a good idea!)
+ 42 chapters must be read (physics)
+ Dois prótons e um café: https://www.youtube.com/channel/UCW0Eyk1RrjIWFjgjBy_RR_g, Physikós: https://www.youtube.com/channel/UCIyM6oBSv0qHwxVpCl5Rehw

* Lucas nos eua 1
+ Alguma das 5 mil faculdades vai te dar uma bolsa, mas qual é a certa pra vc?
+ 85% das 5mil faculdades tem mais de 50% de taxa de aceitação
+ 2 Reach, 5 Match, 3 Safety: Estratégia conservadora

** Provando seu amor
+ Feiras de faculs abertas ao público
+ Webinars
+ Solicitando entrevistas e bate papos
+ Emails
+ Receber cartas físicas e posters
+ Tour virtual
+ Aplicar Early

** Oglethrope University (GA) e Trinity University (TX)
+ Exemplos de EA

** Os 4 fits
+ Acadêmico
  - Procure Recursos/Tamanho
  - Olho na grade curricular (Conteúdo é essencial)
+ Cultural
  - Pesquisar experiência/vivência/indenpendência/networking
  - Tamanho/Localização/Clima
  - Dormitórios/Campus/Serviços
  - Clubes/Organizações/Vida Social
+ Financeiro
  - Quantos alunos recebem bolsa?
  - Quantos de bolsa recebem?/Brasileiros?
+ Carreira
  - Procurar career fairs
  - Ver os ex-alumni

** Mínimo-ideal-sonho
+ Mínimo
+ Ideal
+ Sonho

* Lucas nos eua 2
+ Tenha um kit de stalker completo: cada site é uma ferramenta
+ Quem procura acha: estudar cada faculdade (fuçar e clicar)
+ A fila anda: pesquisar faculdades o mais cedo possível

** Tops sites de pesquisa
+ Ranking: [[https://www.usnews.com/best-colleges?int=top_nav_Colleges][US News]]
+ Filtragem: [[https://collegesearch.collegeboard.org/home][Big Future]]
senha: arroz

* Wichita State University
+ Info on telegram



* Education USA
+ 99% universities will have financial aid, but it is important to understand what kind of it
+ It is not university tution you need to worry about (there is also books & supplies, health insurance, room & board, misecellaneous living expenses)
+ Lecture number 4 is really useful (common mistakes to avoid in your application)
+ Additional Information: I NEED TO USE THIS
** Kinds of need
+ Need based: scholarships given based on need (based on family income)
+ Merit based: students receive this based on their special skills, competitiveness, etc
+ Need blind: applicants financial status don't affect their admittion
+ Need aware: applicants financial status affect their admittion
+ Unmet need: the amout you need to pay after the scholarship is applied (what the scholarship doesn't cover)

* New idea
+ Define this "club" goal...
+ "Computação Quântica - Plano de aula com enfoque para o Ensino Médio" will work for thinking about creating the IFMS QC course, but it can be improved...
+ This project should involve particle physics too!
+ Building OPEN SOURCE detectors (particle physics), the Pauli teta QC (wow!)
+ This project may be done in 3 different tracks... classical physics, particle physics and quantum mechanics focused on quantum computing
+ Building a photonics quantum computer (School builds quantum computer to teach students...), but why..

** The why
+ It is scalable
+ It is robust
+ Practical (room temperature, can be easily integrated infrastucturely)
** Materials
+ Optical Table
+ 2 Lasers (One class four, another class 1)
+ EPI for Lasers
+ 1 KDP (monopotassium phosphate) crystal
+ 3 Polarized Beam Splitter (2 for breaking the entanglement + 1 for identification of the measurement)
+ 2 Mirrors (for breakign the entanglement)
+ 1 Photomultiplier Tube (for measurement)
*** Gates
+ 3 Rx gate (1 Rx gate will work as an X gate + 1 Rx gate will work as an H gate + 1 Rx gate will work as a real Rx gate)


* New idea
+ Create a palce (it can be a website) for people to share real world problems
+ I am tired of looking at my country and seeing only problems. I start thinking of a way I could fix them, but it is just too much for one person
+ So I decided to create this place where anyone can share a problem their community have. Someone can come and propose a solution
+ Maybe a social media???????????????


* Colleges test
Suggested Schools: Science: California Institute of Technology, Clarkson University, Georgia Institute of Technology, Harvey Mudd College, Massachusetts Institute of Technology, New Mexico Institute of Mining and Technology, Rensselaer Polytechnic Institute, Texas Tech University Not science: UCLA, University of North Carolina, Penn State, or Michigan State

+ Arduino ATmega328



* LOA
+ Usar mais o quadro-negro como um retorno visual -> a ideia é parecer mais uma aula
+ Outro com aviãozinho (melhorar a volta do avião) e o like é top
+ Pode ser uma boa ideia ter o titulo embaixo da final da intro

* ACT
+ Questão bem geral: A gente aqui no marcohort estamos no processo de escrever histórias que vão levar a gente a escrever um personal statement. Eu também acredito que você deve ter escrito sobre alguns assuntos diferentes antes de ter chego ao tema principal da sua personal statement. O negócio é que eu meio que já estou vendo um caminho claro pra escrita do meu, mas ao ler seu personal statement eu também acabei me identificando com alguns pontos em específico, mesmo que sendo parte de mim, este não encaixaria nessa minha ideia. A pergunta é como tu conseguiu focar pra falar desse assunto?
+ Se o escritor também seja de exatas (Wangheley Soares Martins, Adeildo Viera Silva Neto - CS and physics!, João Vitor Boeachat Torrest Botelho - CS student!): Minha pergunta é simples: como você escreve tão bem? Porque eu tenho a impressão que o pessoal de exatas só sabe números, ou mexer com equipamentos, etc. Eu sempre tive um medo da lingua portuguesa me comer vivo, mas só depois que eu tinha 14 anos e comecei a aprender ingles que eu aprendi a gosta de linguas, e mesmo sendo apaixonado por física e ciência da computação, agora fazendo curso técnico em eletrotécnica, eu tenho que saber me comunicar: seja pra escrever um artigo científico ou pedir uma pizza. Pedir uma pizza ainda é meio dificil, mas eu já entendi a necessidade. Reformulando minha pergunta: como você escreve um texto sobre si considerando possíveis dificuldades linguísticas
+ Dica da Aisha: Listar coisas pra ir escrevendo - coisas que eu to fazendo e porque eu gosto de fazer isso. Colocar pontos de vc que a pessoa que está lendo entenda quem você é! É bom ambientar a galera - a pessoa lendo se sente como você (em um onibus lotado, você se sente limitado... posso fazer algo sobre isso? isso me levou a fazer tal coisa... o quanto vc luta pra se fazer ser ouvido em um espaço limitado, invisibilizado... ou então fazer o contraste desse lugar de injustiça com o que acontece no resto do seu dia). A redação do Boeachat fez ela pensar em como ela pode mostrar as montanhas que ela moveria pra estudar no ensino superior

* English Club
+ 07/05 (Saturday) at 9am - encontro com possíveis novos participantes
+ Encontros afternoon: 13h15-14h
+ Encontros morning: Por enquanto não teremos porque apenas a Estela está disponível
+ Estela ficou responsável pela arte (até 02/05), Natanael ficou responsável pela divulgação no Instagram, Luis ficou responsável pela divulgação no campus por meio dos cartazes da Estela
+ Próximo retorno do Let's Bora 09/05 at 13h15
+ Procurar informações sobre concurso de logos (concursos similares, cores, cabe em um formato circular, valor de prêmio)
+ Em maio, possivelmente divulgaremos nas salas os cursos CENID
+ Em junho, podemos planejar um encontro no parque das nações, possivelmente dia 11/06




* UNESCO Center for Peace
+ They will give a letter to apply for VISA - A visa of tourist is already enough
+ They conver absolutely everything, except for plan ticket to US and VISA
+ They have a facilitator for Brazil
+ Jorge Gonzales number: +5215568560371; Paloma: (+57) 3017787345; Shurabe: smercado@unescocenterforpeace.org

* Mobfog
** Materiais base de lançamento
+ 80cm de cano 20mm (para confecção de 3 canos de 20cm e 20 de 10cm)
+ 1 T de 20mm
+ 2 Cotovelos de 20mm
+ 2 caps de 20mm
+ 1 válvula de camara de bicicleta
+ 1 pedaço de camara de bicileta (pra ajudar na vedação)
+ 1 pedaço de mangueira de áquario (pra ajudar em caso de emergência)
+ 1 cola de PVC
+ 1 balão 6,5
+ 1 espaladrapo largo
+ 4 abraçadeiras de nylon (largua +- 3,6mm)
+ 1 abraçadeira 1cm diametro
+ 1 cano de esgoto 4cm diametro com 3cm de comprimento
** Materiais para o foguete
+ 2 Garrafa PET com o mesmo diâmetro ao longo da sua extensão (600mL - 2L)
  - A primeira garrafa terá as empenas, a segunda garrafa será removida o fundo e ficará em cima da primeira para que tenha mais aerodinâmica
+ Pasta Polionda para as empenas (3-4 empenas)
+ Parafuso de 1/4 de polegada para peso

+ Fanta 2L é 8,5
+ Suco Scheppes é 4,5

** Materiais - Base de lançamento opção 1
+ (15cm + 15cm + 15cm + 15cm + 40cm + 40cm + 25cm + 25cm + 26,5m 2,165m) 2,165m de cano PVC 25mm
+ 22 cm de cano PVC 20mm
+ 1 pedaço (5,5cm) de cano de 40mm
+ 2 Joelhos pra cano 25mm (Temos)
+ 5 Tês para cano 25mm
+ 1 cap para cano 25mm
+ 1 bucha de redução 25mm para 20mm (Temos)
+ 1 abraçadeira de metal
+ 1 manômetro de 150 PSI pra cima
+ 1 espaladrapo (Temos)
+ 8 enforca gato (4 pra válvula e o resto pra apertar) (Temos)
*** Additional
+ Registro esfera 25 mm soldável
+ 2 arruela de vedação 1/4
+ 1 Cap 25mm
+ 1 porca 1/4
+ 1 abraçadeira anel
+ 1 luva de redução 25 para 20mm
** Materiais - Foguete opção 2
** Materiais que não precisarão ser comprados
- serra
- veda rosca
- varetas de churrasco (obrigatórias)
- vaselina
- joelhos de pvc 25mm
- enforca gato
- esparadrapo
- estilete
- fita isolante
- balão (não sei o tamanho)
- garrafa pesa 39,4g
- 9,93cm
- altura 34cm


* ACT
** School Documents
+ Pedir para usar email institucional
+ Pedir para usar cabeçalho da escola ou logo
+ Pedir para assinarem os documentos (principalmente cartas de recomendação)
+ Todos os documentos devem ser traduzidas para inglês
+ Não tem problema os recomendadores não poderem escrever em inglês, o ACT poderá traduzi-los

** Transcripts
+ Históricos oficiais da escola (precisam ter suas notas do 9th grade a 12th)
+ Precisa ser assinado pelo school counseler/director

** School Profile
+ Helps admissions officers interpret the transcript for classes offered, rigor, grading policies and more
+ Também possui informação sobre a escola, administração, tipo de escola, número de estudantes graduando, curriculo, processo de admissão, atividades extracurriculares, etc
+ Que fique claro que o técnico integrado é diferente de escolas normais -- explicar como essas materias funcionam e que tipo de conteúdo que é ensinado
+ Devem ser traduzidos em inglês, mas não precisam ser assinados
+ Pergunta: Como funciona para quem mudou de escola no nono ano?

** Cartas de recomendação
+ Pedir para pessoas que te acompanharam de perto
+ Escolha seus recommenders sabiamente, mande um email perguntando se eles podem ser seus recommenders, explicar porque escolheu eles, explicar para eles que vc está aplicando para US Colleges, explicar sobre o EducationUS -- application tracker e que o meu mentor pode auxiliar ele na correção de algumas coisas, etc e qualquer dificuldade que você tiver
+ Escreva uma lista de coisas que possa ser destacada na carta -- refresque a memória deles!
+ Possible names: H-Fernanda, H-Flávio, S-Hilton, S-José Ricardo, S-Marco, S-Simone (1 humanities teacher, 1 stem teacher, 1 additional teacher, 1 counseler, 1 peer letter, 1 additional recommender (Iago))
+ As cartas devem contextualizar o candidato no ambiente escolar, por tanto seus recommenders devem compartilhar suas percepções sobre você seja dentro da sala de aula, fora dela ou em um projeto
+ Papel da carta do Counseler: Highlight any special program, how prominent are acitivites/impact in school, any family or personal context we should be aware of, context for student and entire graduating class - A carta do counseler não vai repetir o school profile, mas sim focará em você, no entanto é importante ter em mente o que foi dito no school profile
+ Papel da carta do Professor: Provide a brief introduction of the class for context, Outline academic performance, Highlight distinguishing performance, Be specific and use examples, evitem usar templates (geralmente levam a erros com pronomes) e compartilhar modelos de cartas inteiras.
+ O professor pode utilizar o "Bullet letter of recommendation"

** Homework
+ Contact your recommenders via e-mail (and other modes of communication)
+ Make a list of events that occurred in the recommender classroom or during a project
+ Explain them you are applying to U.S. Colleges. For now, it is necessary to write the letters of recommendation,



* ACT
** Extracurriculars, Honors & Add Info
+ ECAs don't need to have a social impact to be in the application
+ ECAs are simply activities that are not part of the usual school or college course
+ Through them, you showcase abilities you've developed in the past years -> ECAs also tell a lot about who you are
+ ECAs can be any activity that tells you apart
+ Hobbies: Roleplaying, Horticulture club
+ Music: Choir, Musical Interest club, Solo music, Singing lessons, Bands
+ Arts: Writing, annimation, paiting, choreography, puppetry, community theater club, drama club, photography, cartooning, poetry clubs, dance
+ Sports and Recreation: Soccer, Swimming, Ping pong, sports club, martial arts, cheerleading, gymnastics
+ Na hora de elencar as ECAs no common app, colocar as mais relevantes pois só tem 10 vagas...
+ Competitions: Spelling Contest, Poetry Contest, Math Olympiad, Science Olympiad, Language Contest, Essay Contest, Triathlon
+ Language: English clubs, Latin American Studies
+ Discussions and Political Interest: Model UN, Debate Club, Model Congress Club, Parlamento Jovem Brasileiro
+ Programs: improve english, learn/hone general skills, learn about different cultures, engage in special activities, campus visits, special classes, be equipped with leadership skills -> this also justifies a gap year
+ Volunteering: Mentoring, Local Charity, Animal Rescue, International Volunteer Programs, Online/remote volunteering
+ Paid-work interships
+ Research Projects, Extension Projects, Scientific Initiation
+ Some applications may accept portfolios - like MIT
+ Github and website are valid, but you may want to put them on additional information



* Ideas
** 1st and 2nd semester
+ Firstly, apply to the research programs. If you don't suceed, go straight to the Linux research (AND FIND A RESEARCHER FROM U.S. TO HELP YOU) <- Very important!
+ In paralel, continue the research with Hilton <- Very important!
+ Also, try your best with Cortez <- Very important!
** 2nd semester
+ Conduct the physics club experiments <- Very important!
+ Improve your rocket! <- Very important!
+ Improve EC! <- Very important!
+ Spend time with Linux (wisely)... <- Very important!
** Future
+ Raspberry pi...

* ACT
** Vocabulary
+ Aid Policy, Financial Aid Office, Need-Blind Policy, Need-Aware Policy, Need-Based Scholarships, Merit-Based Scholarships, Loans, Grants, Work-Study, Endowments, Tuition, Room & Board, Health Insurance, Other Fees, Cost of Attendance
*** Documents
+ Bank Statement, Individual Income Tax Return, Non-filer Tax Return Form, Annual Income Statement, Employer Letter, Pay checks
*** Searching
+ University Grants, Outside Scholarships, Merit Scholarships Programs

** Examples
*** Villanova University
+ Merit-Based Scholarships, Need-based grants, private education loans
+ They are Need-Aware
**** Merit-Based Scholarships
+ Presidential Scholarship
**** Documents
+ CSS Profile, Employer Letter, Bank Statement -> IDOC service and not the office of financial assistance
Merit-based:

Presidential Scholarship
valued at tuition, general fee, room, board and books for eight consecutive semesters)

Due to the high number of eligible applicants, not all students who meet the minimum criteria are offered scholarships

Need-based:

Although a student applying for aid may be academically admissible, not all students will be awarded financial aid due to the limited availability of funding. In addition, all students receiving funds are expected to contribute personally toward educational and personal expenses while attending Villanova University.

+ Imposto de Renda (Exercício 202 | Ano Calendário 2021) ou Declaração Anual de Rendimentos (Exercício 202 | Ano Calendário 2021) para dia 12/06

* Marco
+ 20D


* English Club
** Registro Escrito
+ Talking about weeks...
+ "Keep calm" "Yesterday yesterday...", "Fracasso...", "Defame", "Bad words - cursing"

* LOA
+ Criador de conteúdo - 2 (inclui roteirista)
+ Editor de Vídeo - 1
+ Gerenciador de Mídias Sociais - 1

+ Desenvolvedor de Software - Verificar com Gustavo
+ Gestor de projetos e parcerias - Verificar com Iago
+ Gestor de interação - Verificar com Iago

* ATC
Group 1 https://mitadmissions.org/apply/firstyear/essays-activities-academics/ https://college.harvard.edu/guides/application-tips Group 2 https://www.amherst.edu/admission/apply/firstyear/writingsupplement https://www.bu.edu/admissions/tuition-aid/scholarships-financial-aid/first-year-merit/trustee/ Group 3 https://admission.stanford.edu/apply/freshman/apply.html https://blog.emoryadmission.com/2021/06/emory_saq2021/ Group 4 https://collegeadmissions.uchicago.edu/apply/uchicago-supplemental-essay-questions

** MIT
+ Consists of several short essays (5) --MIT não usa common application system

+ Describe the world you come from; for example, your family, clubs, school, community, city or town. How has that world shaped your dreams and aspirations? (250 words or fewer) --personal statement
+ Pick what field of study at MIT appeals to you the most right now, and tell us more about why this field of study appeals to you. (100 words or fewer) --Why major?
+ We know you lead a busy life, full of activities, many of which are required of you. Tell us about something you do simply for the pleasure of it. (200–250 words) --Hobbies
+ At MIT, we bring people together to better the lives of others. MIT students work to improve their communities in different ways, from tackling the world’s biggest challenges to being a good friend. Describe one way in which you have contributed to your community, whether in your family, the classroom, your neighborhood, etc. (200–250 words) --Social impact
+ Tell us about a significant challenge you’ve faced or something that didn’t go according to plan that you feel comfortable sharing. How did you manage the situation? (200-250 words) --personal statement

** Harvard
+ Harvard Questions
+ Writing Supplement (Pode mandar uma que já escreveu ou 10 examples)
Achamos confuso!

+ Unusual circumstances in your life --Context
+ Travel, living, or working experiences in your own or other communities
+ What you would want your future college roommate to know about you
+ An intellectual experience (course, project, book, discussion, paper, poetry, or research topic in engineering, mathematics, science or other modes of inquiry) that has meant the most to you
+ How you hope to use your college education
+ A list of books you have read during the past twelve months
+ The Harvard College Honor code declares that we “hold honesty as the foundation of our community.” As you consider entering this community that is committed to honesty, please reflect on a time when you or someone you observed had to make a choice about whether to act with integrity and honesty.
+ The mission of Harvard College is to educate our students to be citizens and citizen-leaders for society. What would you do to contribute to the lives of your classmates in advancing this mission?
+ Each year a substantial number of students admitted to Harvard defer their admission for one year or take time off during college. If you decided in the future to choose either option, what would you like to do?
+ Harvard has long recognized the importance of student body diversity of all kinds. We welcome you to write about distinctive aspects of your background, personal development or the intellectual interests you might bring to your Harvard classmates.

+ Not all short questions are supplemental essays, because some require you to be very objective
+ Analise o que tu já escreveu em outras partes da sua app pra nao ficar repetitivo
+ Alimony goes as supplementaldoc

* Marcohort
+ Stimate how much you improved students' grades DONE
+ Check with Ronaldinho the partipants + add how many projects in fecintec DONE
+ Briefly explain your condition today - commute to school + healt DONE
+ Search more about stanford classes DONE

* Marcohort
+ Literally explain metaphors
+ Follow up + Weekly things + Examples reading + Three short essays

* Marcohort 2
+ I don't get how music is applied into your life (how you feel), and give the example. He doesn't illustrate how it is important music in his context... <- Just Add things in another color, don't delete;
+ The music story will probably not become a personal statement, probably something for a supplemental essay
+ They cycling thing (the imposed limitation here... how?) and the autoimmune disease (focus on how you life were before and how you had to adjust, what you had to do differently like mentally, etc - how did you feel about it? - some limitations were imposed on me, how you feel about it?)

* Marcohort 3
+ "Since I was a child..." - Explain better the consequences of the disease (BE MORE IMPACTFUL) + Explain how you adjusted to your new life (Introduce Linux!!! Explain it is a different kind of freedom, and you get that, my disease allowed me to develop passion for tech - idea: having a change of scnerio, being excited differently)
+ In the story 3 second paragraph, maybe explain what freedom means for you now
+ Perguntar sobre o histórico parcial na escola

* Marcohort 4
+ In paragraph 4, be more clear/straitforward "To add up, I could not go outside yet. Sun was boiling eggs in the pavement, and Covid-19 was running rampant. So, I stay in my room, quiet and alone. I press a button, and a beast silently awakens. I keep staring at the screen, as if the shiny letters could hurt my reality even more. But all it does is ask who I am. As I prompt my user data, I am reminded how trustworthy the system I modified is, and I could also use, study, improve, and share it as I pleased." Try using less metaphors and ryme less, because you already used them in the beginning.
+ You have to be very clear that coding is very important
+ Have a final paragraph saying you can't cycle and it sucks (even though my freedom was removed), but this issue allowed me to discover something else, to explore more about this world.
+ I will need my parcial transcript + transcript

Luís Guilherme Miranda Spengler is currently a High School senior, taking electrotechnology vocational program at Instituto Federal do Mato Grosso do Sul. He is very engaged in the activities from his school, and takes great interest in activities involving research, volunteering and teaching.

During the pandemic, Luís was one of the most engaged students from his school, where he developed research, and coordinated at English Club. As a result of this, his team won Fecintec and were invited to participate in Mostra Nacional Itinerante das Feiras de Ciências. As a 1-year Quantum Computing student at the Qubit by Qubit program for high school students, he could learn more about an exciting career that is changing the world for the better, with its state-of-the-art innovations. He makes it his personal goal to somehow contribute to the Quantum Computing field.

Currently, he is preparing for the application process with the help of EducationUSA Application Tracker project. Meanwhile, he works on other projects he knows will also make an impact on his community, and hopes US colleges will notice his hard work and dedication.

* Marcohort 5
+ Think about the connections between the "As I recovered..." "My interest..." bringing people together - how? what did you participate in? in this virtual world or whatever
+ Also try introducing the community first
+ Also try coming back to cycling more like at the bottom of "As I recovered" paragraph
+ At the end, try modifying something as you see fit

* Marcohort 6
+ Everything, everwhere at once -> movie recommendation
+ There are lot of "software" words repetition software, freedom... (be mindful of the uses) -> refine it in terms of vocabulary
+ Get the 5th semester grades
+ Start the extracurricular activities and additional information docs
+ Search about universities (Duke, Dartmouth college, Rice university, Northwestern university, tarnford) search about the labs?

* Marcohort 7
+ Use maybe a parelel between programming and cycling, and recover something you said in the text -> create a new last paragraph and put it at the bottom
+ Add additional information in the additional information document -DONE
+ How many people have been impacted since the beginning of it? -DONE
+ Don't use "low-income" use underprevileged -DONE
+ Add the rocket -DONE
+ Duke University Press is not student led -DONE
+ What does IHouse do? -DONE
+ What does Bryan center -DONE
+ Talk more about the quantum center -DONE
+ Research about Duke research abroad universities -WHAT
+ Find more things about research - what do they do there?
+ Relate something to what you are doing to what they are doing -- for instance, the part from Jungsang Kim -DONE

* Marcohort
+ Yo Cientificx info about your interviews...
+ 9th grade honors go into additional information AND all the strikethrough
+ Research the other universities

* Marcohort (18/06)
+ We will go back on the ECAs later to check for things -- keep in mind I still have GTwins to write about
+ Create a google sheets template for college search -DONE
+ Create a google sheets | Application Tracker - DONE - In Progress
+ It is mandatory to get my father's documents -> Imposto de renda COMPLETO
+ Continue searching for next week
+ Add the drive folder for each teacher and the document -> Contact them
+ Next week we will start organizing for me to start writing the supplemental essays
+ Visit the College Essay Guy links on google classroom
+ Organize individual folders for each university (write the full university name)
+ Create google docs and write down the prompts-1 prompt per page (use page breaks)

* Marcohort
+ Specific stuff in 1st and 2nd paragrahps -- good, but you need to shorten it
+ The last paragraph is too general -- delete it
+ Introduce other things you could do at Duke -- asides from academics -- try to find connections
+ Homework: Focus on rewriting the why duke essay + writing the duke background essay + finish the research + add universities + try to do a why essay or extracurricular essay

* ATC
+ Why this community essay
+ Why this major essay
+ Why this college essay

+ How would you approach this prompt?
Basicamente tu tem que refletir no seu futuro e imaginar indo nessa faculdade pra conseguir isso. Dá pra pensar no why college essays em como você aprova a faculdade em te ajudar no que tu quer fazer no futuro, não pensa nisso como a faculdade te avaliando, mas em você avaliando ela, porque aí dá pra criar um fit muito bom

+ Where could you find the necessary information?
- Through college searching, throught self-thinking, assistam videos de campus, entendam a geografia de onde fica a faculdade -- só pra dar você realmente se imaginar indo lá

* Reuniao GEDUC + LOA
+ Parceria com pitagóricos para preparação de seletivas + indicar participação no discord? - FALAR COM ELES
+ Brainstorming com cargos específicos no servidor - FAZER ISSO
+ Breakouts com perguntas especificas para as seletivas de astronomia -- o que te levou a ficar interessado em astronomia -- assim aumentamos o engagamento do pessoal. Vai ter kahoot?
+ Fazer brainstorming de canais do youtube que a gente pode fazer divulgação do servidor - FAZER ISSO
+ Canal de memes (off-topic) + sugestão (server info) + desafios semanais ()



* EC
+ Primeira logo em 2017, segunda em 2020 -> está em memories

* ACT - SUPER MEETING
** General
+ João says 5 classes is recommended for a double major and he has a very flexible routine -- Is it really that flexible?
+ Diego +5516988113432 , coelhorodriguesdiego@gmail.com
** DUKE -- João Vitor Boechat -- Computer Science;
vitorboechatbotelho@gmail.com
whatsapp: +19843779581
** NORTHWESTERN -- Davi Maciel -- Computer Science; Kaio Kumagai -- Biomedical Engineering
*** Kaio
+ Quarter system -> Kaio describes it as accelerated
+ Kaio  +1 847 907 1146, kaiokumagai2025@u.northwestern.edu
*** Davi
+ 1st quarter -> He was trying to explore a lot of things... It seems like his biggest task was the even nights to get points for the dorm
+ 2nd quarter ->
+ 3rd quarter ->
+ He says there is a lab for CS students -- Is it like an informatics lab?
+ He says the campus is very pretty and nice to walk

* Dartmouth
+ You'll learn how to be outdoors (nice hehe)
+ All research is funded at Dartmouth and it is really easy to get into a research opportunity
+ You are housed between 6 houses communities on. You are only required to live on campus in the freshman year, but most students do all 4 years
+ Dartmouth accepts peer recommendation

* Tufts
+ Tufts doesn't have a core curriculum, but it has distribution requirements
+ Tufts is having a direct line to Boston ready by fall 2022
+ Q: Can you tell me a bit about the free and open source software community at Tufts? I know there is the Tufts GNU/Linux users group and I even joined their Discord group this week. I also heard about JumboCode that helps non-profit orgs in desigining new free tech.
+ Host's email: theresa.quinto@tufts.edu
+ Moizes H. S. Almeida -> CS + ECON at Tufts
+ Tufts has like 6 campus: 4 in Boston, One area in Boston, called Boston + Davis Square, One in France where they offer a 6-week summer program
+ Tufts students are limitless, rarely someone is going to tell you can't do this and this at the same time
+ Financial Aid docs CSS Profile, Tax Documents via IDOC

* Northwestern
+ It is very easy to take classes between the 6 schools of theirs
* Duke
+ Aldeido Viera Silva Neto -> CS + Physics at Duke

* Video
+ Title: Ep 1. Learning in 6 months: 3 Olympiad medals, 1500+ SAT
Hello guys, welcome to this channel's first video. Let me tell you right away that I don't know how this is going to go at all. But I know I have chances on succeding and if I did, I would want to share this with you. That's what the channel is about, documented learning. I wish I had done that when I was learning English for the time that actually worked, because as time passess you start forgeting how you learned that, all that was required of you to do it. And for all the people that asked my how they could learn English, well, you are not going to learn English out of this video, but if it succeds you will see me taking on challenges of language learning as well as other stuff, so stay tuned.
 + Why am I doing this? Let's start by what I am doing. I am attempting to get Gold medal on two scientific olympiads, and a math one, as well as getting a 1500+ SAT as an international student. My main reason for it is to increase my college competitiveness. For those of you who don't know, I am a senior at High School, and brazilian. Our high school is devided in three years, 9th grade counts only for middle school here btw. So, I have some cool extracurriculars, things I am actually proud of. My grades are also really good, but there is a specific 6 months period, the beginning of my Junior year where I didn't go to class. It was in the middle of Covid-19 pandemic, and I was to say, depressed. I failed two school subjects, and I dropped what was to be a 9.4/10 score, for a 8.7/10. Everyday I wake up I feel like I screw up, this challenge will also be one thing to help me with this feeling.

* Marcohort
+ Get everything together in why duke, if it is the same subject.
+ Show more concrete examples you looked for the stuff at Duke, similar to the mentions of Brown Lab.
+ At third paragraph... "Besides academics, it will be great to hang out..."
+ The last part "hang out at Duke's.." try to find something unique, odd, strange that few people would say it.
+ What if in the first paragraph you connected to things you are doing in Brazil about these subjects and finish with saying you can also do that at Duke. The second paragraph you focus on specifics on how they accomplish that and help you do those stuff.
+ In the community essay, focus on something more specific.
+ You can try music, but introduce the whole family in a paragraph. How they play different instruments. The second paragraph can be talking about how they influeced you, how they made you use music in many contexts.
+ Homework: Focus on Duke and the scholarship essays. You can work on some college search in the spare time.

* Vinicus -> Columbia
+ é bom explorar aulas de humanas em columbia.
+ tem core curriculum
+ no competition for research there

* AdAstra
+ Pedir para a Paola entrar em contato com os canais de divulgação astronomica
+ Mudança do objetivo de contato com pitagóricos: vamos contribuir com lista de exercícios e simulados
+ Adicionar os cargos de moderador do discord do fórum Ad Astra no recrutamento da LOA?
+ Sala de notícias relacionados a olimpiadas no server
+ Prática com o pessoal sobre o James Webb, como isso pode cair nas olimpiadas, etc.
+ Próxima reunião Domingo ás 13h

* Marcohort
+ Put the verbs in the future to look better (done)
+ The ending may be missing something
+ Add a PS easter egg when you talk about cyclng. (done)

+ Double check some of the universities you added for their requirements (done)

+ Go to Rice university supplemental essays (done)

+ At Essay 1 you should be very specific (paragraph 2, 3). Meaning, fulfilling. Use these words as you explain why you would take a break. You can also mention what makes you happy today, what you know today that you can do in the future.

+ At Essay 2 there is a very big sentence at paragraph 1. Focus a bit more on the importance of the issue "We can address these issues more effectively". Advancing quantum computing in Brazil is something you look forward to. At third paragraph, try doing the Brazil thing + summarizing everything you learned in the course in once sentence. "It is no wonder that things are like that, because something lacks." "It is no accident that QC"

* Marcohort
+ Why Duke essay first paragraph... (done)
+ Why Duke essay be more specific about the professor (done)
+ How you see yourself achieving your goals in the future, future areas (why major rice essay)
+ Sunday at 7pm
+ Try to bring new light on the community essay (focus on the linux club question on community essay) -- bring something more personal

* Loa + geduc
+ Reunião de integração 06/08 às 19h
+ Marcar reunião com joão victor e mandar lá no grupo
+ Publicar o processo seletivo da loa no canal do telegram

* Marcohort
+ Ad Astra movie
+ Finishing the rice, duke, and open philanthropy essay

* Common-Appy
** Dúvidas
+ High School name é pra incluir em português e com acento? O que é o CEEB code? Should IF be classified as Charter School? (R: em português)
+ "If you have attended any secondary/high schools not listed in the previous section, please indicate the number of schools." -> Should I add my 9th grade school?
+ Please provide details about why you left each of the above secondary/high schools.
+ "Please list all courses you are taking this academic year. If you are not currently enrolled, please list courses from your most recent academic year.
How many courses would you like to report?" -> 28. Chemestry 4, Biology 4, History (3,4), Mathematics (5,6,3), Physical Education 5, Philosophy 3, Sociology 3, Statistics (8). Control and Instrumentation, Microcontroled and Digital Systems, Reneable Energy and Environment, Inovation and Entreperneuship, Generation, Transmission and Energy Distrubuition, Personal and Professional Orientation (15)
+ "Honors" comes all our honors now?
+ Senior Secondary Leaving Examinations. Should I put yes?

* ATC
+ Use the same email through the app process
+ 23 de setemebro bithrday do marco. Rua Manoel Correia da Costa Neto, 1. Tabuleiro do Martins. Maceió, Alagoas.
+ Graduating Class size -> coloca o mesmo que todos (aplicantes e counselers)

* Marcohort
+ Rewrite some expressions
+ Finish all the essays (duke, rice, philanthropy)

+ Mencionar que um plano de trabalho

+ USBEmato grosso do sul
+ instagram da embaixada

* Rec letters
+ CANNOT identify a college as recepient -> all colleges will receive the app on common app
+ Send them an e-mail asking them to be your recommenders. Explain them why you chose them. Explain them that you are applying to U.S.
+ Pedir para usar email institucional
+ Pedir para usar cabeçalho da escola ou logo
+ Pedir para assinarem os documentos (principalmente cartas de recomendação)
+ Todos os documentos devem ser traduzidas para inglês
+ Não tem problema os recomendadores não poderem escrever em inglês, o ACT poderá traduzi-los
+ Pedir para pessoas que te acompanharam de perto
+ Escolha seus recommenders sabiamente, mande um email perguntando se eles podem ser seus recommenders, explicar porque escolheu eles, explicar para eles que vc está aplicando para US Colleges, explicar sobre o EducationUS -- application tracker e que o meu mentor pode auxiliar ele na correção de algumas coisas, etc e qualquer dificuldade que você tiver
+ Escreva uma lista de coisas que possa ser destacada na carta -- refresque a memória deles!
+ Possible names: H-Fernanda, H-Flávio, S-Hilton, S-José Ricardo, S-Marco, S-Simone (1 humanities teacher, 1 stem teacher, 1 additional teacher, 1 counseler, 1 peer letter, 1 additional recommender (Iago)) -> Fernanda (humanities teacher), Ronaldim (STEM teacher), Marco (additional teacher), Simone (additional teacher), Flávio (counseler letter), Raquel (peer letter)

+ As cartas devem contextualizar o candidato no ambiente escolar, por tanto seus recommenders devem compartilhar suas percepções sobre você seja dentro da sala de aula, fora dela ou em um projeto
+ Papel da carta do Counseler: Highlight any special program, how prominent are acitivites/impact in school, any family or personal context we should be aware of, context for student and entire graduating class - A carta do counseler não vai repetir o school profile, mas sim focará em você, no entanto é importante ter em mente o que foi dito no school profile
+ Papel da carta do Professor: Provide a brief introduction of the class for context, Outline academic performance, Highlight distinguishing performance, Be specific and use examples, evitem usar templates (geralmente levam a erros com pronomes) e compartilhar modelos de cartas inteiras.
+ O professor pode utilizar o "Bullet letter of recommendation"
** Chosen names
+ OBG 1: Fernanda (humanities teacher)
+ OBG 2/OPT1: Ronaldim (STEM teacher)
+ OPT1/OPT2: Marco (additional teacher)
+ OPT2/OPT3: Simone (additional teacher)
+ MANDATORY: Flávio (counseler letter)
+ OPTIONAL: Raquel (peer letter)
** By college:
+ Boston University -> OBG1, OPT1, OPT2 or OPTIONAL
+ Brown University -> OBG1, OBG2, OPT1, OPT2, OPTIONAL
+ Columbia University -> OBG1, OBG2, OPT1 or OPT2
+ Cornell University -> OBG1, OBG2, OPT1, OPT2, OPTIONAL
+ Dartmouth University -> OBG1, OBG2, OPT1, OPT2 or OPTIONAL
+ Duke University -> OBG1, OBG2, OPT1, OPT2 or OPTIONAL
+ Emory University -> OBG1, OBG2, OPT1, OPT2, OPTIONAL
+ Haveford College -> OBG1, OBG2, OPT1, OPT2, OPTIONAL
+ Northwestern University -> OBG1, OPT1, OPT2, OPT3, OPTIONAL
+ Oberlin College of Arts and Sciences -> OBG1, OBG2, OPT1, OPT2, OPTIONAL
+ Rice University -> OBG1, OBG2, OPT1
+ Stanford University -> OBG1, OBG2, OPT1 or OPTIONAL
+ Swarthmore College -> OBG1, OBG2, OPT1, OPT2, OPTIONAL
+ Tufts University -> OBG1, OPT1, OPT2
+ University of Chicago -> OBG1, OBG2, OPT1, OPT2, OPTIONAL
+ University of Notre Dame -> OBG1, OPT1 or OPTIONAL
+ University of Pennsylvania -> OBG1, OPT1, OPT2, OPT3
+ Washington and Lee University -> OBG1, OBG2, OPT1, OPT2
+ Williams College -> OBG1, OBG2, OPT1, OPT2, OPTIONAL
+ Yale University -> OBG1, OBG2

* Talk with Nobel
+ The greatest scientists are fooling around scientists
+ Curiosity-driven reasearch is awesome
+ Challenge today: Implement quantum erro-correciton that is more effective
+ The more diversity you have in your team, the more likely you are to make progress
* Olympiads
** 2019 (9th grade)
5h/w for 32 weeks
** May
+ 07/05 -> 5h (OBA + MOBFOG)
+ 08/05 -> 5h40min (OBA + MOBFOG)
+ 09/05 -> 4h50min (OBA + MOBFOG)
+ 10/05 -> 1h30min (OBA + MOBFOG)
+ 11/05 -> 30min (OBA + MOBFOG)
+ 12/05 -> 3h (OBA + MOBFOG)
+ 13/05 -> 5h30min (OBA + MOBFOG)
+ 14/05 -> 9h30min (OBA + MOBFOG)
+ 15/05 -> 9h (OBA + MOBFOG)
+ 16/05 -> 6h (OBA + MOBFOG)
+ 17/05 -> 5h (OBA + MOBFOG)
+ 18/05 -> 30min (OBA + MOBFOG)
+ 19/05 -> 3h (OBA + MOBFOG)
+ HOURS: 59h | DAYS: 13 days | H/D: 4h32min
** June
+ 03/06 -> 3h (OBI)
+ 04/06 -> 3h (OBI)
+ 05/06 -> 2h (OBI) + 1h (OBMEP)
+ HOURS: 8h | DAYS: 3 days | H/D: 2h40min
** August
+ Multiply by 0,5h each block + level 1 exercise (OBF)
+ 40h (OBF)
** September

* Raquel
+ She acts quick when solving problems
+ She believes in education -> Demonstrates that when deciding the future leaders of our country, in her social projects

* Empreendedorismo e inovação
after 2. Como você acredita que sua vida estaria se não tivesse aberto esse negócio?
1.

* School profile
+
