#+TITLE: Annotations

+ Create a schedule to study (you and your brother) - that means strictly defining your goals for what's to come
+ 3+2 double major is not the same as double degree
+ CSS Profile non-custodial waiver (explain why vc n tem contato - documentos judiciais servem)
+ Think about somone in the school to be your consuler (to talk about your bad grade - contextualizar)
+ Apply to Brasa in the second semester (ajuda financeira)
+ Keep an eye on "Design in the command line: Recipes for tasty outcomes" Imagemagick + ffmpeg + bash to create animation for LP work (https://erase.artdel.net/ )
+ Keep an eye on "Living in freedom with GNU Emacs"
+ Course on Open Source applications (Living in freedom with GNU emacs is a good idea!)
+ 42 chapters must be read (physics)
+ Dois prótons e um café: https://www.youtube.com/channel/UCW0Eyk1RrjIWFjgjBy_RR_g, Physikós: https://www.youtube.com/channel/UCIyM6oBSv0qHwxVpCl5Rehw

* Lucas nos eua 1
+ Alguma das 5 mil faculdades vai te dar uma bolsa, mas qual é a certa pra vc?
+ 85% das 5mil faculdades tem mais de 50% de taxa de aceitação
+ 2 Reach, 5 Match, 3 Safety: Estratégia conservadora

** Provando seu amor
+ Feiras de faculs abertas ao público
+ Webinars
+ Solicitando entrevistas e bate papos
+ Emails
+ Receber cartas físicas e posters
+ Tour virtual
+ Aplicar Early

** Oglethrope University (GA) e Trinity University (TX)
+ Exemplos de EA

** Os 4 fits
+ Acadêmico
  - Procure Recursos/Tamanho
  - Olho na grade curricular (Conteúdo é essencial)
+ Cultural
  - Pesquisar experiência/vivência/indenpendência/networking
  - Tamanho/Localização/Clima
  - Dormitórios/Campus/Serviços
  - Clubes/Organizações/Vida Social
+ Financeiro
  - Quantos alunos recebem bolsa?
  - Quantos de bolsa recebem?/Brasileiros?
+ Carreira
  - Procurar career fairs
  - Ver os ex-alumni

** Mínimo-ideal-sonho
+ Mínimo
+ Ideal
+ Sonho

* Lucas nos eua 2
+ Tenha um kit de stalker completo: cada site é uma ferramenta
+ Quem procura acha: estudar cada faculdade (fuçar e clicar)
+ A fila anda: pesquisar faculdades o mais cedo possível

** Tops sites de pesquisa
+ Ranking: [[https://www.usnews.com/best-colleges?int=top_nav_Colleges][US News]]
+ Filtragem: [[https://collegesearch.collegeboard.org/home][Big Future]]
senha: arroz

* Wichita State University
+ Info on telegram

* Marcohort
+ Literally explain metaphors
+ Follow up + Weekly things + Examples reading + Three short essays

* Education USA
+ 99% universities will have financial aid, but it is important to understand what kind of it
+ It is not university tution you need to worry about (there is also books & supplies, health insurance, room & board, misecellaneous living expenses)
+ Lecture number 4 is really useful (common mistakes to avoid in your application)
+ Additional Information: I NEED TO USE THIS
** Kinds of need
+ Need based: scholarships given based on need (based on family income)
+ Merit based: students receive this based on their special skills, competitiveness, etc
+ Need blind: applicants financial status don't affect their admittion
+ Need aware: applicants financial status affect their admittion
+ Unmet need: the amout you need to pay after the scholarship is applied (what the scholarship doesn't cover)

* New idea
+ Define this "club" goal...
+ "Computação Quântica - Plano de aula com enfoque para o Ensino Médio" will work for thinking about creating the IFMS QC course, but it can be improved...
+ This project should involve particle physics too!
+ Building OPEN SOURCE detectors (particle physics), the Pauli teta QC (wow!)
+ This project may be done in 3 different tracks... classical physics, particle physics and quantum mechanics focused on quantum computing
+ Building a photonics quantum computer (School builds quantum computer to teach students...), but why..

** The why
+ It is scalable
+ It is robust
+ Practical (room temperature, can be easily integrated infrastucturely)
** Materials
+ Optical Table
+ 2 Lasers (One class four, another class 1)
+ EPI for Lasers
+ 1 KDP (monopotassium phosphate) crystal
+ 3 Polarized Beam Splitter (2 for breaking the entanglement + 1 for identification of the measurement)
+ 2 Mirrors (for breakign the entanglement)
+ 1 Photomultiplier Tube (for measurement)
*** Gates
+ 3 Rx gate (1 Rx gate will work as an X gate + 1 Rx gate will work as an H gate + 1 Rx gate will work as a real Rx gate)

* Marcohort 2
+ I don't get how music is applied into your life (how you feel), and give the example. He doesn't illustrate how it is important music in his context... <- Just Add things in another color, don't delete;
+ The music story will probably not become a personal statement, probably something for a supplemental essay
+ They cycling thing (the imposed limitation here... how?) and the autoimmune disease (focus on how you life were before and how you had to adjust, what you had to do differently like mentally, etc - how did you feel about it? - some limitations were imposed on me, how you feel about it?)

* New idea
+ Create a palce (it can be a website) for people to share real world problems
+ I am tired of looking at my country and seeing only problems. I start thinking of a way I could fix them, but it is just too much for one person
+ So I decided to create this place where anyone can share a problem their community have. Someone can come and propose a solution
+ Maybe a social media???????????????


* Colleges test
Suggested Schools: Science: California Institute of Technology, Clarkson University, Georgia Institute of Technology, Harvey Mudd College, Massachusetts Institute of Technology, New Mexico Institute of Mining and Technology, Rensselaer Polytechnic Institute, Texas Tech University Not science: UCLA, University of North Carolina, Penn State, or Michigan State
