#+TITLE: Annotations

+ Create a schedule to study (you and your brother) - that means strictly defining your goals for what's to come
+ 3+2 double major is not the same as double degree
+ CSS Profile non-custodial waiver (explain why vc n tem contato - documentos judiciais servem)
+ Think about somone in the school to be your consuler (to talk about your bad grade - contextualizar)
+ Apply to Brasa in the second semester (ajuda financeira)
+ Keep an eye on "Design in the command line: Recipes for tasty outcomes" Imagemagick + ffmpeg + bash to create animation for LP work (https://erase.artdel.net/ )
+ Keep an eye on "Living in freedom with GNU Emacs"
+ Course on Open Source applications (Living in freedom with GNU emacs is a good idea!)
+ 42 chapters must be read (physics)
+ Dois prótons e um café: https://www.youtube.com/channel/UCW0Eyk1RrjIWFjgjBy_RR_g, Physikós: https://www.youtube.com/channel/UCIyM6oBSv0qHwxVpCl5Rehw

* Lucas nos eua 1
+ Alguma das 5 mil faculdades vai te dar uma bolsa, mas qual é a certa pra vc?
+ 85% das 5mil faculdades tem mais de 50% de taxa de aceitação
+ 2 Reach, 5 Match, 3 Safety: Estratégia conservadora

** Provando seu amor
+ Feiras de faculs abertas ao público
+ Webinars
+ Solicitando entrevistas e bate papos
+ Emails
+ Receber cartas físicas e posters
+ Tour virtual
+ Aplicar Early

** Oglethrope University (GA) e Trinity University (TX)
+ Exemplos de EA

** Os 4 fits
+ Acadêmico
  - Procure Recursos/Tamanho
  - Olho na grade curricular (Conteúdo é essencial)
+ Cultural
  - Pesquisar experiência/vivência/indenpendência/networking
  - Tamanho/Localização/Clima
  - Dormitórios/Campus/Serviços
  - Clubes/Organizações/Vida Social
+ Financeiro
  - Quantos alunos recebem bolsa?
  - Quantos de bolsa recebem?/Brasileiros?
+ Carreira
  - Procurar career fairs
  - Ver os ex-alumni

** Mínimo-ideal-sonho
+ Mínimo
+ Ideal
+ Sonho

* Lucas nos eua 2
+ Tenha um kit de stalker completo: cada site é uma ferramenta
+ Quem procura acha: estudar cada faculdade (fuçar e clicar)
+ A fila anda: pesquisar faculdades o mais cedo possível

** Tops sites de pesquisa
+ Ranking: [[https://www.usnews.com/best-colleges?int=top_nav_Colleges][US News]]
+ Filtragem: [[https://collegesearch.collegeboard.org/home][Big Future]]
senha: arroz

* Wichita State University
+ Info on telegram



* Education USA
+ 99% universities will have financial aid, but it is important to understand what kind of it
+ It is not university tution you need to worry about (there is also books & supplies, health insurance, room & board, misecellaneous living expenses)
+ Lecture number 4 is really useful (common mistakes to avoid in your application)
+ Additional Information: I NEED TO USE THIS
** Kinds of need
+ Need based: scholarships given based on need (based on family income)
+ Merit based: students receive this based on their special skills, competitiveness, etc
+ Need blind: applicants financial status don't affect their admittion
+ Need aware: applicants financial status affect their admittion
+ Unmet need: the amout you need to pay after the scholarship is applied (what the scholarship doesn't cover)

* New idea
+ Define this "club" goal...
+ "Computação Quântica - Plano de aula com enfoque para o Ensino Médio" will work for thinking about creating the IFMS QC course, but it can be improved...
+ This project should involve particle physics too!
+ Building OPEN SOURCE detectors (particle physics), the Pauli teta QC (wow!)
+ This project may be done in 3 different tracks... classical physics, particle physics and quantum mechanics focused on quantum computing
+ Building a photonics quantum computer (School builds quantum computer to teach students...), but why..

** The why
+ It is scalable
+ It is robust
+ Practical (room temperature, can be easily integrated infrastucturely)
** Materials
+ Optical Table
+ 2 Lasers (One class four, another class 1)
+ EPI for Lasers
+ 1 KDP (monopotassium phosphate) crystal
+ 3 Polarized Beam Splitter (2 for breaking the entanglement + 1 for identification of the measurement)
+ 2 Mirrors (for breakign the entanglement)
+ 1 Photomultiplier Tube (for measurement)
*** Gates
+ 3 Rx gate (1 Rx gate will work as an X gate + 1 Rx gate will work as an H gate + 1 Rx gate will work as a real Rx gate)


* New idea
+ Create a palce (it can be a website) for people to share real world problems
+ I am tired of looking at my country and seeing only problems. I start thinking of a way I could fix them, but it is just too much for one person
+ So I decided to create this place where anyone can share a problem their community have. Someone can come and propose a solution
+ Maybe a social media???????????????


* Colleges test
Suggested Schools: Science: California Institute of Technology, Clarkson University, Georgia Institute of Technology, Harvey Mudd College, Massachusetts Institute of Technology, New Mexico Institute of Mining and Technology, Rensselaer Polytechnic Institute, Texas Tech University Not science: UCLA, University of North Carolina, Penn State, or Michigan State

+ Arduino ATmega328



* LOA
+ Usar mais o quadro-negro como um retorno visual -> a ideia é parecer mais uma aula
+ Outro com aviãozinho (melhorar a volta do avião) e o like é top
+ Pode ser uma boa ideia ter o titulo embaixo da final da intro

* ACT
+ Questão bem geral: A gente aqui no marcohort estamos no processo de escrever histórias que vão levar a gente a escrever um personal statement. Eu também acredito que você deve ter escrito sobre alguns assuntos diferentes antes de ter chego ao tema principal da sua personal statement. O negócio é que eu meio que já estou vendo um caminho claro pra escrita do meu, mas ao ler seu personal statement eu também acabei me identificando com alguns pontos em específico, mesmo que sendo parte de mim, este não encaixaria nessa minha ideia. A pergunta é como tu conseguiu focar pra falar desse assunto?
+ Se o escritor também seja de exatas (Wangheley Soares Martins, Adeildo Viera Silva Neto - CS and physics!, João Vitor Boeachat Torrest Botelho - CS student!): Minha pergunta é simples: como você escreve tão bem? Porque eu tenho a impressão que o pessoal de exatas só sabe números, ou mexer com equipamentos, etc. Eu sempre tive um medo da lingua portuguesa me comer vivo, mas só depois que eu tinha 14 anos e comecei a aprender ingles que eu aprendi a gosta de linguas, e mesmo sendo apaixonado por física e ciência da computação, agora fazendo curso técnico em eletrotécnica, eu tenho que saber me comunicar: seja pra escrever um artigo científico ou pedir uma pizza. Pedir uma pizza ainda é meio dificil, mas eu já entendi a necessidade. Reformulando minha pergunta: como você escreve um texto sobre si considerando possíveis dificuldades linguísticas
+ Dica da Aisha: Listar coisas pra ir escrevendo - coisas que eu to fazendo e porque eu gosto de fazer isso. Colocar pontos de vc que a pessoa que está lendo entenda quem você é! É bom ambientar a galera - a pessoa lendo se sente como você (em um onibus lotado, você se sente limitado... posso fazer algo sobre isso? isso me levou a fazer tal coisa... o quanto vc luta pra se fazer ser ouvido em um espaço limitado, invisibilizado... ou então fazer o contraste desse lugar de injustiça com o que acontece no resto do seu dia). A redação do Boeachat fez ela pensar em como ela pode mostrar as montanhas que ela moveria pra estudar no ensino superior

* English Club
+ 07/05 (Saturday) at 9am - encontro com possíveis novos participantes
+ Encontros afternoon: 13h15-14h
+ Encontros morning: Por enquanto não teremos porque apenas a Estela está disponível
+ Estela ficou responsável pela arte (até 02/05), Natanael ficou responsável pela divulgação no Instagram, Luis ficou responsável pela divulgação no campus por meio dos cartazes da Estela
+ Próximo retorno do Let's Bora 09/05 at 13h15
+ Procurar informações sobre concurso de logos (concursos similares, cores, cabe em um formato circular, valor de prêmio)
+ Em maio, possivelmente divulgaremos nas salas os cursos CENID
+ Em junho, podemos planejar um encontro no parque das nações, possivelmente dia 11/06




* UNESCO Center for Peace
+ They will give a letter to apply for VISA - A visa of tourist is already enough
+ They conver absolutely everything, except for plan ticket to US and VISA
+ They have a facilitator for Brazil
+ Jorge Gonzales number: +5215568560371; Paloma: (+57) 3017787345; Shurabe: smercado@unescocenterforpeace.org

* Mobfog
** Materiais base de lançamento
+ 80cm de cano 20mm (para confecção de 3 canos de 20cm e 20 de 10cm)
+ 1 T de 20mm
+ 2 Cotovelos de 20mm
+ 2 caps de 20mm
+ 1 válvula de camara de bicicleta
+ 1 pedaço de camara de bicileta (pra ajudar na vedação)
+ 1 pedaço de mangueira de áquario (pra ajudar em caso de emergência)
+ 1 cola de PVC
+ 1 balão 6,5
+ 1 espaladrapo largo
+ 4 abraçadeiras de nylon (largua +- 3,6mm)
+ 1 abraçadeira 1cm diametro
+ 1 cano de esgoto 4cm diametro com 3cm de comprimento
** Materiais para o foguete
+ 2 Garrafa PET com o mesmo diâmetro ao longo da sua extensão (600mL - 2L)
  - A primeira garrafa terá as empenas, a segunda garrafa será removida o fundo e ficará em cima da primeira para que tenha mais aerodinâmica
+ Pasta Polionda para as empenas (3-4 empenas)
+ Parafuso de 1/4 de polegada para peso

+ Fanta 2L é 8,5
+ Suco Scheppes é 4,5

** Materiais - Base de lançamento opção 1
+ (15cm + 15cm + 15cm + 15cm + 40cm + 40cm + 25cm + 25cm + 26,5m 2,165m) 2,165m de cano PVC 25mm
+ 22 cm de cano PVC 20mm
+ 1 pedaço (5,5cm) de cano de 40mm
+ 2 Joelhos pra cano 25mm (Temos)
+ 5 Tês para cano 25mm
+ 1 cap para cano 25mm
+ 1 bucha de redução 25mm para 20mm (Temos)
+ 1 abraçadeira de metal
+ 1 manômetro de 150 PSI pra cima
+ 1 espaladrapo (Temos)
+ 8 enforca gato (4 pra válvula e o resto pra apertar) (Temos)
*** Additional
+ Registro esfera 25 mm soldável
+ 2 arruela de vedação 1/4
+ 1 Cap 25mm
+ 1 porca 1/4
+ 1 abraçadeira anel
+ 1 luva de redução 25 para 20mm
** Materiais - Foguete opção 2
** Materiais que não precisarão ser comprados
- serra
- veda rosca
- varetas de churrasco (obrigatórias)
- vaselina
- joelhos de pvc 25mm
- enforca gato
- esparadrapo
- estilete
- fita isolante
- balão (não sei o tamanho)
- garrafa pesa 39,4g
- 9,93cm
- altura 34cm


* ACT
** School Documents
+ Pedir para usar email institucional
+ Pedir para usar cabeçalho da escola ou logo
+ Pedir para assinarem os documentos (principalmente cartas de recomendação)
+ Todos os documentos devem ser traduzidas para inglês
+ Não tem problema os recomendadores não poderem escrever em inglês, o ACT poderá traduzi-los

** Transcripts
+ Históricos oficiais da escola (precisam ter suas notas do 9th grade a 12th)
+ Precisa ser assinado pelo school counseler/director

** School Profile
+ Helps admissions officers interpret the transcript for classes offered, rigor, grading policies and more
+ Também possui informação sobre a escola, administração, tipo de escola, número de estudantes graduando, curriculo, processo de admissão, atividades extracurriculares, etc
+ Que fique claro que o técnico integrado é diferente de escolas normais -- explicar como essas materias funcionam e que tipo de conteúdo que é ensinado
+ Devem ser traduzidos em inglês, mas não precisam ser assinados
+ Pergunta: Como funciona para quem mudou de escola no nono ano?

** Cartas de recomendação
+ Pedir para pessoas que te acompanharam de perto
+ Escolha seus recommenders sabiamente, mande um email perguntando se eles podem ser seus recommenders, explicar porque escolheu eles, explicar para eles que vc está aplicando para US Colleges, explicar sobre o EducationUS -- application tracker e que o meu mentor pode auxiliar ele na correção de algumas coisas, etc e qualquer dificuldade que você tiver
+ Escreva uma lista de coisas que possa ser destacada na carta -- refresque a memória deles!
+ Possible names: H-Fernanda, H-Flávio, S-Hilton, S-José Ricardo, S-Marco, S-Simone (1 humanities teacher, 1 stem teacher, 1 additional teacher, 1 counseler, 1 peer letter, 1 additional recommender (Iago))
+ As cartas devem contextualizar o candidato no ambiente escolar, por tanto seus recommenders devem compartilhar suas percepções sobre você seja dentro da sala de aula, fora dela ou em um projeto
+ Papel da carta do Counseler: Highlight any special program, how prominent are acitivites/impact in school, any family or personal context we should be aware of, context for student and entire graduating class - A carta do counseler não vai repetir o school profile, mas sim focará em você, no entanto é importante ter em mente o que foi dito no school profile
+ Papel da carta do Professor: Provide a brief introduction of the class for context, Outline academic performance, Highlight distinguishing performance, Be specific and use examples, evitem usar templates (geralmente levam a erros com pronomes) e compartilhar modelos de cartas inteiras.
+ O professor pode utilizar o "Bullet letter of recommendation"

** Homework
+ Contact your recommenders via e-mail (and other modes of communication)
+ Make a list of events that occurred in the recommender classroom or during a project
+ Explain them you are applying to U.S. Colleges. For now, it is necessary to write the letters of recommendation,



* ACT
** Extracurriculars, Honors & Add Info
+ ECAs don't need to have a social impact to be in the application
+ ECAs are simply activities that are not part of the usual school or college course
+ Through them, you showcase abilities you've developed in the past years -> ECAs also tell a lot about who you are
+ ECAs can be any activity that tells you apart
+ Hobbies: Roleplaying, Horticulture club
+ Music: Choir, Musical Interest club, Solo music, Singing lessons, Bands
+ Arts: Writing, annimation, paiting, choreography, puppetry, community theater club, drama club, photography, cartooning, poetry clubs, dance
+ Sports and Recreation: Soccer, Swimming, Ping pong, sports club, martial arts, cheerleading, gymnastics
+ Na hora de elencar as ECAs no common app, colocar as mais relevantes pois só tem 10 vagas...
+ Competitions: Spelling Contest, Poetry Contest, Math Olympiad, Science Olympiad, Language Contest, Essay Contest, Triathlon
+ Language: English clubs, Latin American Studies
+ Discussions and Political Interest: Model UN, Debate Club, Model Congress Club, Parlamento Jovem Brasileiro
+ Programs: improve english, learn/hone general skills, learn about different cultures, engage in special activities, campus visits, special classes, be equipped with leadership skills -> this also justifies a gap year
+ Volunteering: Mentoring, Local Charity, Animal Rescue, International Volunteer Programs, Online/remote volunteering
+ Paid-work interships
+ Research Projects, Extension Projects, Scientific Initiation
+ Some applications may accept portfolios - like MIT
+ Github and website are valid, but you may want to put them on additional information



* Ideas
** 1st and 2nd semester
+ Firstly, apply to the research programs. If you don't suceed, go straight to the Linux research (AND FIND A RESEARCHER FROM U.S. TO HELP YOU) <- Very important!
+ In paralel, continue the research with Hilton <- Very important!
+ Also, try your best with Cortez <- Very important!
** 2nd semester
+ Conduct the physics club experiments <- Very important!
+ Improve your rocket! <- Very important!
+ Improve EC! <- Very important!
+ Spend time with Linux (wisely)... <- Very important!
** Future
+ Raspberry pi...

* ACT
** Vocabulary
+ Aid Policy, Financial Aid Office, Need-Blind Policy, Need-Aware Policy, Need-Based Scholarships, Merit-Based Scholarships, Loans, Grants, Work-Study, Endowments, Tuition, Room & Board, Health Insurance, Other Fees, Cost of Attendance
*** Documents
+ Bank Statement, Individual Income Tax Return, Non-filer Tax Return Form, Annual Income Statement, Employer Letter, Pay checks
*** Searching
+ University Grants, Outside Scholarships, Merit Scholarships Programs

** Examples
*** Villanova University
+ Merit-Based Scholarships, Need-based grants, private education loans
+ They are Need-Aware
**** Merit-Based Scholarships
+ Presidential Scholarship
**** Documents
+ CSS Profile, Employer Letter, Bank Statement -> IDOC service and not the office of financial assistance
Merit-based:

Presidential Scholarship
valued at tuition, general fee, room, board and books for eight consecutive semesters)

Due to the high number of eligible applicants, not all students who meet the minimum criteria are offered scholarships

Need-based:

Although a student applying for aid may be academically admissible, not all students will be awarded financial aid due to the limited availability of funding. In addition, all students receiving funds are expected to contribute personally toward educational and personal expenses while attending Villanova University.

+ Imposto de Renda (Exercício 202 | Ano Calendário 2021) ou Declaração Anual de Rendimentos (Exercício 202 | Ano Calendário 2021) para dia 12/06

* Marco
+ 20D

* Clara
+ Dancing, books, music (zouk, latinas)
+ Eu não sei explicar, mas você tem um jeito que me atrai muito. É muito bizarro o quanto que é diferente e bom ao mesmo tempo

* English Club
** Registro Escrito
+ Talking about weeks...
+ "Keep calm" "Yesterday yesterday...", "Fracasso...", "Defame", "Bad words - cursing"

* LOA
+ Criador de conteúdo - 2 (inclui roteirista)
+ Editor de Vídeo - 1
+ Gerenciador de Mídias Sociais - 1

+ Desenvolvedor de Software - Verificar com Gustavo
+ Gestor de projetos e parcerias - Verificar com Iago
+ Gestor de interação - Verificar com Iago

* ATC
Group 1 https://mitadmissions.org/apply/firstyear/essays-activities-academics/ https://college.harvard.edu/guides/application-tips Group 2 https://www.amherst.edu/admission/apply/firstyear/writingsupplement https://www.bu.edu/admissions/tuition-aid/scholarships-financial-aid/first-year-merit/trustee/ Group 3 https://admission.stanford.edu/apply/freshman/apply.html https://blog.emoryadmission.com/2021/06/emory_saq2021/ Group 4 https://collegeadmissions.uchicago.edu/apply/uchicago-supplemental-essay-questions

** MIT
+ Consists of several short essays (5) --MIT não usa common application system

+ Describe the world you come from; for example, your family, clubs, school, community, city or town. How has that world shaped your dreams and aspirations? (250 words or fewer) --personal statement
+ Pick what field of study at MIT appeals to you the most right now, and tell us more about why this field of study appeals to you. (100 words or fewer) --Why major?
+ We know you lead a busy life, full of activities, many of which are required of you. Tell us about something you do simply for the pleasure of it. (200–250 words) --Hobbies
+ At MIT, we bring people together to better the lives of others. MIT students work to improve their communities in different ways, from tackling the world’s biggest challenges to being a good friend. Describe one way in which you have contributed to your community, whether in your family, the classroom, your neighborhood, etc. (200–250 words) --Social impact
+ Tell us about a significant challenge you’ve faced or something that didn’t go according to plan that you feel comfortable sharing. How did you manage the situation? (200-250 words) --personal statement

** Harvard
+ Harvard Questions
+ Writing Supplement (Pode mandar uma que já escreveu ou 10 examples)
Achamos confuso!

+ Unusual circumstances in your life --Context
+ Travel, living, or working experiences in your own or other communities
+ What you would want your future college roommate to know about you
+ An intellectual experience (course, project, book, discussion, paper, poetry, or research topic in engineering, mathematics, science or other modes of inquiry) that has meant the most to you
+ How you hope to use your college education
+ A list of books you have read during the past twelve months
+ The Harvard College Honor code declares that we “hold honesty as the foundation of our community.” As you consider entering this community that is committed to honesty, please reflect on a time when you or someone you observed had to make a choice about whether to act with integrity and honesty.
+ The mission of Harvard College is to educate our students to be citizens and citizen-leaders for society. What would you do to contribute to the lives of your classmates in advancing this mission?
+ Each year a substantial number of students admitted to Harvard defer their admission for one year or take time off during college. If you decided in the future to choose either option, what would you like to do?
+ Harvard has long recognized the importance of student body diversity of all kinds. We welcome you to write about distinctive aspects of your background, personal development or the intellectual interests you might bring to your Harvard classmates.

+ Not all short questions are supplemental essays, because some require you to be very objective
+ Analise o que tu já escreveu em outras partes da sua app pra nao ficar repetitivo
+ Alimony goes as supplementaldoc

* Marcohort
+ Stimate how much you improved students' grades DONE
+ Check with Ronaldinho the partipants + add how many projects in fecintec DONE
+ Briefly explain your condition today - commute to school + healt DONE
+ Search more about stanford classes DONE

* Marcohort
+ Literally explain metaphors
+ Follow up + Weekly things + Examples reading + Three short essays

* Marcohort 2
+ I don't get how music is applied into your life (how you feel), and give the example. He doesn't illustrate how it is important music in his context... <- Just Add things in another color, don't delete;
+ The music story will probably not become a personal statement, probably something for a supplemental essay
+ They cycling thing (the imposed limitation here... how?) and the autoimmune disease (focus on how you life were before and how you had to adjust, what you had to do differently like mentally, etc - how did you feel about it? - some limitations were imposed on me, how you feel about it?)

* Marcohort 3
+ "Since I was a child..." - Explain better the consequences of the disease (BE MORE IMPACTFUL) + Explain how you adjusted to your new life (Introduce Linux!!! Explain it is a different kind of freedom, and you get that, my disease allowed me to develop passion for tech - idea: having a change of scnerio, being excited differently)
+ In the story 3 second paragraph, maybe explain what freedom means for you now
+ Perguntar sobre o histórico parcial na escola

* Marcohort 4
+ In paragraph 4, be more clear/straitforward "To add up, I could not go outside yet. Sun was boiling eggs in the pavement, and Covid-19 was running rampant. So, I stay in my room, quiet and alone. I press a button, and a beast silently awakens. I keep staring at the screen, as if the shiny letters could hurt my reality even more. But all it does is ask who I am. As I prompt my user data, I am reminded how trustworthy the system I modified is, and I could also use, study, improve, and share it as I pleased." Try using less metaphors and ryme less, because you already used them in the beginning.
+ You have to be very clear that coding is very important
+ Have a final paragraph saying you can't cycle and it sucks (even though my freedom was removed), but this issue allowed me to discover something else, to explore more about this world.
+ I will need my parcial transcript + transcript

Luís Guilherme Miranda Spengler is currently a High School senior, taking electrotechnology vocational program at Instituto Federal do Mato Grosso do Sul. He is very engaged in the activities from his school, and takes great interest in activities involving research, volunteering and teaching.

During the pandemic, Luís was one of the most engaged students from his school, where he developed research, and coordinated at English Club. As a result of this, his team won Fecintec and were invited to participate in Mostra Nacional Itinerante das Feiras de Ciências. As a 1-year Quantum Computing student at the Qubit by Qubit program for high school students, he could learn more about an exciting career that is changing the world for the better, with its state-of-the-art innovations. He makes it his personal goal to somehow contribute to the Quantum Computing field.

Currently, he is preparing for the application process with the help of EducationUSA Application Tracker project. Meanwhile, he works on other projects he knows will also make an impact on his community, and hopes US colleges will notice his hard work and dedication.

* Marcohort 5
+ Think about the connections between the "As I recovered..." "My interest..." bringing people together - how? what did you participate in? in this virtual world or whatever
+ Also try introducing the community first
+ Also try coming back to cycling more like at the bottom of "As I recovered" paragraph
+ At the end, try modifying something as you see fit

* Marcohort 6
+ Everything, everwhere at once -> movie recommendation
+ There are lot of "software" words repetition software, freedom... (be mindful of the uses) -> refine it in terms of vocabulary
+ Get the 5th semester grades
+ Start the extracurricular activities and additional information docs
+ Search about universities (Duke, Dartmouth college, Rice university, Northwestern university, tarnford) search about the labs?

* Marcohort 7
+ Use maybe a parelel between programming and cycling, and recover something you said in the text -> create a new last paragraph and put it at the bottom
+ Add additional information in the additional information document -DONE
+ How many people have been impacted since the beginning of it? -DONE
+ Don't use "low-income" use underprevileged -DONE
+ Add the rocket -DONE
+ Duke University Press is not student led -DONE
+ What does IHouse do? -DONE
+ What does Bryan center -DONE
+ Talk more about the quantum center -DONE
+ Research about Duke research abroad universities -WHAT
+ Find more things about research - what do they do there?
+ Relate something to what you are doing to what they are doing -- for instance, the part from Jungsang Kim -DONE

* Marcohort
+ Yo Cientificx info about your interviews...
+ 9th grade honors go into additional information AND all the strikethrough
+ Research the other universities

* Marcohort (18/06)
+ We will go back on the ECAs later to check for things -- keep in mind I still have GTwins to write about
+ Create a google sheets template for college search -DONE
+ Create a google sheets | Application Tracker - DONE - In Progress
+ It is mandatory to get my father's documents -> Imposto de renda COMPLETO
+ Continue searching for next week
+ Add the drive folder for each teacher and the document -> Contact them
+ Next week we will start organizing for me to start writing the supplemental essays
+ Visit the College Essay Guy links on google classroom
+ Organize individual folders for each university (write the full university name)
+ Create google docs and write down the prompts-1 prompt per page (use page breaks)

* Marcohort
+ Specific stuff in 1st and 2nd paragrahps -- good, but you need to shorten it
+ The last paragraph is too general -- delete it
+ Introduce other things you could do at Duke -- asides from academics -- try to find connections
+ Homework: Focus on rewriting the why duke essay + writing the duke background essay + finish the research + add universities + try to do a why essay or extracurricular essay

* ATC
+ Why this community essay
+ Why this major essay
+ Why this college essay

+ How would you approach this prompt?
Basicamente tu tem que refletir no seu futuro e imaginar indo nessa faculdade pra conseguir isso. Dá pra pensar no why college essays em como você aprova a faculdade em te ajudar no que tu quer fazer no futuro, não pensa nisso como a faculdade te avaliando, mas em você avaliando ela, porque aí dá pra criar um fit muito bom

+ Where could you find the necessary information?
- Through college searching, throught self-thinking, assistam videos de campus, entendam a geografia de onde fica a faculdade -- só pra dar você realmente se imaginar indo lá

* Reuniao GEDUC + LOA
+ Parceria com pitagóricos para preparação de seletivas + indicar participação no discord? - FALAR COM ELES
+ Brainstorming com cargos específicos no servidor - FAZER ISSO
+ Breakouts com perguntas especificas para as seletivas de astronomia -- o que te levou a ficar interessado em astronomia -- assim aumentamos o engagamento do pessoal. Vai ter kahoot?
+ Fazer brainstorming de canais do youtube que a gente pode fazer divulgação do servidor - FAZER ISSO
+ Canal de memes (off-topic) + sugestão (server info) + desafios semanais ()



* EC
+ Primeira logo em 2017, segunda em 2020 -> está em memories

* ACT - SUPER MEETING
** General
+ João says 5 classes is recommended for a double major and he has a very flexible routine -- Is it really that flexible?
+ Diego +5516988113432 , coelhorodriguesdiego@gmail.com
** DUKE -- João Vitor Boechat -- Computer Science;
vitorboechatbotelho@gmail.com
whatsapp: +19843779581
** NORTHWESTERN -- Davi Maciel -- Computer Science; Kaio Kumagai -- Biomedical Engineering
*** Kaio
+ Quarter system -> Kaio describes it as accelerated
+ Kaio  +1 847 907 1146, kaiokumagai2025@u.northwestern.edu
*** Davi
+ 1st quarter -> He was trying to explore a lot of things... It seems like his biggest task was the even nights to get points for the dorm
+ 2nd quarter ->
+ 3rd quarter ->
+ He says there is a lab for CS students -- Is it like an informatics lab?
+ He says the campus is very pretty and nice to walk

* Dartmouth
+ You'll learn how to be outdoors (nice hehe)
+ All research is funded at Dartmouth and it is really easy to get into a research opportunity
+ You are housed between 6 houses communities on. You are only required to live on campus in the freshman year, but most students do all 4 years
+ Dartmouth accepts peer recommendation

* Tufts
+ Tufts doesn't have a core curriculum, but it has distribution requirements
+ Tufts is having a direct line to Boston ready by fall 2022
+ Q: Can you tell me a bit about the free and open source software community at Tufts? I know there is the Tufts GNU/Linux users group and I even joined their Discord group this week. I also heard about JumboCode that helps non-profit orgs in desigining new free tech.
+ Host's email: theresa.quinto@tufts.edu
+ Moizes H. S. Almeida -> CS + ECON at Tufts
+ Tufts has like 6 campus: 4 in Boston, One area in Boston, called Boston + Davis Square, One in France where they offer a 6-week summer program
+ Tufts students are limitless, rarely someone is going to tell you can't do this and this at the same time
+ Financial Aid docs CSS Profile, Tax Documents via IDOC

* Northwestern
+ It is very easy to take classes between the 6 schools of theirs
* Duke
+ Aldeido Viera Silva Neto -> CS + Physics at Duke

* Video
+ Title: Ep 1. Learning in 6 months: 3 Olympiad medals, 1500+ SAT
Hello guys, welcome to this channel's first video. Let me tell you right away that I don't know how this is going to go at all. But I know I have chances on succeding and if I did, I would want to share this with you. That's what the channel is about, documented learning. I wish I had done that when I was learning English for the time that actually worked, because as time passess you start forgeting how you learned that, all that was required of you to do it. And for all the people that asked my how they could learn English, well, you are not going to learn English out of this video, but if it succeds you will see me taking on challenges of language learning as well as other stuff, so stay tuned.
 + Why am I doing this? Let's start by what I am doing. I am attempting to get Gold medal on two scientific olympiads, and a math one, as well as getting a 1500+ SAT as an international student. My main reason for it is to increase my college competitiveness. For those of you who don't know, I am a senior at High School, and brazilian. Our high school is devided in three years, 9th grade counts only for middle school here btw. So, I have some cool extracurriculars, things I am actually proud of. My grades are also really good, but there is a specific 6 months period, the beginning of my Junior year where I didn't go to class. It was in the middle of Covid-19 pandemic, and I was to say, depressed. I failed two school subjects, and I dropped what was to be a 9.4/10 score, for a 8.7/10. Everyday I wake up I feel like I screw up, this challenge will also be one thing to help me with this feeling.

* Marcohort
+ Get everything together in why duke, if it is the same subject.
+ Show more concrete examples you looked for the stuff at Duke, similar to the mentions of Brown Lab.
+ At third paragraph... "Besides academics, it will be great to hang out..."
+ The last part "hang out at Duke's.." try to find something unique, odd, strange that few people would say it.
+ What if in the first paragraph you connected to things you are doing in Brazil about these subjects and finish with saying you can also do that at Duke. The second paragraph you focus on specifics on how they accomplish that and help you do those stuff.
+ In the community essay, focus on something more specific.
+ You can try music, but introduce the whole family in a paragraph. How they play different instruments. The second paragraph can be talking about how they influeced you, how they made you use music in many contexts.
+ Homework: Focus on Duke and the scholarship essays. You can work on some college search in the spare time.

* Vinicus -> Columbia
+ é bom explorar aulas de humanas em columbia.
+ tem core curriculum
+ no competition for research there

* AdAstra
+ Pedir para a Paola entrar em contato com os canais de divulgação astronomica
+ Mudança do objetivo de contato com pitagóricos: vamos contribuir com lista de exercícios e simulados
+ Adicionar os cargos de moderador do discord do fórum Ad Astra no recrutamento da LOA?
+ Sala de notícias relacionados a olimpiadas no server
+ Prática com o pessoal sobre o James Webb, como isso pode cair nas olimpiadas, etc.
+ Próxima reunião Domingo ás 13h

* Marcohort
+ Put the verbs in the future to look better (done)
+ The ending may be missing something
+ Add a PS easter egg when you talk about cyclng. (done)

+ Double check some of the universities you added for their requirements (done)

+ Go to Rice university supplemental essays (done)

+ At Essay 1 you should be very specific (paragraph 2, 3). Meaning, fulfilling. Use these words as you explain why you would take a break. You can also mention what makes you happy today, what you know today that you can do in the future.

+ At Essay 2 there is a very big sentence at paragraph 1. Focus a bit more on the importance of the issue "We can address these issues more effectively". Advancing quantum computing in Brazil is something you look forward to. At third paragraph, try doing the Brazil thing + summarizing everything you learned in the course in once sentence. "It is no wonder that things are like that, because something lacks." "It is no accident that QC"

* Marcohort
+ Why Duke essay first paragraph... (done)
+ Why Duke essay be more specific about the professor (done)
+ How you see yourself achieving your goals in the future, future areas (why major rice essay)
+ Sunday at 7pm
+ Try to bring new light on the community essay (focus on the linux club question on community essay) -- bring something more personal

* Loa + geduc
+ Reunião de integração 06/08 às 19h
+ Marcar reunião com joão victor e mandar lá no grupo
+ Publicar o processo seletivo da loa no canal do telegram

* Marcohort
+ Ad Astra movie
+ Finishing the rice, duke, and open philanthropy essay

* Common-Appy
** Dúvidas
+ High School name é pra incluir em português e com acento? O que é o CEEB code? Should IF be classified as Charter School? (R: em português)
+ "If you have attended any secondary/high schools not listed in the previous section, please indicate the number of schools." -> Should I add my 9th grade school?
+ Please provide details about why you left each of the above secondary/high schools.
+ "Please list all courses you are taking this academic year. If you are not currently enrolled, please list courses from your most recent academic year.
How many courses would you like to report?" -> 28. Chemestry 4, Biology 4, History (3,4), Mathematics (5,6,3), Physical Education 5, Philosophy 3, Sociology 3, Statistics (8). Control and Instrumentation, Microcontroled and Digital Systems, Reneable Energy and Environment, Inovation and Entreperneuship, Generation, Transmission and Energy Distrubuition, Personal and Professional Orientation (15)
+ "Honors" comes all our honors now?
+ Senior Secondary Leaving Examinations. Should I put yes?

* ATC
+ Use the same email through the app process
+ 23 de setemebro bithrday do marco. Rua Manoel Correia da Costa Neto, 1. Tabuleiro do Martins. Maceió, Alagoas.
+ Graduating Class size -> coloca o mesmo que todos (aplicantes e counselers)

* Marcohort
+ Rewrite some expressions
+ Finish all the essays (duke, rice, philanthropy)

+ Mencionar que um plano de trabalho

+ USBEmato grosso do sul
+ instagram da embaixada

* Rec letters
+ CANNOT identify a college as recepient -> all colleges will receive the app on common app
+ Send them an e-mail asking them to be your recommenders. Explain them why you chose them. Explain them that you are applying to U.S.
+ Pedir para usar email institucional
+ Pedir para usar cabeçalho da escola ou logo
+ Pedir para assinarem os documentos (principalmente cartas de recomendação)
+ Todos os documentos devem ser traduzidas para inglês
+ Não tem problema os recomendadores não poderem escrever em inglês, o ACT poderá traduzi-los
+ Pedir para pessoas que te acompanharam de perto
+ Escolha seus recommenders sabiamente, mande um email perguntando se eles podem ser seus recommenders, explicar porque escolheu eles, explicar para eles que vc está aplicando para US Colleges, explicar sobre o EducationUS -- application tracker e que o meu mentor pode auxiliar ele na correção de algumas coisas, etc e qualquer dificuldade que você tiver
+ Escreva uma lista de coisas que possa ser destacada na carta -- refresque a memória deles!
+ Possible names: H-Fernanda, H-Flávio, S-Hilton, S-José Ricardo, S-Marco, S-Simone (1 humanities teacher, 1 stem teacher, 1 additional teacher, 1 counseler, 1 peer letter, 1 additional recommender (Iago)) -> Fernanda (humanities teacher), Ronaldim (STEM teacher), Marco (additional teacher), Simone (additional teacher), Flávio (counseler letter), Raquel (peer letter)

+ As cartas devem contextualizar o candidato no ambiente escolar, por tanto seus recommenders devem compartilhar suas percepções sobre você seja dentro da sala de aula, fora dela ou em um projeto
+ Papel da carta do Counseler: Highlight any special program, how prominent are acitivites/impact in school, any family or personal context we should be aware of, context for student and entire graduating class - A carta do counseler não vai repetir o school profile, mas sim focará em você, no entanto é importante ter em mente o que foi dito no school profile
+ Papel da carta do Professor: Provide a brief introduction of the class for context, Outline academic performance, Highlight distinguishing performance, Be specific and use examples, evitem usar templates (geralmente levam a erros com pronomes) e compartilhar modelos de cartas inteiras.
+ O professor pode utilizar o "Bullet letter of recommendation"
** Chosen names
+ OBG 1: Fernanda (humanities teacher)
+ OBG 2/OPT1: Ronaldim (STEM teacher)
+ OPT1/OPT2: Marco (additional teacher)
+ OPT2/OPT3: Simone (additional teacher)
+ MANDATORY: Flávio (counseler letter)
+ OPTIONAL: Raquel (peer letter)
** By college:
+ Boston University -> OBG1, OPT1, OPT2 or OPTIONAL
+ Brown University -> OBG1, OBG2, OPT1, OPT2, OPTIONAL
+ Columbia University -> OBG1, OBG2, OPT1 or OPT2
+ Cornell University -> OBG1, OBG2, OPT1, OPT2, OPTIONAL
+ Dartmouth University -> OBG1, OBG2, OPT1, OPT2 or OPTIONAL
+ Duke University -> OBG1, OBG2, OPT1, OPT2 or OPTIONAL
+ Emory University -> OBG1, OBG2, OPT1, OPT2, OPTIONAL
+ Haveford College -> OBG1, OBG2, OPT1, OPT2, OPTIONAL
+ Northwestern University -> OBG1, OPT1, OPT2, OPT3, OPTIONAL
+ Oberlin College of Arts and Sciences -> OBG1, OBG2, OPT1, OPT2, OPTIONAL
+ Rice University -> OBG1, OBG2, OPT1
+ Stanford University -> OBG1, OBG2, OPT1 or OPTIONAL
+ Swarthmore College -> OBG1, OBG2, OPT1, OPT2, OPTIONAL
+ Tufts University -> OBG1, OPT1, OPT2
+ University of Chicago -> OBG1, OBG2, OPT1, OPT2, OPTIONAL
+ University of Notre Dame -> OBG1, OPT1 or OPTIONAL
+ University of Pennsylvania -> OBG1, OPT1, OPT2, OPT3
+ Washington and Lee University -> OBG1, OBG2, OPT1, OPT2
+ Williams College -> OBG1, OBG2, OPT1, OPT2, OPTIONAL
+ Yale University -> OBG1, OBG2

* Talk with Nobel
+ The greatest scientists are fooling around scientists
+ Curiosity-driven reasearch is awesome
+ Challenge today: Implement quantum erro-correciton that is more effective
+ The more diversity you have in your team, the more likely you are to make progress
* Olympiads
** 2019 (9th grade)
5h/w for 32 weeks
** May
+ 07/05 -> 5h (OBA + MOBFOG)
+ 08/05 -> 5h40min (OBA + MOBFOG)
+ 09/05 -> 4h50min (OBA + MOBFOG)
+ 10/05 -> 1h30min (OBA + MOBFOG)
+ 11/05 -> 30min (OBA + MOBFOG)
+ 12/05 -> 3h (OBA + MOBFOG)
+ 13/05 -> 5h30min (OBA + MOBFOG)
+ 14/05 -> 9h30min (OBA + MOBFOG)
+ 15/05 -> 9h (OBA + MOBFOG)
+ 16/05 -> 6h (OBA + MOBFOG)
+ 17/05 -> 5h (OBA + MOBFOG)
+ 18/05 -> 30min (OBA + MOBFOG)
+ 19/05 -> 3h (OBA + MOBFOG)
+ HOURS: 59h | DAYS: 13 days | H/D: 4h32min
** June
+ 03/06 -> 3h (OBI)
+ 04/06 -> 3h (OBI)
+ 05/06 -> 2h (OBI) + 1h (OBMEP)
+ HOURS: 8h | DAYS: 3 days | H/D: 2h40min
** August
+ Multiply by 0,5h each block + level 1 exercise (OBF)
+ 40h (OBF)
** September + OCTOBER
+ MOBFOG? (37h + 200h)
+ ONC? 4h
+ OBMEP? 4h

  + Reported on common app: other olympiads (75h)

* Raquel
+ She acts quick when solving problems
+ She believes in education -> Demonstrates that when deciding the future leaders of our country, in her social projects

+ Personality: Present-oriented, concerned about problem at hand, insightful, shows sympathy, warmth, concern and support for others, enthusiastic
+ Chracter
+ Interests outside of school: impact in education
+ Attitude: acting as a leader, pushing others to their best,
+ Unique traits
+ Interaction with others

+ Leadership
+ Motivation
+ Trustworthiness
+ Dependability

+ What makes Raquel stand out?
+ What qualities in them impress you?
+ What have the two of you bonded over?
+ What successes or adversities have you shared?

+ Introduction
+ Body
+ Conclusion

* Marcohort
+ Ask him if he wants to pass the credentials to the common app acc
+ Because it takes time, he can help, he has the answers for my app because of the form.
+ Find  one thing you can say from everything you said and finish with it.
+ In rice essay, say that collaborating with people is important and that you want to continue working on that - with the goal of whatever it is
+ Interviews: see what universities are able to be scheduled -> then schedule those, then prioritize the college search!
+ Amanda: She can start talking with the teachers, but they will only be able to sign it next week.
+ Amanda 2: The counselers (less questions) and the teachers answer questions about the students when submitting the letters. The forms is for the advisor to be checking if all answers are accordingly, but it also helps with the support of the language. She must also tell them the evaluation must be accurate. If they think her evaluation is to be placed in the top of the class, she should tell them to be very realistic
+ You go to any university
+ Write your full name (remove the full name thing), remove the address for the english version of it. Change the Goals to Profile (how you define yourself). Move formação academica e complementar in the beggining. You also put your GPA in the brazilian system. Honors and accomplishements - rename that. Have a section for Extracurriculars (explained), and uise the ones in your app. Use your general abilities in the profile section. Technical abilities is good. Create a linkedi as well. Remove the bulleted things in put them in line
+ Interviews: Rice doesn't need to apply,

* Lecture
+ O sol é tão quente que os atomos que se formam estão em um estado meio quebrado, pois elétrons e nucleo estão separados -> um estado conhecido como plasma
+ Esse plasma sofre alterações pelo próprio campo magnético do sol, que é gerado pelo movimento dessas partículas
+ As vezes, estranhos padrões de campo magnético surgem na superfície do sol que carregam grandes quantidades de energia
+ Quando esse padrão estranho quebra, o sol pode liberar algumas coisas no sistema solar
+ Um delas é o flare solar, que nada mais é que radiação de alta energia
+ Flare solares viajam na velocidade da luz, mas elas vão carregando protons do vento solar, formando uma tempestade solar de protons
+ Outra coisa que pode ser liberado é massa coronal, o próprio plasma do sol é catapultado a velocidades de até 9 milhões de km/h
+ Quando essa ejeção de massa coronal atinge a terra, nada acontece a nós. Mas no espaço próximo, satelites, comunicações por rádio são prejudicados e astronautas
+ A própria atmosfera proteje a gente dos raio-x, absorvendo os antes da superficie
+ No espaço, CMEs são desviados pelo campo magnético da terra e acabam caindo nos polos

* Test foguete
+ 5.5L de vinagre + 500g de bicarbonato
+ Lançando em proporção 20 para 1 -> 800 mL de vinagre dá 40g de bicarbonato -> Vamos usar 1L e 40g -> 50-60 psi
+ Testando em 500 ml para 25g de bicarbonato 2x (?psi)
+ Testando em 1,5L para 75 de bicarbonato


* Marcohort
+ Should I add my scholarships from school in the work part? (NO)
+ What if I only include my mother's sorts of income in the parents part, and leave the amount received by my father (which is the non-custodial parent) be reported by him when he receives the email from college board? -> Only mother's!!!
+ Create an email for your father to edit CSS Profile, and you fill it out
+ Put the DET score in the languages session
+ Recommenders, make them sign (Fernanda, Marco, Flávio) -> Ask for access, and Marco will be responsible to fill it out so that they won't be worried about me. Flávio doesn't need to fill mine, my mentor will take care of everything, just pass the credentials
+ Remind Marco to reschedule for Friday or Saturday (prob sat.)

+ More specific on the academic experience thing -> choose something that lasted a considerable time, like the rocket thing -> foca na quesatão do rocket desde quando vc começou até a premiação -> ganhamos, mas foi uma long journey -> it was the best academic experience beacuse you put everything you learned  to practice, and it reassured to you it is the path you want to follow in stem
+ Expand something on the why essayy

* Pedro
+ como você vê a LOA no sentido de concretizar sua meta de falar sobre a sua área de atuação (astrofísica)? seria interessante você participar do projeto criando vídeos pra LOA apresentando sua experiência, especialmente pela sua área de atuação ser astrofísica -> Continuar no meio de divulgação de astronomia
+ Corrigido: como você vê a LOA no sentido de concretizar sua meta de falar sobre astrofísica?
+ Vendo seu perfil, deu a impressão que você gosta de pensar sobre a conexão da ciência com a sociedade, de uma forma, isso resume o que a gente tem em mente aqui na LOA. Tem alguma coisa a comentar sobre isso?
+ Parece gostar da área da educação, já tem materiais elaborados por ele (big olimpicos brasil)


* Paula
+ Em quais tipos de projetos utilizou LaTeX?
+ Você acha que consegue aplicar sua experiência obtida na escrita dos artigos de opnião na criação de roteiros de vídeos para o canal da LOA?
+ Observativa, organizada

* Francine
+ Mesmo a gente não aparecendo na reunião,
+ Não sabe muito sobre as olimpiadas, mas tem interesse em participar - o que fez voce gostar de astronomia?
+ Timida e introvertida - as caracteristicas iniciais de um editor de video
+ Com o after effects, acha que consegue fazer uma intro nova pro canal? -> capcut, ... motion,
+ Quanto tempo você normalmente leve no processo de edição, fazer os cortes, transições, aplicar efeito, renderizar o vídeo? -> 1h30min
+ Você faz alguma correção no audio se for necessário, tipo usando o audacity ->
+ Ela topou intro nova, ela aprende muito olhando, gostaria de textos no video
+ Voce não deixou muito claro no formulário, mas a gente viu seu perfil astrofrancine no instagram e achou incrível - pergunta sobre isso
+ Criou o insta pra ajudar os amigos

* Maiara
+ 4 medalhas de ouro
+ Cria questões para amigos
+ Qual parte principal na criação de conteúdo você mais gostaria de participar? (escrevendo artigos, roteiros pros videos, materiais de estudo (lista de ex, provas, etc.)) -> Artigos, com o foco de redes socias para engagamento, parceria com um outro projeto para incentivo dos alunos partindo da empatia operacional (eu sei como foi pra mim). Redes sociais. Ótima redatora de artigos.
+ Boa no canva
+ Que série está? 1 ano

* Jandir
+ Faz geografia
+ Conta um pouco da sua história (depois de eu contar a minha lol)
+ Conta um pouco o que vc faz nas suas páginas especializadas em astronomia -> ADM da página sociedade astronomica
+ E considerando isso, como acha que poderia contribuir com a LOA? (Pro cargo de gerenciador de mídias -> Ajudar a criar conteúdo para o instagram, checar as mensagens, colaborar com o gerenciamento da página)


* About
+ Felipe: Estudante egresso do Instituto Federal de Educação, Ciência e Tecnologia de Mato Grosso do Sul - IFMS no curso de nível médio integrado em Eletrotécnica. Alumni da Embaixada dos Estados Unidos no Brasil e da Casa Thomas Jefferson em Brasília pelos programas English Immersion USA Program (EIP) 2019 e Jovens Embaixadores 2020. Envolvido em diversos projetos de pesquisa aplicada e de extensão, assim como em diversos trabalhos voluntários, sejam esses ligados ou não à Instituição Federal de ensino IFMS. Aluno egresso do Centro Estadual de Atendimento Multidisciplinar para Altas Habilidades/Superdotação - CEAM/AHS com áreas de destaque em "Acadêmico" e "Musica". Monitor voluntário de Inglês e representante das Relações Estudantis e Institucionais do Grêmio 2019 no Campus Campo Grande do IFMS. Mentor voluntário de inglês do Projeto Globalizando pelo ciclo de 2020.1. Coordenador Educacional do Projeto Globalizando pelos ciclos 2020.2. e 2021.1
+ Marco: I have been teaching English for the past 9 years in primary school. In 2018 I started working at Centro Universitário Cesmac (2018-2021) to teach English in the Faculty of Medicine. In the same year, I was given the opportunity to work as an EducationUSA Adviser and coordinate the EducationUSA Center in Maceió, AL, Brazil.\Since then, International Education has become a topic of interest. Therefore, in 2019, I was also given the chance to be a part of the Opportunity Funds Program (Undergraduate) Coordination in Brazil, which focuses on supporting academically competitive students that cannot afford the application process to U.S. Higher Education Institutions.\I have also created the Application Tracker Cohort Group, in 2021, to support 11 underserved students navigate in the application process to U.S. H.E.I. The new 2022 cohort has 20 brilliant students.\Currently, I remotely work at ABA Global Education as an EducationUSA Adviser and implementing mentorship programs to underserved students, such as My Application Prep (MAP) and the Global Education Prep (GEPrep).\Thus, I have successfully supported many brilliant students in the application process to US H.E.I., which is what brings me joy as I have to be in constant contact with them, learning about their journey, and helping them achieve the best application they could have ever sent.
+ Joao: I like to see creativity in just about everything, from music and movies to ways how to solve a mathematical problem. For me, creating new and innovative "things" is extremely fascinating, since humanity has a great history and thousands of minds that have existed and still exist. Therefore, creating something original becomes much more amazing than people usually think about it.\An incoming first-year at the Trinity College of Arts and Sciences @ Duke University intending to major in Computer Science + Linguistics IDM program. Current interested in Information Technology, Linguistics, Foreign languages, and Racial Issues.\Being the first-ever quilombola to study in the USA at the undergraduate level with a full-ride scholarship, I want to unite my interests to help people who are part of socio-historically oppressed groups. So that education will change their lives in the same way it changed mine.\Experienced in Information Technology services, Classical and Quantum Programming, Web Development, Web Desing, Public Speaking, Research on Linguistics and Internationalization, and Racial Equality Initiatives.

* Mock Interviews
** KILL Introduction
CLOSED: [2022-11-06 Sun 15:27]
1. Tell me a bit about yourself?
a. Name
b. Where you’re from
c. High school
d. Intended major
e. Two or three activities
f. Bring up topics and ideas you want to talk about for the rest of the interview
+ I am Luis, I am from Brazil and I study at the Federal Institute of Mato Grosso do Sul, and I intend to double major in Physics and Computer Science. I like to watch fantasy, sci-fi, and comedy tv shows and movies in my free time, as well as listen to several types of music, like rock, metal, pop, and classic music.
+ COMMENT: Hey, Luis! In the introduction, you should give an overall about many interests you have! It was a very short intro. Use at least 1 minute, and pace down your response. Do not need to rush it! Tell about your school as well... that you are in a integrated technical program in high school in IFMS... it would surely prompt a question about school! Also, which part of Brazil? You can talk a bit morr about the climate etc.
+ I am Luis, I am from Brazil, living in Campo Grande, also known as the brunette city. To me, that nickname sounds really funny in English, but regardless it was earned because of the dirt's color, which is a black-purple color. We are also famous for our caphybaras, a similar story United States' squirrels, because even though capybaras are not such small animals, you can find them very easily here. Besides that, I study at the Federal Institute of Mato Grosso do Sul, studing electrotechnics integrated to high school, meaning I have a lot of subjects involving electricty. And connecting this previous experience I had with electricty, I intend to double major in Physics and Computer Science. I guess on my free time, besides talking to friends, and having some meaninful conversations, I like to watch fantasy, sci-fi, and comedy tv shows and movies.

** KILL Why the US
CLOSED: [2022-11-06 Sun 15:28]
2. Why do you want to go to college in America?
a. Best academic and professional opportunities
b. Brazilian education is too narrow and test oriented
c. Personal experiences in America
d. Know friends or family in America
+ I know in the US I can have better academic and professional opportunities. It is different from pursuing a whole life of Brazilian education, since here we have such a narrow and test oriented academic experience. That was always a deal breaker to me, and considering I've always like physics and computer stuff, the big opportunities of learning and working in these fields are in the US.
+ COMMENT: You should explore more in-depth examples. For instance, which big opportunities are you talking about? It is the same thing as essays = ALWAYS BE SPECIFIC and detail your answer. 1 minute would suffice.

+ I know in the US I can have better academic and professional opportunities. It is different from pursuing a whole life of Brazilian education, since here we have such a narrow and test oriented academic experience. That was always a deal breaker to me, and considering I've always like physics and computer stuff, the big opportunities of learning and working in these fields are in the US. Rocket launching companies, tech startups, companies in quantum industry, even the government participates in research and scientific development. I think that is what is inspiring about the US. Universities also tend to have the best researchers of the world, Duke is included of course, and to get started in some STEM area, there is nothing better than to being guided by people who are participating in the change, those people contributing to make the field grow, have more visibility. They also get waaaay more funding than on Brazil, and if you don't want to spend half of your time on a thesis, thinking how to get more money, or what to do with the little you have, the US is doing better than Brazil on than. And I can see myself going to college in the US, doing well in my studies and with the support I have received, I will be achieving pretty amazing things.
** KILL Major&Carrer
CLOSED: [2022-11-06 Sun 15:28]
a. Demonstrate passion

b. Demonstrate knowledge

c. Be as specific as possible about what areas of the major you’re interested in
i. Don’t just say “history,” say “late-19th century American economic history”

d. Connect to career goals

e. Connect to past experiences, especially activities

What are your future career plans?
a. Be as specific as possible

b. If you don’t know, explain why you don’t know

c. Name specific dream companies
i. For instance, if you’re into tech, say Apple, Space-X, etc.
+ I would like to conduct research on the hardware part of quantum computers, either improving error correction in photonic quantum computers, or in the betterment of trapped ions quantum computers. To meet those goals, I could either join the private industry in companies like Xanadu, and IonQ, or continue conducting research in a university after my PhD

+ This is a BIG question. Why this major AT DUKE? You gotta give more context on HOW you reached the conclusion that you wanted to follow this path... mention school, what you do there, mention your early exp inthe field, if there is a person who intro you to this field, than tal kabout the major + what you expect to do in the future... interlock your extracurriculars (quickly) to the feeling of knowing this is what you wanna follow.

+ The interest for my majors were developing over time. When I was little I remember the periodic table really fascinated me. I would draw different layout versions of it, and my father got to explain me how the atom worked in a simple way. And of course I grew up liking it, and when I was presented with a computer, just because I am curious, I would try to tweak most of the software settings, of course, in a simple way in Windows. I think my most proud achievment was downloading around 10 browsers in my father's computer. As I a grew older, I started looking at the world and seeing what humanity was able to accomplish with physics knowledge, and with some many good examples of that, I can think of the computer as really an interesting tool, thinking more in hardware terms. Then, I went back to what I had done as a child, tweak software settings, but I changed it a little bit to changing operating systems, and started learning Linux. As of now, I absolutely love Linux, I am running arch linux on my laptop with everything that I could now personalized. What I love about Linux is the ability to have the system I want, just by the power of will, and the freedom that comes with building a tool to achieve your goals. Turning this concept to science, I see it as a way to power humanity, and give it more freedom. Majoring in Physics and Computer Science, or even Electrical and Computer Engineering at Duke, which is a major I find very appealing, is a chance for me to use passions of mine to maybe change the way some things are being used or the way people perceive things from science, and that means continuing the mission I had with some projects I've been, like managing a YouTube channel for people interested in Astronomy Olympiads, managing and lecturing at the Physics Club in my school, continue working in a rocket launching team, learn more about quantum computing, and also free and open source software. So, overall, the projects I've been in the past gave me a reassuring feeling that I want to keep on the STEM road, and that reflects directly into the majors I chose, and my decision in applying early to Duke.

** KILL ECA
CLOSED: [2022-11-06 Sun 16:15]
4. What extra-curricular activity are you most proud of?
a. Pick your best/most impressive activity, likely research or internship
b. Demonstrate passion
c. If possible, connect to future activities or academics in college
+ English Club is the extra curricular activity I am most proud of, because I developed a sense of myself and others, coming out with softskills like communication, time management, and resourcefulness, which I applied to all of my other extracurricular activities and projects reported on my application. We also did research, and although lingustics is not a field of research I will be following much in the future, I learned the process of doing scientific research, and presenting it in science fairs, learning how to take advice from evaluators and improving the research. Although it may not seem like it, this helped me take on other research ventures in Physics and Computing, even writing research papers in English was made easier, helping me a lot when submitting my research proposal to CERN. And lastly, the science fairs we presented awarded us some prizes, like a 3.6k brazilian reais grant, and best high school level project award, which I am proud of having as part of the development of the English club project.
+ That is a great example of a good answer! Great answer, really!! You contextualized it, and explained how this ECA helped you in other areas!!!

However, I want you to talk more about the feeling of belonging there! it is important to also focus on the humane side of things -- the interconnections you created etc.

+ English Club is the extra curricular activity I am most proud of, because I developed a sense of myself and others, coming out with softskills like communication, time management, and resourcefulness, which I applied to all of my other extracurricular activities and projects reported on my application. We also did research, and although lingustics is not a field of research I will be following much in the future, I learned the process of doing scientific research, and presenting it in science fairs, learning how to take advice from evaluators and improving the research. Although it may not seem like it, this helped me take on other research ventures in Physics and Computing, even writing research papers in English was made easier, helping me a lot when submitting my research proposal to CERN. And lastly, the science fairs we presented awarded us some prizes, like a 3.6k brazilian reais grant, and best high school level project award, which I am proud of having as part of the development of the English club project. Since those prizes took us some time to achieve, it was nice seeing that great things go through a process of development, usually taking way more than a day to be achieved. In 3 years in English Club, we got to know very weel the people we were working with, amazing people really. Joao Haufes, ex-member is in Duke 2026 class, Felipe Pavanelli is in 2027 class in Dartmouth. My colleagues, friends, now, that are graduating this year have recently been selected to HMUN at Harvard, and other pretty interesting achievments. I learned a lot from the humane side of things with these people, considering people from STEM usually struggle with that, EC was the perfect project for me to solve this problem too. The activities we engeaged with the school community, put us closer, even personally with them. It is nice going to a big school everyday and having a look around, and seeing you more or less know more than half the people there because of your actions towards the school community.
** KILL Favorite Person
CLOSED: [2022-11-06 Sun 15:28]
Who is your favorite (person in your major/field)?
a. For instance, who is your favorite biologist? Who is your favorite historical figure? Etc.
b. Pick someone unique
c. Describe the individual and his accomplishments
d. Connect the individual to yourself
+ In Physics I find many unique personalities, but one that always calls my attention in Richard Feynman. The way he could leave great contributions to science as a theoretical physicist and education as a science communicator is incredible. He is a nobel prize winner in physics for his contributions with the theory of quantum electrodynamics. He is the father of the field of quantum computing, the area I intend to contribute. But above all, he popularized physics through his books, and lectures. His way of explaining can catch the attention of any child in the audience. When I want to explain something with the greatest level of understanding, I always think of how Feynman would do it.

** KILL Favorite Book
CLOSED: [2022-11-13 Sun 14:43]
What’s the last book you’ve read?

What is your favorite book?
a. Say title and author
b. Briefly describe the plot or content of the book
c. Spend more time on the themes of the book and their impact on you
+ “One Hundred Reasons to Be a Scientist” by the International Centre of Theoric Physics starts with a paradoxical idea that our societies depend even more on science, even though their interest in it is declining. I was given an adapted version of this book to the Brazilian public at a SBPC (Brazilian Society for the Progress of Science, in Portuguese) event. While reading the book, I could identify myself with the many stories it told, each scientist sharing their own struggles and why doing science mattered to them. The idea of humanization of science was perhaps the greatest lesson I took away, and I would like to live my life also sharing that idea.

+ You could illustrate better how this impacted you. this is your FAVORITE BOOK!! Interlock it with your life... what did you learn and HOW it changes you.

``After reading this book, I started to...``

+ “One Hundred Reasons to Be a Scientist” by the International Centre of Theoric Physics starts with a paradoxical idea that our societies depend even more on science, even though their interest in it is declining. I was given an adapted version of this book to the Brazilian public at a SBPC (Brazilian Society for the Progress of Science, in Portuguese) event. While reading the book, I could identify myself with the many stories it told, each scientist sharing their own struggles and why doing science mattered to them. The idea of humanization of science was perhaps the greatest lesson I took away, and I would like to live my life also sharing that idea. After reading this book, I started to wonder how some factors in our early lives make us choose something completely different of a carrer, and finally understand how much more important scientific olympiads are. They encourage you to study something that wasn't taught in class before, you become a self learner to compete with other people doing the same thing. You end up learning a lot and also enjoying what you are doing. And the best thing is you are doing it at an early age, and most scientists chose they carrers because of an enjoyment they had when they were young. Scientific olympiads in a country like Brazil, where there is a shortage on scientific production in many fields, is something amazing, and I only came to realize it after reading this book. And now, I want my siblings, aged 11 and 9 to be discovering the world of scientific olympiads, so they can discover themselves.

** KILL Worst&Best
CLOSED: [2022-11-06 Sun 15:29]
What are your best and worst academic qualities?
a. Best – don’t brag, but say something good about you
i. Common good answers – curious, creative, innovative, great leader, passionate
ii. Common Bad answers – hardworking, nice, easy-going, fun

b. Worst – don’t say anything too bad, but don’t say something which isn’t actually bad
i. Common good answers – don’t try as hard on subjects I don’t care about, procrastinate a lot, get lost in details, perfectionist
ii. Common bad answer – bad at time management, lazy, care too much about doing a good job

c. Use details and examples for both parts
+ I am mostly curious, and I can take this quality to a day-to-day basis, because it is simple: if you didn't understand something, ask it. And if you don't have any doubts, it is because you either know everything or you have no idea what you're missing out. So, in the classroom, don't try to impress. The teacher explained something, you didn't get it, ask your question. Leadership is a very useful skill, and when setting up groups, I can use that to make the best out of our time and resources. I understand, being assigned to do a project with people you don't know well can be challenging, so I always try to break the ice and get the people to work beside me.
+ As a bad thing, I don't try to much on subjects I think are of no importance, like portuguse language. Besides having difficulty with it, I don't really get how that's gonna affect my life in the long run, but I do see the appeal to social approaches when studying it. I also tend to procastinate when I don't have as many deadlines or only a few ones, which then make me turn the amount into many deadlines.

+ Your ``worst`` was really not good haha. I mean, DO NOT say that you dont see usefulness in your life. This is a dealbreaker... you can starrt with -- Even though I see the appeal... in my daily life I tend to not put that much effort in subjects like...

+ I am mostly curious, and I can take this quality to a day-to-day basis, because it is simple: if you didn't understand something, ask it. And if you don't have any doubts, it is because you either know everything or you have no idea what you're missing out. So, in the classroom, don't try to impress. The teacher explained something, you didn't get it, ask your question. Leadership is a very useful skill, and when setting up groups, I can use that to make the best out of our time and resources. I understand, being assigned to do a project with people you don't know well can be challenging, so I always try to break the ice and get the people to work beside me.
+ Even though I see the appeal, in my daily life I tend to not put that much effort in subjects like portuguse language. I have some difficulty understanding some norms of portuguse, but I see how that is useful, specially because it is a language, and we communicate with language. I also tend to procastinate when I don't have as many deadlines or only a few ones, which then make me turn the amount into many deadlines sometimes.
** KILL Research
CLOSED: [2022-11-13 Sun 13:46]
If you were given $10 million to do a research project, what project would you do?

a. Pick a subject your passionate about
i. Usually intended major, but doesn’t have to be

b. Be as specific as possible
i. Don’t just say “education research,” say “I want to set up multiple schools in rural China with different education approaches to test the success of each methodology”

c. Be aware of how much money you’re working with
i. You can do a lot with $10 million, but not too much
+ With 10 million dollars, I guess we could start a project in Brazil to further advance the quantum computing context here. We can create cheap, but functional photonic quantum hardware, partering with big Brazilian educational institutions like USP, UNICAMP, UERJ

+ When I saw 19 seconds only... I knew your answer would be limited or superficial...

You gotta contextualize the problem, why you wanna solve it, HOW you would apply the money, etc. Details!!

+ I would like to create a workspace of tools of open source nature to facilitate anyone's class note taking. In high school classes, I realized people take up too much time to write what the teachers write on the board. If you are copying at their pace, it still takes the time the teachers do to write things on the board. Usually in STEM classes, the teachers don't write much text in the board, but rather formulas. As of now I use doom emacs to write text and equations with the LaTeX integration. Doom emacs is an Integrated Development Environment, IDE, that with simple commands I can put my notes on the web and access with any other device. What is missing is missing is special integration to handwriting diagrams. For that, I can use some of Inkscape funcionalities, and a digital tablet. For easy carrying, instead of taking a laptop with you in classes, like I do, you could use a much smaller and efficient device, programmed specifically for taking the best notes of classes, a raspberry pi 4 fits this with ease. With the 10 million dollars, I could fasten the development of this project by hiring people that write software in Linux, and still have enough money to buy this device to 25 incoming classes, supposing the device's cost would be 100 dollars each, and each income class fits 2 thousand students.

** Additional Info
Aside from what has been said in this interview, is there anything else you want the admissions officers to know about you?

a. Pick an activity, interest, or anything else that sounds really good about yourself that you haven’t talked about in the interview so far
** KILL Why us?
CLOSED: [2022-11-13 Sun 10:31]
Describe the reasons you are applying to this specific college
a. Talk about why you are a good fit for the university.

b. Talk about why this university is a good fit for you.

c. How can you contribute to the college community?

Be specific! Give examples.
+ I've already shared my interest for Quantum Computing in this interview, but one thing that sets Duke apart from other universities is the student-led organization DuQIS, that is a place of pre-training and networking where I can grow a lot and will have an impactful contribution of me achieving my goals as a researcher. OSPRI, that develops a professional innovatin ecosystem applying open source methodologies could have some of my contributions, specially in the OSPRI Lab, where I can create learning projects using my knowledge of the open source world. I am also keen on rockets, so I would love to join Duke AERO to participate in rocket competitions
+ Thats THE question -- you took only 53 seconds. start with -- When I was searching for U.S. colleges, I was fascinated about Duke`s... (give examples as you just did here... (i loved the rocket part)), I knew that Duke had to be my early decision option because...

ALWAYS connect with the other parts of your application.
``I can continue...``
``As I did in high school, I am crazy to start...``
+ DuQIS, TUNL, FEL, OSPRI, Duke AERO, Innovation & Entrepreneurship certificate, research opportunities, study language requirement (Germanic Languages and Literature), ECE program.

+ When I was searching for U.S. colleges, I encoutered many things that placed Duke in a higher postion in my college list. Starting with the student-led organization DuQIS, that is a place of pre-training and networking where I can grow a lot and where I can have an impactful contribution, later on, as a researcher. I can learn more about Physics outside the classroom participating in research projects in the facilities of the triangle universities nuclear laboratory, where they have a high intensity gamma-ray source, an electron laser, and even a particle accelerator. Which surely opens new doors to me in what I will be able to do after I graduate. Another thing that interests me is the Electrical and Computer Enginnering program, which made me question if I would persue Computer Science at Duke. If I could explore even more the experimental part of doing science, I guess the ECE program will benifit me even more than the CS major, and Duke ECE program is even ranked the best in US. Now, there is something that I really found interesting and wanted to know more about, which is the Open Source Pedagogy, Research and Inovation center at Duke. I've read they develop a professional innovation ecosystem applying open source methodologies. Being as it is, I could contribute specially in what they cal OSPRI lab, I can create learning projects using my knowledge of the open source world. And talking about innovation, the ability to have a certificate in Innovation & Entrepreneurship is appealing, and I would use that knowledge to foster something unique with my abilities in Science and Technology to positively impact the world. A club I found really interesting at Duke, is the rocketry club. As you can see behind me I have some PET bottle rockets, that I made to participate in the Rocketry Journey, which took me and my team hundreds of hours of testing. At the end, it was worth it, as we were awarded the vice-champion trophy, and got free training to make Solid Propelled rockets in February of 2023. I would be very happy to join the rocketry club at Duke. Now, last thing I guess is the requirements from Trinity college. I would enjoy the language requirements to the best of my abilities. I am planning on continue learning Spanish and German for the coming 2023 year. I have some basic/intermidiate level in those languages already, but Duke education could be very beneficial for me to become a true polyglot. Even the study abroad program, which I guess Duke in Berlin or Duke in Spain or Costa Rica will be appealing to participate.
** KILL Classes
CLOSED: [2022-11-12 Sat 19:30]
Describe what would be a perfect class for you.
i. Do not forget the correct name of the class!!!
ii. Try to think of activities, class structure, class size, topics, etc.
iii. always be specific: is this class project-driven? Does it use a hands-on approach?

Describe what is the class you are most afraid of.
i. Do not forget the correct name of the class!!!
ii. Choose a class that poses a challenge to you: something you are not good at;
iii. Focus on how you want to be challenged nevertheless; that despite being "afraid", you are certain in this specific college they will allow you to thrive, and that you will give your best.
+ A perfect class for me would above all be challenging. I can imagine an Advanced Operating Systems class, where we would be studying the OS structure and kernal internals of the Free BSD distrubition. The 8 people in the classroom will find it funny after they realize Free BSD has a red devil logo.
+ Now, I know for a fact writing classes, which are of mandatory completion at Duke will be most challenging to me because I tend to have more difficulties in those classes, but I am intrigued to see how these writing classes will enable me to explore different sides of me that haven't been explored before. Duke will surely allow me to thrive, and I will try my best to succeed in the writing classes.
+ do not use the word ``afraid``. Say that you know for a fact that writing classes such as YYYYY will be most challenging to you because tend to have more difficulties in such classes, BUT that you also intrigued to see how these classes will enable YOU to explore different sides of you that are unexplored. For instance, I have a student that never imagined he would love to study world literature. He is now in love with it at Grinnell... maybe you will be too haha

+ A perfect class for me would above all be challenging. I can imagine an Advanced Operating Systems class, where we would be studying the OS structure and kernal internals of the Free BSD distrubition. The 8 people in the classroom will find it funny after they realize Free BSD has a red devil logo.
+ Now, I know for a fact writing classes, which are of mandatory completion at Duke will be most challenging to me because I tend to have more difficulties in those classes, but I am intrigued to see how these writing classes will enable me to explore different sides of me that haven't been explored before. Duke will surely allow me to thrive, and I will try my best to succeed in the writing classes.

** KILL Describing you
CLOSED: [2022-11-06 Sun 16:06]
How would your teachers describe you in three words
i.  Say three words (adjectives, nouns)
ii. You can give a brief context before saying the words. For instance: "as I always volunteer to assist my teachers, they would definitely say - proactive, helpful etc.


How would your friends describe you in three words
i. Say three words (adjectives, nouns)
ii. You can give a brief context before saying the words. For instance: "as I always help my peers, they would definitely say - friend, helpful etc.
+ As I always volunteer to assist my teachers, they would definitely say something like I am proactive. As in asking them great questions, they will say I am curious, and a passionate student
+ My friends would say I am collaborative and a leader, since I always find always to make everyone express their thoughts in a more or less organized way depending on the situation. I've also been called dedicated to the things I do a handful of times.
+ That is a great way to answer this! Congratz!

You can also mention 1 event/exp that led the person say it...

For instance, there was a day that...

* Marcohort
+ Covering
+ On 14/11 do:
+ Duke admissions: My counselor said on Nov 6 was submitted school report with the transcript containing first quarter grade report, but the portal says it still awaiting, even though it was sent on nov 6. "How should I proceed? Thank you in advance" Put your ID (it is in the portal) + CSS profile ID (CBFIn stuff)
+ On 16/11 do:
+ Duke: The portal is still red Foreign Financial Aid Appl, and I haven't received any instruxitons, "How should I proceed?" Put your ID (it is in the portal) + CSS profile ID (CBFIn stuff)
+ Explore either second and third paragraph
* Marcohort
- Advise all from ATC to prepare their additional information answer !DONE!
- The Wonder !DONE!
- Temple University !DONE!
- Talk about family lunch !DONE!
- Now: Send an email to BU -> Can you cover the fee waiver as an international student? I am applying by December 1st !DONE!
- Change everything to would, I envision, where I could -> Why Essay !DONE!
- Talk about lunch !DONE!
- Change everything to a less impersonal tone -> talk as if you were talking with a student "come, please". Alternate between giving context, then calling the student out (but in the same paragraph, and no need to do in all of them, but the more the merier) !DONE!
- Read uncovered self, gay passing, gay covering

* Soccer quiz
1. What is the word used when a team scores?
   A: Goal
2. What is the position responsible to be their team's last line of defense?
   A: Goalkeeper
3. What is the position responsible to be their team's offensive line?
   A: Attacker
4. What is Tite's position in Brazil national team?
   A: Coach
5. What is the name of the goal when the player does almost a backflip and kicks the ball in the air?
   A: Bicycle Kick
6. Complete the sentence: Yesterday, Brazil's goal was ruled out for ______
   A: Offside
7. Who is the responsible for enforcing the rules of soccer in the field?
   A: Referee
8. What does VAR stand for?
   A: Video Assitant Referee
9. Which team played against Brazil in the finals of the 2002 world cup?
   A: Germany
10. After the qualifiers, which is the next stage Brazil is going to play?
    A: Round of 16
11. The team who wins a tournment is called Champions, the second place is called Vice-Champions but it is also known as?
    A: Runners-up
12. How many games does a team play until finals?
    A: 6
* Covering
+ Americans realized people should not be penalized for being different in those dimensions, yet it does not protect individuals against demands that they mute those differences
+ Covering is a form of assimilation
+ "I have seen this bargain many times since - in myself and others - compensation for standing out along one dimension by assimilating along others"
+ "Contrary to my belief that I had to kill all but one self, it is the polyphony of selves that has been celebrated here"
+ "All of us struggle for self-expression; we all have covered selves"
+ "There are books around which our lives sink and settle"
+ Describe your covering in a pagraph, passing in another
+ "Unlike conversion and passing, covering is a strategy of assimilation available to all groups, including but no limited to the classic civil rights groups of racial minorities, women, religious minorities, and people with disabilities"
+ "Covering seems a more compelex form of assimilation than conversion or passing."

** Important ones
+ Covering is a form of assimilation
+ "All of us struggle for self-expression; we all have covered selves"
+ "There are books around which our lives sink and settle"
+ "Unlike conversion and passing, covering is a strategy of assimilation available to all groups, including but no limited to the classic civil rights groups of racial minorities, women, religious minorities, and people with disabilities"
+ "Covering seems a more compelex form of assimilation than conversion or passing."

** Structuring
+ "There are books around which our lives sink and settle"
+ My covered self
+ How I had to pass
+ How I had to cover

* Marcohort
+ The transition between what you are tutoring and what you are proposing is confusing -> the experience itself in high school is not connected
+ Develop the Student Group idea
+ Talking too much about Community Bridges
+ Shorten the help students with physics, and focus more on creating groups
+ This essay is also about cultural tradition -> try to say you created a school tradition: english club, and from that you created other clubs (because tradition helped you)
+ Use words such as community, collaboration, school tradition, at schoool you really learned in teams (learned to work with other people) -> let it clear that you build up these life experiences. You school is an environment that makes you work in community, that focuses on community building,, then you can  talk about rice that you are going to take this community building and applying to rice
+ Propose the creation of a club, focus on something specific, tanto creating quanto participating -> Mention stuff on how you could engage in rice

* Marcohort
+ Question: At Emory I gotta submit my international student documentation of finances and I need to upload a bank statement there, does it need to be translated?
+ Question: Consegui o fee waiver de washington and lee, posso já enviar o css profile?
+ Ask for Marco to verify Raquel's peer letter.

* Loa
 + Vai ser uma reunião bem curtinha, vamos adicionar vocês no whatsapp depois
 + Sua apresentação: Eu sou o Luis, tenho 17 anos, to terminando o curso técnico em eletrotecnica no instituto federal de mato grosso do sul. Tenho muito interesse pela área da física e da ciência da computação e to no processo de application para as faculdades nos EUA. Na LOA, eu sou o diretor de conteúdo, então é o cargo responsável..
 + Introdução: Cada um pensa em 3 afirmações, uma delas é falsa
 + Como preferem ser chamados?
 + When will we get back? On the week of Jan 8, 2023
** Alexia
+ Prefere ser chamada de Francine, mora no RN
+ Telefone: +55 (84) 991465671
+ Impacto acadêmico, interesse em melhorar
+ Editora de vídeo!
** Maiara
+ Telefone:
+ A junção, humanização, redação de artigos para democratização
+ Criador de conteúdo
** Pedro
+ Mora no SJ
+ Telefone: +55 (79) 988010396
+ Faculdade Astrofísica, envolvido com educação, boa didática
+ Criador de conteúdo
** Paula
+ Mora no Ceará
+ Telefone: +55 (88) 99989 2718
+ Observativa, organizada, humanização
+ Criador de conteúdo
* Afirmações
+ Mentira: Faz duas semanas que eu uso Linux
+ Verdade: Eu tenho 2 irmãos e 7 meio irmãos
+ Verdade: Eu fui campeão da interclasse da minha escola no fundamental
