#+TITLE: Instrumentação e Controle
#+DESCRIPTION: Instrumentação e Controle - Meu caderno virtual
#+SETUPFILE: https://luispengler.github.io/site/org-html-themes/org/theme-readtheorg.setup
#+LaTeX_+HEADER: \usepackage{physics}
#+LaTeX_+HEADER: \usepackage{amsmath}
#+OPTIONS: num:nil ^:{} toc:2

* Primeira Aula
+ O professor Hilton James passou como vai ser as notas da disciplina, de acordo com a seguinte equação
  \[MF=\frac{[(P1\cdot 0,7)+(Ativ. Trab.\cdot 0,3)]+[(P2\cdot 0,7)+(Ativ. Trab.\cdot 0,3)]}{2}\]

Sendo P1 dia 31/03 e sua recuperação dia 07/04 e a P2 sendo dia 09/06 e sua recuperação dia 23/06.

+ Ele também passou seus horários de permanência: 14h30-17h05 (WED), 08h30-10h20 (THU), 18h50-20h20 (FRI) - Salas B206, B102, B204

+ A disciplina vai ser ministrada pelo professor Hilton James na parte prática e a teoria com a professora Gabriele Kavano

+ Horário de PE da professora: 15h35-16h30 (THU)

** Tipos de processos (ponto de vista do tempo e do tipo de operação envolvida)
*** Processo Contínuo
+ A adição da matéria-prima e a saída do produto são contrínuas (no sentido de não ser interrompido). Ex: Refinaria de petróleo
  - Não realizam paradas periódicas (Works 24/7), exceto por paradas progamadas com um periodo maior que 1 ano
  - Esse tipo de industria faz somente um produto

*** Processo em Batelada
+ O processo é alimentado e re-alimentado. O produto é descarregado e inicia-se outro ciclo, sendo o intervalo entre estes curto.
+ Permite vários produtor em uma mesma linha de produção. Ex: Fanta laranja, fanta uva, etc...
+ É um processo descontínuo

*** Processo Discreto
+ Itens separados = produto
+ Não tem dependência de outras etapas como no processo contínuo, ou tanto quanto em batelada
+ Geralmente usa-se robos
+ Industria de automóveis é um exemplo


* Aula 17/02
+ Tivemos que fazer o pré-rascunho de um artigo em trio. Fui com Daniel e Lukas. Obtivemos a seguinte belezinha
#+ATTR_HTML: alt: waterwave :title Primeira atividade prática :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://luispengler.github.io/site/org-pages/notes/12th-grade/doc/instrumenta1.jpg

* Aula 18/02
** Classes de instrumentos
+ Podem ser divididos em várias categorias
*** Elemento primário/Sensor
+ Capaz de detectar a variação de uma grandeza física e converter um tipo de grandeza que pode ser mensurada por dispositivos eletrônicos. Ex: termometro
+ Esta classe é dividida entre instrumento cego (não apresenta um visor) e instrumento indicador (possui um visor)
+ Normalmente se associa com outros componentes para se tornar um transdutor

*** Registrador
+ Registra as variações de uma ou mais variáveis, guardando as em discos ou fitas de papel e através de displays eletrônicos

*** Conversor
+ Recebe um tipo de sinal e o converte em outro

*** Transmissor/Transdutor
+ Mede uma grandeza física e transmite um sinal padronizado proporcional a faixa de variação da grandeza

*** Controlador
+ Recebe sinais dos transmissores/sensores e com base nisso, faz a correção do sistema acionando os atuadores

*** Atuador/Elemento final de controle
+ Provoca uma mudança em uma variável do processo de acordo com um sinal enviado pelo controlador do processo.

* Aula 24/02
+ Fazer pré-rascunho de um artigo (sozinho), contendo Introdução, Problemática, Objetivo...
+ Aqui está o [[https://luispengler.github.io/site/org-pages/notes/12th-grade/doc/instrumentacao1/instrumentacao1.pdf][artigo pronto]]

* Aula 25/02
*** Zero Vivo
+ Transmissão de um sinal de 4 a 20mA, com 4 sendo o 0% do nível de água de um recipiente. 20mA representa 10%

** Características dos sistemas de medição
*** Faixa nominal (nominal range)
+ Limite superior e inferior da faixa de trabalho do instrumento

*** Fundo de escala
+ Valor máximo que um instrumento de medida pode medir sem ser danificado

* Aula 03/03
+ O professor fez a correção da atividade entregue anteriormente (aula 24/02)
+ Fomos apresentados o sensor infrared difuse e o infrared retroreflective. Depois fomos pedidos para escolher o melhor desses dois para identificar a passagem de ouro numa linha de trituração e o melhor entre os dois para identificar se há um objeto passando OU NÃO em uma linha de produção.
+ Retro-reflective: Sinal lógico 0 quando nada está passando. Mas existem dois tipos, aqueles que emitem ondas polarizadas e que não. Não polarizados não saberiam diferenciar o seu espelho retro-refletor de um objeto metálico, se este redirecionasse o feixe do emissor diretamente no receptor. Neste caso, objetos metálicos, às vezes, fariam o nível lógico voltar pra 0. Com objetos normais, o nível lógico continuaria sendo 1. É sensível até 7m. No entanto, para o tipo de ondas polarizadas, qualquer objeto que interrompa o feixe, mesmo que este seja metálico (ou até outro espelho!), o sinal lógico vai ser 1. É sensível de 3 a 5,5m.
+ Difuse: A diferença entre este e o anterior, é que usam o alvo para mandar a luz de volta (em vez de um espelho). No entanto, nem todos os alvos são bons em emitir luz de volta e precisam estar mais perto do que alguns para serem detectados. Sensores de proximidade difusos tem um alcance de até 500mm. Qualquer alvo dentro deste alcance vai ser visto, contanto que reflita luz suficiente. Para aplicações menores (com alvos menores), existe o tipo de foco fixo. O foco do emissor e receptor estão no mesmo ponto do espaço, aumentando a sua precisão, mas diminuindo o alcance quando comparados com sensores de proximidade difusos. Alcance de geralmente até 70mm.
+ Resposta (remover depois) difuso para o do ouro e retoreflector não polarizado para linha de produção
+ Aqui está o artigo pronto

* Aula 04/03
+ Prova semana que vem (atividade avaliativa) até a Aula 3 no moodle
** Tipos de sensores
+ Sensores industriais: Pega uma variável e transforma em outra variável mais conveniente
+ Sesnsores podem ser do tipo discreto e contínuo

*** Sensores discretos
+ Apenas ligado ou desligado
+ Ex: Chave fim de curso

**** Sensores de proximidade discretos
+ Detectar a presença de um determinado objeto e chaves eletromecânicas são atuadas em função disso
+ Usado para detecção de posição, contagem de peças, medição da velocidade, detecção do nível de água e detecção de altura, detecção de forma, detecção de ferramenta

**** Definições Básicas
+ Face sensora: superficie de onde sai campo elétrico ou campo eletromagnético
+ Distância sensora nominal (Sn): Distância teórica que os sensores são específicados. Não significa que ele sempre vai operar nessa faixa.
+ Distância sensora operacional (Sa): Distância segura, em que se considera todas as variáveis de industrialização, temperatura e tensão de alimentação.
\[S_{a}=0,81\cdot S_{n}\]
+ Alvo padrão: É um acionador normalizado para calibrar a distância sensore nominal durante o processo de fabriação do sensor. Este consiste de uma chapa de aço de 1mm de espessura, formato quadrado, mas essas medidas mudam por sensor.
+ Histerese: Diferença entre o ponto de acionamento e o ponto de desligamento. Basicamente a medida (em m, mm, cm, etc) da diferença de desligar ou ligar um sensor

**** Configurações elétricas em corrente contínua
+ Apresentam várias formas de estágios de saída.
+ A configuração elétrica em corrente contínua é bastante usada na automação de processos.
+ Existem dois tipos de transistores de saída
  - Um que comuta o terminal positivo da fonte (PNP)
  - Otro que comuta o terminal negativo da fonte (NPN)
+ Esses tipos de sensores apresentam características que dependem do conhecimento das definições abaixo
  - Normalmente aberto (NO) (NA): O transistor de saída está normalmente cortado, com o sensor desativado, assim a carga está desativada também.
  - Normalmente fechado (NC) (NF): O transistor de saída está normalmente saturado, com o sensor ativado, assim a carga está ativada também.

**** Tipos de sensores de proximidade
***** Indutivos: detectam a proximidade de elementos metálicos sem a necessidade de contato
+ Este gera um campo eletromagnético que é gerado por uma bobina ressonante instalada na face sensora
+ Sua distância sensora operacional depende do tipo de material e é multiplicada por um fator de redução

***** Magnéticos: detectam a proximidade de um imã, atuando de acordo com a sua presença e ausência
***** Capacitivos: detectam a presença de materiais orgânicos, pós, líquidos, entre outros. Assim como objetos dentro de objetos (líquidos dentro de garrafas)
+ Consiste de duas placas paralelas (armaduras) e isoladas por um dielétrico
+ O valor da capacitância pode ser alterado pela aproximação de um objeto
+ Por serem utilizados em uma grande variedade de objetos, geralmente há algum tipo de ajuste de sensibilidade presente na parte traseira do sensor.
+ Permissividade relativa: uma medida do aumento de capacidade de armazenar energia em um meio dielétrico sob efeito de um campo elétrico. Quanto maior esse valor, maior a quantidade de cargas elétricas que o capacitor será capaz de armazenar em suas armaduras.
+ São influenciados pela densidade do meio onde o sensor está instalado, então tomar cuidado com este ambiente

***** Sensores de proximidade fotoelétricos
+ Denomidados de sensores ótpicos, os quais manipulam a luz para detectar a presença de um objeto dentro de uma área delimitada
+ Transmissor: Apenas sensores fotoelétricos ativos o apresentam. Este componente envia um feixe de luz através de um LED. Esses flashes são de alta potência e de curta duração
+ Receptor: Composto por um fototransistor que é sensível à luz emitida pelo transmissor
+ Conversor de sinal: Converte os pulsos de luz do transmissor em sinais elétricos.
+ Estes ainda podem ser
  - Ativos: Necessitam de transmissor e receptor de infravermelho separados
  - Passivos: Apresentam somente receptores pois não emitem ondas infravermelhas

****** Sistema por barreira direta
+ Transmissor e receptor estão em unidades distintas e devem ser dispostos frente a frente
+ Quando houver alguma interrupção, a saída será acionada
****** Sistema por difusão
+ O transmissor e receptor são montados na mesma unidade
+ O acionamento da saída ocorre quando o objeto a ser detectado entre na região de sensibilidade e reflete para o receptor o feixe de luz emitido pelo transmissor
+ É muito eficiente com objetos metálicos, pois depende do índice de reflexão do objeto
+ É calibrado com uma folha de papel branco, apresentando índice de refletividade de 90%
\[S_{a}=0,81\cdot S_{n}\cdot F\]

* Aula 10/03
+ Instrumentamos sensores capacitivos e indutivos com diversos materiais (silicone, joelho de cano pvc, cabo de cobre isolado com borracha)

* Aula 11/03
** Sensores de proximidade ultrassônicos
+ Emprega frequências fora do espectro de audição humana, determinando a distância de objetos (proximidade)
+ A detecção acontece quando a onda bate sobre um objeto e produz um eco
+ O tempo de repetição do eco é medido, sendo convertido em um sinal elétrico.
+ Existe uma repetição desses pulsos de onda mecânica de 1 a 100Hz.
*** Vantagens
+ Detcção sem contato direto
+ Detecção idependente da cor
*** Desvantages
+ Dificuldade de detecção se há muitas irregularidades no objeto
+ Esse sensor é relativamente lento (porque usa som)
+ Custo maior comparado aos fotoelétricos
+ Podem ser influenciados pela temperatura (porque a velocidade do som muda de acordo com a temperatura)
+ Dificuldade no uso de vários sensores ultrassônicos próximos (por causa da interferência)
** Sensor óptico de posição (encoder)
+ Detectam a posição de um objeto com respeito a um ponto de referência
+ Podem medir distâncias lineares quanto angulares
+ Funciona convertendo o movimento ou posição angular em uma série de pulsos.
*** Encoder absoluto
+ Definimos a posição absoluta do encoder através de um código
+ O código mais utilizado é o binário, mas pode ser o código de Gray
*** Encoder Incremental
+ Possui apenas uma trilha com dentes igualmente espaçados
+ A resolução é dada pela relação pulso/revolução (chamado de PPR) - Quantos pulsos de luz por cada volta?
+ Podem ser dividos em simples e quadratura
