#+TITLE: Máquinas Elétricas e Acionamentos 2 - Meu caderno virtual
#+DESCRIPTION: Máquinas Elétricas e Acionamentos 2 - Meu caderno virtual
#+SETUPFILE: https://luispengler.github.io/site/org-html-themes/org/theme-readtheorg.setup
#+LaTeX_+HEADER: \usepackage{physics}
#+LaTeX_+HEADER: \usepackage{amsmath}
#+OPTIONS: num:nil ^:{} toc:2

* Primeira Aula
O professor só introduziu a disciplina, mas começando uma revisão de eletricidade 2 e máquinas elétricas e acionamentos 1, tanto nas aulas teóricas, quanto nas práticas

O professor disse que a tensão era o conceito mais fundamental da eletricidade que a gente trabalha. Sem tensão, não há palavras chiques: corrente, resistência, capacitância, campo eletromagnético...

+ Campo Grande tem uma tensão fase-neutro de 127V, fase-fase é de 220V
+ Bahia tem uma tensão fase-neutro de 220V, fase-fase é de 380V

* Segunda Aula
+ Por causa da frequência, que é 1, onde T é o tempo decorrido de um ciclo completo em uma onda senoidal, que só acontece em C.A, temos:
\[X_L=2\cdot \pi\cdot f\cdot L\]
\[X_C=\frac{1}{2\cdot \pi\cdot f\cdot C}\]

+ Toda corrente trifásica pode ser calculada de acordo com as fórmulas abaixo, em função do tempo
\[ia(t)=im\cdot cos(\omega\cdot t+0º)\]
\[ib(t)=im\cdot cos(\omega\cdot t-120º)\]
\[ic(t)=im\cdot cos(\omega\cdot t+120º)\]

+ Em uma instalação trifásica os custos dos materiais são reduzidos em 25% para a mesma quantidade de energia transformada e gerada.

* Aula 07/03 (Aula prática)
+ Entendemos os tipos de ligações dentro dos motores de indução trifásicos apresentados
+ Um dos modelos era o que eu chamo de "bivolt manual". Era possível ligar ele em 220V, se fosse uma ligação delta. Em 380V esta era uma ligação estrela.

* Aula 08/03 (Aula prática)
+
