#+TITLE: Luis Spengler's Open Research Initiative
#+DESCRIPTION: Luis Spengler's Open Research Initiative
#+SETUPFILE:  https://luispengler.github.io/site/org-html-themes/org/theme-readtheorg.setup
#+OPTIONS: num:nil ^:{} toc:nil

* Why?
"Science is, by nature, a collaborative venture; however, a ‘closed’ culture of science has nonetheless developed. Data are often hoarded for extended periods of time, paywalls prevent access to articles and unnecessary hurdles continue to slow the rate of progress. An ‘open’ culture of science would provide the most benefit to the public, to the scientists involved and to science itself, and it is best to begin practicing open science as early as possible in your scientific career." Ben Thomas; Science is necessarily collaborative. Biochem (Lond) 22 June 2020; 42 (3): 58–60. doi: https://doi.org/10.1042/BIO20200030

So... I can say that's the best reason a decided to put on my website what I was working on. I promise my *personal* research will always be here (perhaps *still* in development, but I will hide nothing), however I cannot say the same when I am not the main author, or I am following strict orders from any reasearch institute I end up working for.

Therefore, I must state: My *personal* research will always remain open to you, including, but not limited to ".tex" file, and rendered PDF. I shall also never obly you to pay to gain access. I will not submit you to a paywall. I do not promise to always have reasearch done in english, even though it would ease the spread of science. I cannot always have the luxury to write in english, since I am still a brazilian student *studying* in Brazil.

Sugestions, contribuitions, and constructive criticism torwads my research is *always* welcome. You can follow my contact page. (luispengler@protonmail.com)

* Open Research
1. On Linux [DEV] (portuguese): [[https://luispengler.github.io/site/doc/articles/linux/linux.pdf][PDF]], [[https://luispengler.github.io/site/doc/articles/linux/linux.tex][LaTeX]]
2. On Recycling [IDEA] (english): [[https://luispengler.github.io/site/doc/articles/recycling/recycling.pdf][PDF]], [[https://luispengler.github.io/site/doc/articles/recycling/recycling.tex][LaTeX]]
