#+TITLE: Luis Spengler's actually read books list
#+DESCRIPTION:luispengler.github.io/site - Luís Spengler's official webpage
#+SETUPFILE:  https://luispengler.github.io/site/org-html-themes/org/theme-readtheorg.setup
#+OPTIONS: num:nil ^:{} toc:2

* 2022
** Miss Peregrine's Home for Peculiar Children - Ransom Riggs
*** Total books
+ Miss Peregrine's Home for Peculiar Children
+ Miss Peregrine's Home for Peculiar Children - Hollow City
+ Miss Peregrine's Home for Peculiar Children - Library of Souls
+ Miss Peregrine's Home for Peculiar Children - A Map of Days
+ Miss Peregrine's Home for Peculiar Children - The Conference of the Birds
+ Miss Peregrine's Home for Peculiar Children - The Desolations of Devil's Acre
+ Tales of the Peculiar

*** Cover sample
#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 50%;
https://luispengler.github.io/site/doc/images/missperegrines.jpg

*** Description
"A mysterious island. An abandoned orphanage. A strange collection of vintage photography. It all waits to be discovered in Miss Peregrine’s Home for Peculiar Children, a spine-tingling YA fantasy illustrated with haunting black-and-white photography. The hardcover edition spent more than 52 consecutive weeks on the New York Times Best-Seller List. This beautifully designed paperback edition features an exclusive interview with author Ransom Riggs and a sneak preview of the upcoming Miss Peregrine novel."


** QED: The Strange Theory of Light and Matter - Richard P. Feynman

*** Cover sample
#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 50%;
https://luispengler.github.io/site/doc/images/qed.jpg

*** Description
"Celebrated for his brilliantly quirky insights into the physical world, Nobel laureate Richard Feynman also possessed an extraordinary talent for explaining difficult concepts to the general public. Here Feynman provides a classic and definitive introduction to QED (namely, quantum electrodynamics), that part of quantum field theory describing the interactions of light with charged particles. Using everyday language, spatial concepts, visualizations, and his renowned "Feynman diagrams" instead of advanced mathematics, Feynman clearly and humorously communicates both the substance and spirit of QED to the layperson. A. Zee's introduction places Feynman’s book and his seminal contribution to QED in historical context and further highlights Feynman’s uniquely appealing and illuminating style."

** What is Spiritism? - Allan Kardec

*** Cover sample
#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 50%;
https://luispengler.github.io/site/doc/images/spiritism1.jpg

*** Description
"A work that is still up-to-date, What is Spiritism? is useful for adherents of the Spiritist Doctrine as well as for those who want to understand the nature of Spiritism and its fundamental points. Kardec’s logic and common sense are obvious in this book as he confounds Spiritism’s detractors while answering the questions of those who believe in and aspire to a superior life. The book is divided into three chapters. The first is composed of dialogues between Kardec and a critic, a skeptic and a priest, providing answers to those who do not understand the basic principles of Spiritism. It also presents appropriate refutations to its opponents. The second chapter presents practical and experimental aspects of the science and is a kind of summary of The Mediums’ Book. The third chapter is a short synthesis of The Spirits’ Book, with solutions to psychological, moral and philosophical problems according to the Spiritist Doctrine. In addition, the book is prefaced with an abridged version of Henri Sausse’s biography of Allan Kardec.""

** Triste Fim de Policarpo Quaresma - Lima Barreto
*** Cover Sample
#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 50%;
https://luispengler.github.io/site/doc/images/tristefim.jpeg
*** Description
"Publicado inicialmente em folhetins no ano de 1911, Triste fim de Policarpo Quaresma é um romance do período do Pré-Modernismo brasileiro. Por meio da vida tragicômica do major Quaresma, um nacionalista fanático, ingênuo e idealista, Lima Barreto revela as estruturas sociais e políticas do Brasil da Primeira República, enfocando os fatos históricos do governo de Floriano Peixoto. Sobre o autor: Afonso Henriques de Lima Barreto (1881-1922), filho de um tipógrafo da Imprensa Nacional e de uma professora pública, era mestiço e foi iniciado nos estudos pela própria mãe. Ainda estudante, começou a publicar seus textos em pequenos jornais e revistas estudantis, incrementando mais tarde sua militância na imprensa, lutando contra as injustiças sociais e os preconceitos de raça, de que ele próprio era vítima."

** O Presidente Negro - Monteiro Lobato
*** Cover Sample
#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 50%;
https://luispengler.github.io/site/doc/images/opresidentenegro.jpg
*** Description
"A história de O Presidente Negro, único romance adulto de Monteiro Lobato, passa-se nos Estados Unidos e aborda temas como a segregação racial, aculturação, feminismo e ainda profetiza o surgimento de uma rede pela qual as pessoas se comunicariam e trabalhariam à distância, semelhante à internet. Através das lentes do “porviroscópio”, aparelho capaz de prever o futuro, Lobato leva os leitores para 2228, ano em que o personagem norte-americano Jim Roy, um negro, concorre à presidência."

** Outras tantas histórias indígenas de origem das coisas e do universo - Daniel Munduruku
*** Cover Sample
#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 50%;
https://luispengler.github.io/site/doc/images/historiasdaniel.jpg
*** Description
"Quatro histórias são recontadas pelo autor. Duas tratam da origem do fogo, uma do mito do povo Tariano, do Amazonas, e outra do mito do povo Bororo, de Mato Grosso; uma terceira sobre a origem do Universo, mito do povo Aruá, habitante da região de Rondânia, e uma quarta sobre a origem do povo Kaiapó, habitante da região do Pará. No prefácio do livro, o autor, Daniel Munduruku, comenta: Estas histórias que estou recontando fazem parte de um grande diálogo entre natureza e cultura. É uma conversa que vem se repetindo ao longo da história humana neste nosso planeta. (…) Estas histórias contam como alguns dos povos indígenas do Brasil criaram um caminho muito próprio e especial e como “receberam seus bens culturais” que os tornou humanos sujeitos a erros e a acertos durante sua caminhada. É com esse olhar que convido vocês a entrar em contato com estas histórias (…)."

** Quarto de despejo - Carolina Maria de Jesus
*** Cover Sample
#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 50%;
https://luispengler.github.io/site/doc/images/quartocarolina.jpg
*** Description
"O diário da catadora de papel Carolina Maria de Jesus deu origem à este livro, que relata o cotidiano triste e cruel da vida na favela. A linguagem simples, mas contundente, comove o leitor pelo realismo e pelo olhar sensível na hora de contar o que viu, viveu e sentiu nos anos em que morou na comunidade do Canindé, em São Paulo, com três filhos."

** A desumanização - Valter Hugo Mãe
*** Cover Sample
#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 50%;
https://luispengler.github.io/site/doc/images/desumanizacao.jpg
*** Description
"Quarto romance do aclamado escritor português a ser lançado pela Cosac Naify, A desumanização se passa na paisagem inóspita dos fiordes islandeses. Narrado por uma menina de 11 anos que nos conta, de maneira muito especial, o que lhe resta depois da morte da irmã gêmea, o livro é feito de delicada melancolia e extrema beleza plástica."

** NO Finished - A Hora da Estrela - Clarice Lispector
*** Cover Sample
#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 50%;
https://luispengler.github.io/site/doc/images/claricehora.jpg
*** Description
"Último livro escrito por Clarice Lispector, A hora da estrela é também uma despedida. Lançada pouco antes de sua morte em 1977, a obra conta os momentos de criação do escritor Rodrigo S. M. (a própria Clarice) narrando a história de Macabéa, uma alagoana órfã, virgem e solitária, criada por uma tia tirana, que a leva para o Rio de Janeiro, onde trabalha como datilógrafa. Em A hora da estrela Clarice escreve sabendo que a morte está próxima e põe um pouco de si nas personagens Rodrigo e Macabéa. Ele, um escritor à espera da morte; ela, uma solitária que gosta de ouvir a Rádio Relógio e que passou a infância no Nordeste, como Clarice. A despedida de Clarice é uma obra instigante e inovadora. Como diz o personagem Rodrigo, "estou escrevendo na hora mesma em que sou lido". É Clarice contando uma história e, ao mesmo tempo, revelando ao leitor seu processo de criação e sua angústia diante da vida e da morte. Macabéa, a nordestina, cumpre seu destino sem reclamar. Feia, magra, sem entender muito bem o que se passa à sua volta, é maltratada pelo namorado Olímpico e pela colega Glória. Os dois são o seu oposto: o metalúrgico Olímpico sonha alto e quer ser deputado, e Glória, carioca da gema e gorda, tem família e hora certa para comer. Os dois acabam juntos, enquanto Macabéa, sozinha, continua a viver sem saber por que está vivendo, sem pensar no futuro nem sonhar com uma vida melhor. Até que um dia, seguindo uma recomendação de Glória, procura a cartomante Carlota, uma ex-prostituta do Mangue, que revela a Macabéa toda a inutilidade de sua vida. Mas também enche-a de esperança, prevendo a paixão por um estrangeiro rico, com quem ela iria se casar."
