#+TITLE: Big Form
#+DESCRIPTION: Big form
#+SETUPFILE:  https://luispengler.github.io/site/org-html-themes/org/theme-readtheorg.setup
#+OPTIONS: num:nil ^:{} toc:1

* Writing and Activities Section - for future reference
** Extracurricular activities
+ LIST your extracurricular activities (i.e activities that students do outside of their classroom work, such as participation in clubs and societies, volunteer work, house responsibilities). Include dates of participation and briefly the type of activities that you do. Write them in order of importance. Also, feel free to share a link in the description of the activity, if applicable.

*** Position/Leadership position
Staff Member and Leader
*** Organization Name OR name of the activity
English Club
*** Period of participation
2020-2022
*** Hours per Week and Weeks per Year
4h/w; 48w/y
*** Please describe this activity, including what you accomplished and any recognition you received, etc. [Feel free to share a link if applicable].
I joined in 2020 and due to the pandemic, we promoted online meetings, and digital content production. Instagram was the tool used to spread our digital content, with 109 posts. We enhanced and strengthened institutional internacionalization, and helped students develop their English. For our research we were honered with Best Project at High School Level in a state wide science fair (Fecintec), leading us to one state wide presentation and two national science fairs. https://www.instagram.com/englishclubcg/

*** Position/Leadership position
Video editor senior
*** Organization Name OR name of the activity
Liga Olimpica de Astronomia
*** Period of participation
2021-2022
*** Hours per Week and Weeks per Year
5h/w; 40w/y
*** Please describe this activity, including what you accomplished and any recognition you received, etc. [Feel free to share a link if applicable].
Olympiad League of Astronomy is a project focused on astronomy dissemination. We have 1,354 followers on Instagram and our recent youtube channel has 175 subscribers. However the project started as a webpage. We offer preparation for Astronomy Olympiads, be it national or international (OBA, MOBFOG, OLAA, IOAA), as well as having anything (exams, worklists, books, handouts, articles, guides) you will need to study for them. https://ligadeastronomia.com/ https://www.youtube.com/channel/UCzd-QgsR05lxMWl1Wa0KKuQ

*** Position/Leadership position
IGTV&Live team member
*** Organization Name OR name of the activity
Yo Científicx
*** Period of participation
2020-2021
*** Hours per Week and Weeks per Year
4h/w; 45w/y
*** Please describe this activity, including what you accomplished and any recognition you received, etc. [Feel free to share a link if applicable].
Yo Científicx is a project focused on scientific dissemination. It is an Instagram and presencial project focused on bringing academic level science to high school students that engage with us. https://www.instagram.com/yocientificx/

*** Position/Leadership position
English Mentor 1st cycle
*** Organization Name OR name of the activity
Projeto iLearn
*** Period of participation
2020
*** Hours per Week and Weeks per Year
6h/w; 20w/y
*** Please describe this activity, including what you accomplished and any recognition you received, etc. [Feel free to share a link if applicable].
40 students impacted.https://www.instagram.com/projetoilearn/

** Academic accomplishments
+ LIST your academic accomplishments (honors, medals, olympiads) and include a title for each one. Make sure you include if it is school wide, state wide, national, or international. Write them in cronological order, from most recent to least recent.

*** Honor title
Honorable Mention - 5th International Physics and Culture Olympiad (IPhCO)
*** Year of accomplishment
2021
*** Level of Recognition
International

*** Honor title
Honorable Mention - 24th Brazilian Olympiad of Astronautics and Astronomy (OBA)
*** Year of accomplishment
2021
*** Level of Recognition
National

*** Honor title
Honorable Mention - Physics Brazilian Olympiad for the Public Schools (OBFEP) 2021
*** Year of accomplishment
2021
*** Level of Recognition
National

*** Honor title
Best project at High School level - Science and Technology Fair of Campo Grande MS (Fecintec) 2021
*** Year of accomplishment
2021
*** Level of Recognition
State wide

*** Honor title
Silver medal - Physics Brazilian Olympiad (OBF) 2021
*** Year of accomplishment
2020
*** Level of Recognition
State wide

** Essays
+ Prompt: Which major would you like to pursue and why? Even if you are undecided, tell us why. Please provide details. (250 - 500 words)
  My interest for Physics actually started with Chemestry. As a 6 year-old boy, I would ask my dad to print me a new periodic table everytime I ran out of ways to set it up. But truth be told: at that time all I ever wanted to do was learn anything I found interesting. In Physics, one can never run out of curiosity and my inner-childhood never allowed me to do that. Throughout years I have been amazed by what humanity was able to do just by mastering Physics. How does an airplane that weights 440 tons fly anyway?
  When I was 14 I got surprised how Linux made all the crappy computers I ever owned seem like they could have a new life. Simply learning how I could use this operating system with more efficiency helped me see the bigger picture. Just like operating systems, computers are simply a tool. And the better a tool becomes, more efficiently we are able to solve our unique set of problems. Be it improving chaotic system simulations for whether forecast or providing assistance in solving united nations' Zero Hunger Goal.
  I want to be part of that. Quantum computers represent our best chance of doing many things we didn't imagine would be possible.

+ Optional: Please use this space to provide details of circumstances or qualifications not contemplated in this section (300 words or less). *
