#+TITLE: Big Form
#+DESCRIPTION: Big form
#+SETUPFILE:  https://luispengler.github.io/site/org-html-themes/org/theme-readtheorg.setup
#+OPTIONS: num:nil ^:{} toc:1

* Additional Information


* Writing and Activities Section - for future reference
** Extracurricular activities
+ LIST your extracurricular activities (i.e activities that students do outside of their classroom work, such as participation in clubs and societies, volunteer work, house responsibilities). Include dates of participation and briefly the type of activities that you do. Write them in order of importance. Also, feel free to share a link in the description of the activity, if applicable.

*** Position/Leadership position
Staff Member and Leader
*** Organization Name OR name of the activity
English Club
*** Period of participation
2020-2022
*** Hours per Week and Weeks per Year
4h/w; 48w/y
*** Please describe this activity, including what you accomplished and any recognition you received, etc. [Feel free to share a link if applicable].
I joined the club in 2020 and due to the pandemic, we promoted online meetings, and digital content production. Instagram was the tool used to spread our digital content, with 109 posts created since its creation date. We enhanced and strengthened institutional internacionalization, and helped students develop their English. For our research we were honered with Best Project at High School Level in a state wide science fair (Fecintec), leading us to one state wide presentation and two national science fairs, from which we received R$ 4,200.00. Link to our Instagram: https://www.instagram.com/englishclubcg/

*** Position/Leadership position
Student
*** Organization Name OR name of the activity
Qubit by Qubit by The coding School
*** Period of participation
2021-2021
*** Hours per Week and Weeks per Year
6h/w; 24w/y
*** Please describe this activity, including what you accomplished and any recognition you received, etc. [Feel free to share a link if applicable].
An online course with the mission of empowering students with the skills and confidence necessary to become future leaders, problem solvers and innovators through quantum education. Taught by MIT Scientists (other universities too!) and Sponsored by IBM, this is the only online course about quantum computing open worldwide for high school students. QubitxQubit excits me every week with lectures and lab sessions and I take advantage of these moments to learn as much as I can about the field I want to specialize in. I even started sharing my notes with the worldwide web: https://luispengler.github.io/site/html/org-pages/quantum-computing.html also here's a link to my first semester grades: https://drive.google.com/file/d/1X8zmCD8W1R8TCljNCOMkUOpgvaeku9UF/view?usp=sharing

*** Position/Leadership position
IGTV&Live team member
*** Organization Name OR name of the activity
Yo Científicx
*** Period of participation
2020-2021
*** Hours per Week and Weeks per Year
4h/w; 45w/y
*** Please describe this activity, including what you accomplished and any recognition you received, etc. [Feel free to share a link if applicable].
Yo Cientificx is a project focused on scientific dissemination. It is an Instagram and presencial project focused on bringing academic level science to high school students. One of our biggest accomplishments was to hold webinars with some famous Brazilian scientists, who represented minorities, with the goal to inspire these same high school students that are from these minorities. Another big accomplishment of ours was having 43 people enrolled in a 11 week course about scientific methodology and how to develop your own project. Throughout my time in the team I was able to interview people - with whom I would like to work with - for livestreams and Instagram videos. Link to the project's Instagram: https://www.instagram.com/yocientificx/

*** Position/Leadership position
Video editor senior
*** Organization Name OR name of the activity
Liga Olimpica de Astronomia
*** Period of participation
2021-2022
*** Hours per Week and Weeks per Year
5h/w; 40w/y
*** Please describe this activity, including what you accomplished and any recognition you received, etc. [Feel free to share a link if applicable].
Olympiad League of Astronomy is a project focused on astronomy dissemination. We have 1,354 followers on Instagram and our recent youtube channel has 175 subscribers. However the project started as a webpage. We offer preparation for Astronomy Olympiads, be it national or international (OBA, MOBFOG, OLAA, IOAA), as well as having anything (exams, worklists, books, handouts, articles, guides) you will need to study for them. Link to the project's website: https://ligadeastronomia.com/ Link to the youtube channel: https://www.youtube.com/channel/UCzd-QgsR05lxMWl1Wa0KKuQ

*** Position/Leadership position
English Mentor 1st cycle
*** Organization Name OR name of the activity
Projeto iLearn
*** Period of participation
2020
*** Hours per Week and Weeks per Year
5h/w; 20w/y
*** Please describe this activity, including what you accomplished and any recognition you received, etc. [Feel free to share a link if applicable].
In the cycle I had the opportunity to be a mentor on, we had 40 students, whom went from almost zero level of English to a conversational level in 20 weeks. As a mentor I would say I had a really good opportunity to develop my soft skills, not only in order to communicate with other mentors and mentees, but to create the material, give the classes and practice with my mentee each week. In the period of mentoring, I developed 205 slide pages to auxiliate the teaching process. Link to my certificate: https://drive.google.com/file/d/10Gtvf4V5ivsMoBL7lZFVvRvf4Ieu3Zq1/view?usp=sharing Link to the project's Instagram page: https://www.instagram.com/projetoilearn/

*** Position/Leadership position
Physics teacher assistant
*** Organization Name OR name of the activity
Instituto Federal de Educação, Ciência e Tecnologia de Mato grosso do Sul - Campus Campo Grande
*** Period of participation
2021
*** Hours per Week and Weeks per Year
8h/w; 25w/y
*** Please describe this activity, including what you accomplished and any recognition you received, etc. [Feel free to share a link if applicable].
I volunteered a month in auxiliating a physics teacher with 3 physics classes (about 40 students each), and received a scholarship for the following semester to continue the work. The students participated throughout this period, having questions regarding activities, and list of exercises cleared up. Besides the test reviews I helped them with.

*** Position/Leadership position
Self-teaching
*** Organization Name OR name of the activity
Self-taught UNIX and FOSS-related content
*** Period of participation
2020-2022
*** Hours per Week and Weeks per Year
8h/w; 52w/y
*** Please describe this activity, including what you accomplished and any recognition you received, etc. [Feel free to share a link if applicable].
I study FOSS-related content, including but not limited to, Linux workbench, Linux system administration, basic Git, window managers configuration, free and open source licensing, and Tor networking. I also developed skills regarding AWK, bash/shell, C, Python, LaTeX, Markdown, Org-mode, and Qiskit. All my public activities are available in my github profile: https://github.com/luispengler

** Academic accomplishments
+ LIST your academic accomplishments (honors, medals, olympiads) and include a title for each one. Make sure you include if it is school wide, state wide, national, or international. Write them in cronological order, from most recent to least recent.

*** Honor title
Honorable Mention - 5th International Physics and Culture Olympiad (IPhCO)
*** Year of accomplishment
2021
*** Level of Recognition
International

*** Honor title
Honorable Mention - 24th Brazilian Olympiad of Astronautics and Astronomy (OBA) (Grade: 7/10)
*** Year of accomplishment
2021
*** Level of Recognition
National

*** Honor title
Honorable Mention - Physics Brazilian Olympiad for the Public Schools (OBFEP) 2021 (last phase)
*** Year of accomplishment
2021
*** Level of Recognition
National

*** Honor title
Best project at High School level - Science and Technology Fair of Campo Grande MS (Fecintec) 2021
*** Year of accomplishment
2021
*** Level of Recognition
State wide
*** Description
My group and I wrote a paper on how we managed to continue developing English conversations focused on our school community throughout 2021.

*** Honor title
Silver medal - Physics Brazilian Olympiad (OBF) 2019
*** Year of accomplishment
2020
*** Level of Recognition
State wide
*** Description
I worked through High School physics problems but in 9th grade. I was one of five students to attend the final examinations in my state.

** Essays
+ Prompt: Which major would you like to pursue and why? Even if you are undecided, tell us why. Please provide details. (250 - 500 words)
  My interest in Physics actually started with Chemistry. As a 6-year-old boy, I would ask my dad to print me a new periodic table every time I ran out of ways to set it up. But truth be told: at that time all I ever wanted to do was learn anything I found interesting. In Physics, one can never run out of curiosity and my inner-childhood never allowed me to do that. Throughout the years, I have been amazed by what humanity was able to do by just mastering Physics. How does an airplane that weighs 440 tons fly anyway?
  When I was 14, I was surprised how Linux-based operating systems made all the crappy computers I ever owned seem like they could have a new life. Simply learning how I could use this OS with more efficiency helped me see the bigger picture. Just like operating systems, computers are a tool. And the better a tool becomes, the more efficiently we are able to solve our unique set of problems. Be it improving chaotic system simulations for the weather forecasts or providing assistance in solving the united nations' Zero Hunger Goal.
  Quantum Computers will be the way to go in the future, at least for simulations (which we can use to solve the world’s biggest problems). A cool thing about this growing field is that it is really multidisciplinary. Having a degree in Physics and Computer Science would help me approach Quantum Computers in two distinct ways. Besides, I have individual interests in both fields that I could pursue in the future.


+ Why does this image appeals to you?
/You can see nobody was ready for this screenshot, but this same group of people used to meet throughout the whole year of 2021. This project is called Let's Bora and it is a conversational meeting group, so that we can practice English. That day, we were just having fun while playing UNO on telegram, and playing Gartic Phone. This image appeals to me because it reminds me how much we can accomplish when we are together. All of us improved our English, and I am sure we could not have done if we had nobody to listen to or no one to laugh with.

+ Please use this space to provide details of circumstances or qualifications not contemplated in this section (300 words or less).
In Junior High, I received 11 certificates indicating great academic performance, 7 of them being either class valedictorian or stating a GPA greater than 9.5. But at the end of middle school, about 8th-9th grade, my house was not in a good mood. My parents always fought a lot, but prior to their divorce, there were constant fights each week that a few times made my mom leave the house or we (me, my mother, and my two younger siblings) go to a distant police station dedicated to cases concerning violence against women. They got divorced in February of 2019. On September 15h of 2020, I was hospitalized for a disease I still carry, but wasn't identified until this event. Idiopathic thrombocytopenic purpura is the disease, and a rare one. But after removing my spleen it isn't much of a trouble. I started developing a passion for FOSS (free and open-source software) and as part of that journey, I've been writing my own website/blog https://luispengler.github.io/site/html/README.html. I presented a scientific initiation in High School (https://www.youtube.com/watch?v=HXh0zFwdwKo).

** Second session (RECORD A VIDEO)
+ Record a video with no more than 2 minutes answering *one* of the following prompts:
  a) *Tell us a story/curiosity/fun fact about you, your family, your neighborhood or the city you live in.*
I've always been really interested in my family's history, and today I am gonna share some things I find interesting about it.
1. My dad told me his mother's father (AKA my great-grandfather) was campo grande's mayor, which is the city I currently live in. I got interested about this and started searching more. I found out later that his name is in a wikipedia page intitled "Lista de prefeitos de Campo Grande". He was the 30th mayor of Campo Grande, but for only 2 months and 2 days. Most recently, I found out, through a newspaper he was also mayor of "Vila Bela da Santíssima Trindade".
2. My dad's family is also of german descendance, and even with little information about it, I was able to set up centuries of ancestry. It took me many months, but thanks to the internet I was able to finish something my older siblings couldn't. Most of them came from what we call today Rheinland-Pfalz, helping to spread the most common brazilian german dialect spoken nowadays, Hunsrückisch, which you can learn more about on youtube.
3. The last curiosity that I wanna share is that having the last name "Spengler" sometimes makes me receive messages like this. Thank you very much Egon!

  b) *You created a product or service. What is it? Why should people have it?*
  c) *Other than the ones mentioned so far on your application, tell us about something you really enjoy doing. Why is that?*
    1) WHAT ARE WE LOOKING FOR?

    We want to evaluate your overall communication skills and the message you get across to us.
    Please note:

        The video should be recorded in English by the candidate.
        Try to record somewhere quiet so we can hear what you have to say.
        We will NOT be evaluating the quality of your camera or the background.
        Feel free to be creative, AS LONG AS you answer the prompt.
        DON’T READ A SCRIPT! BE SPONTANEOUS!

    2) HOW DO YOU SUBMIT THE VIDEO?

    Post your video on YouTube, then fill *[[https://docs.google.com/forms/d/e/1FAIpQLSevWjpbip5cX2Fp2l9YTO5OigEs9CYXM_R9LM2NDXwIQCv6bw/viewform][THIS FORM]]* as requested!

    3) WHAT'S THE DEADLINE FOR SENDING THE VIDEO?

    FEBRUARY 2nd (WEDNESDAY), no later than 23:59


* YYGS

** TODO Activities list
+ Activity/Organization Name
  English Club
+ Position
Staff Member and Leader
+ Description (130 char)
Promote English interactions and reaserch throughout campus community

+ Why is this activity most meaningful to you? (100 words)
  I feel link we are of great help to students seeking to practice English, especially with someone you can see every day in your classroom, creating a truly dynamic interaction between students. I couldn't know the feeling better, for I have been an English club member myself!
  I also work with a very powerful, and incredible set of people. It feels like together we can do anything. As I write this, we have taken the English club to our state science fair, winning in first place, and two national science fairs. We even received a R$ 4,200.00 scholarship.

+ Activity/Organization Name
  Qubit by Qubit by The coding School
+ Position
  Student
+ Description
An online course with the mission of empowering students with the skills and confidence necessary to become future leaders, problem solvers and innovators through quantum education. Taught by MIT Scientists (other universities too!) and Sponsored by IBM, this is the only online course about quantum computing open worldwide for high school students. QubitxQubit excits me every week with lectures and lab sessions and I take advantage of these moments to learn as much as I can about the field I want to specialize in. I even started sharing my notes with the worldwide web: https://luispengler.github.io/site/html/org-pages/quantum-computing.html also here's a link to my first semester grades: https://drive.google.com/file/d/1X8zmCD8W1R8TCljNCOMkUOpgvaeku9UF/view?usp=sharin

+ Activity/Organization Name
Liga Olimpica de Astronomia
+ Position
Video editor senior
+ Description
Olympiad League of Astronomy is a project focused on astronomy dissemination. We have 1,354 followers on Instagram and our recent youtube channel has 175 subscribers. However the project started as a webpage. We offer preparation for Astronomy Olympiads, be it national or international (OBA, MOBFOG, OLAA, IOAA), as well as having anything (exams, worklists, books, handouts, articles, guides) you will need to study for them. Link to the project's website: https://ligadeastronomia.com/ Link to the youtube channel: https://www.youtube.com/channel/UCzd-QgsR05lxMWl1Wa0KKuQ

** Family information
+ For "No Parent/Guardian 2", please give a brief explanation. Many students list only one Parent/Guardian and then explain why this is the case.
  My parents got divorced about 3 years ago. My mother took custody, meaning she is the only legal guardian. My father needs to pay alimony tho.

** Essay
+ Please write about a time when your courage failed you. What happened? If you could go back in time and change it, what would you do differently (if anything)? (200-400 words)
It was September 15, 2020. I was in a queue to get vaccinated when my nose started bleeding. At that point in my life, my nose would start bleeding almost every day. However, this one occasion was special, as it was the first time I really needed to go to the hospital for it to stop bleeding.
As a result of needing a hospital to refrain my nose from bleeding, I ended up staying there for about three weeks, being submitted to different exams. With the examination, the doctor was determining the best course of action to take from there. As a consequence, it was decided I was to remove my spleen.
They tried explaining to me I would still have a normal life, and etc. I said I understood it, but I kept denying the fact that I was scared. Really scared this time. What if something was to go wrong? Besides, living the rest of my life requiring vaccination every 5 years wasn't something I was willing to go for either.
After those three weeks, I was home, resting and getting ready to take the surgery. Still scared, but I managed to hide it from my mother and the people closest to me. Though, one night before going to the hospital again, I started crying like that was the last day of my life. I decided to tell my good friend Raquel what I was feeling, and after a moment I managed to put it together.
I woke up the next day after the surgery, a bright day: October 23, 2020. At first, it was hard to do anything, but I recovered just fine. Sometimes I keep wondering why I felt so frightened that day. Perhaps if my life ever gets threatened once again, I can remember how well everything went that day.

+ If you could change one historical event that occurred in your country in the 20th century, what would you change and why? Please note that this does need to be a real, historical event that occurred between the years 1900-1999. (280 Characters)
The Nationalization campaign directly resulted in the oppression of immigrants in Brazil. It affected generations of immigrants' descendants, being difficult for them to recover documents regarding family trees, heritage, natively spoken language, and dialects.

+ What fictional character (from a book, tv show, film, short story, or any other literary work) do you relate to the most and why? (280 Characters)
Cyborg, from DC's teen titans. He goes in-depth when answering people's questions, he enjoys self-made (personalized) stuff, he binge-watches series he likes a lot, he is keen on technology. He has also displayed emotions of anger and frustration. Besides, he also eats a lot!

+ We want to learn more about your background, beliefs, values, and/or the important people in your life. Please tell us about something that has influenced you and articulate how it has shaped you. (200 words)
New friends, youtube videos, and software were some things that helped me learn the English language. I would spend the afternoon talking in English with my Turkish friend, Berkay. At the earliest days of our calls on the phone, I was- how would you describe? “Just smile and wave, boys”. Now, I have a friend for life.
The people from the English club were also on my list of new friends. There is a passion for the English language: A group of students ready to take their English experiences to other people. I soon became one of the staff members, and it helped me not only with English but also to develop my leadership skills.
Even during the pandemic, my friend Raquel and I had work to do. We hosted four live streams in English and every time, we would just go crazy, having calls that lasted hours, just to prepare for being host again.
I can say that learning English has enabled me to broaden my perspectives in many different ways, but above all, it has been responsible for the development of a better sense of myself and of what I want for life.
=note= finish financial aid questions

** Session Selection
+ Please explain why you chose the session(s) above, including your reasoning for how you ranked each session. (100 Words)
   I chose IST as the first option because I carry a huge passion for physics, molecular biology, chemistry, astronomy, engineering. I have also worked at electrical engineering labs, and researched, mainly in the English language area. Multidisciplinarity is a great deal for me, as I am modeling my way towards working in the quantum computing field. I also considered SGC because parts of working in this field require you to think about how such an innovative and expensive machine can be used to solve the world's biggest problems.

+ SHORT ANSWER: We know students have many options for academic enrichment programs to which to apply. Please explain why you chose to apply for YYGS specifically AND why you would be a great fit for the program. What will you contribute to YYGS, and what do you hope to take away from YYGS and bring back to impact your community? (100 words)
Partially because what I intend to do in the future takes contributions from many areas, I highly value multidisciplinarity and I feel at home when I am in a place I can learn from math to global politics.
I fit in the program because I am an open-minded person, collaborative, and I can contribute to the global diversity as a Brazilian student.
I hope to take as some of my outcomes, more impactful ideas to contribute to my projects regarding my school/country community where I play a big role, and greater respect for the different cultures portraited in YYGS.

https://summer.uchicago.edu/programs/latin-american-phoenix-scholars

https://docs.google.com/document/d/1YT7tm4rITJfybqANmjMVJLwLhoZUB5jH21w21B4jn9w/edit

https://docs.google.com/document/u/1/d/1LPvdtoQUSV_6_c26H-RkYTu-3nlnv_eSmvHMqR5Y2Tg/edit?usp=sharing

https://docs.google.com/spreadsheets/d/1rTgSijU-tr3zqN5AAJB6nI9A70Z4ktwk/edit#gid=1114293165

https://docs.google.com/spreadsheets/d/1PmfXW78jpqGekbDNJR3LR1TM4BQA0JC9/edit#gid=1875892457

SE EU PASSAR EU PROMETO QUE DOU 10 REAIS PRO EDUARDO.
SE EU FOR PROS EUA EU PROMETO QUE DOU A GUITARRA PRO JOÃO DA ROSELI

* TKS
** App questions
+ What's a company working on a disruptive innovation that most people don't know about? Tell us more about the company and their innovation. ("In business theory, disruptive innovation is innovation that creates a new market and value network or enters at the bottom of an existing market and eventually displaces established market-leading firms, products, and alliances.")
Many brands that design and manufacture laptops or other electronic devices aren't as focused on the consumer as you may think, and some might even use planned obsolescence as a business plan. However, framework is different.
This company is working on proving that you don't need to make ugly, heavy and thick laptops to call them repairable, neither revoke your rights on the product you manufacture to make it self-repairable.
By open-sourcing their firmware, software, and several hardware components, they give the user his freedom back, and stimulate privacy-conserving practices. As a bigger result, they create a community of non and tech experts who love framework's products.

+ Teach us about a topic you're interested in.
Sometimes when you are part of a group that does something interesting, you think everybody else knows what you are doing. But that's not the reality. Imagine you are part of a research group focused on decreasing noise in quantum computers. "What does noise have to do with computers?" (One might ask) And then you decide it is time people know what the heck a quantum computer is.
First, you need to understand that quantum computers are not devices that will help you send an email to your teacher, or being able to play 8K videos in 10 different monitors at the same time (stuff that gamers love). No, quantum computers are not supposed to be a replacement for your normal computer. For the sake of understanding, let's say normal computers are classical computers.
And the kind of problems quantum computers may be able to solve in the future is incredible: Search for life in other planets, global hunger, climate change, cyber security issues, vaccine development, drug discovery, and many other problems. But those problems will only be able to be solved with a quantum computer in the long-term quantum computing. For now, we need to get satisfaction by being able to simulate quantum monte-carlo, take advantage of quantum key distribuition, and play quantum chess (I know, the first two reasons don't seem fun, but I promise quantum chess is cool!).
Quantum computers have a huge advantage on classical computers when we are solving problems that involve too much searching or testing for classical computers to do quickly, problems that require secure encryption, or problems that require simulating quantum mechanical systems. Remember, they are not a replacement for classical computers. Quantum computers have the name quantum because they use the properties of quantum mechanics to solve problems, and classical computers use the properties of classical physics to solve problems.
If quantum computers use the properties of quantum mechanics, then what are these properties? There are 3 properties that are really importance to us: superposition, interference, and entanglement. All of these will sound weird to you, but with a simple ice cream analogy, I can facilitate your understanding.
Superposition is like when you go to an ice cream store. There are only two ice cream flavors in this particular store: chocolate, and strawberry. Until you say it out loud "I want a chocolate ice cream", the person taking orders will not know which one you do want. If you already had this non-asked-ice-cream, it would be in a superposition of chocolate AND strawberry, meaning that for a moment, you actually had an ice cream that tasted two different flavors at the same time! But because this is not possible, when you finally decide which flavor you want, your magical ice cream becomes a simple chocolate one OR a strawberry one.
Interference is like when you are choosing an ice cream flavor plus an ice cream topping. Lets suppose you only have 4 toppings: caramel sauce, blueberry sauce, lemon sauce, and vanilla sauce. The first two (caramel sauce, and blueberry sauce) are only allowed to go with the chocolate ice cream, and the last two (lemon sauce, and vanilla sauce) can only be on top of a strawberry ice cream. In reality, you only need to tell your ice cream topping to know your ice cream flavor. If you order an ice cream with lemon sauce topping, a strawberry ice cream will come up + this lemon sauce topping.
Entanglement can also be explained in an easy way. Imagine you go to this same ice cream store, even though it only has two ice cream flavors and four toppings, it is the place your best friend and you love going to the most. You go there so often, the attendant already know what you usually order. If you just tell them you will want the usual, they will know what you and your friend is going to eat. There is a correlation between the command "I will have the usual" and the final result (the ice cream you and your friend get at the end).
The last three paragraphs are only simple analogies about complex ideas. You will not be a university professor just by understanding them, but I hope I made myself clear in explaining the essentials of a quantum computer, what we will get if we continue developing them, and the basics behind those computers that obey strange laws.

+ Who is someone that inspires you?
Richard Stallman is someone who inspires me to continue the fight for freedom of software, as well as freedom in a more general sense. Some even say he is the freedom defender whom we may not deserve but definetely need. By definition, free software means the users have the freedom to run, copy, distribute, study, change and improve the software.
While Stallman has some ideas I don't agree with, his role as software freedom fighter remained since the beginning of his carrer and it is crucial to the internet as we know it today. Without him the internet would be a place 100% jeopardized by companies with interest in selling information about you. Even the modern way we learn programming, and science areas would be fundamentally different without someone like Richard.

+ Why do you want to be in TKS?
I want to have a deeper impact in my community through the ways I can help with, and I believe I can have a better impact if I do something I both love and am good at. I love doing research, teaching, and having fun while being a nerd. But I also require guidance, teaching, and I would like to know more about business and ideas that are in accord to my moral ones.
As a high school student already in the field of quantum computing, I can say it is a field that only one area doesn't prevail. In fact, most things that matter aren't. I want to have this chance of getting to know more about other areas outside a classroom.
TKS will be a place for me to develop impactful ideas, enhance my multidisciplinarity, and broaden my network and world prespective.

+ Optional: Is there anything else we should know? (Share projects you've worked on, past achievements you're proud of, or anything you think that will help us evaluate if you'd be a good candidate for TKS. If you share a link, please make sure it's not a private link.)
Story 1: I work at English Club as a staff member, leader, and researcher. Our intention last year was just to develop an online conversation group dedicated to practicing English during the pandemic. We ended up doing more than that, as “Let's Bora”—the name of our online conversation group—was so successful, we wrote a research paper about it. Then, we were awarded as the best project at the High School level at our city-state fair, leading us to two national science fairs, subsequently earning R$ 4,200.00 to use in our project's needs.
I think what made it successful was the individual commitment each one of us had. Additionally, we could also count on an advisor whose previous experiences with English clubs were also successful, and was able to provide us guidance. The biggest challenge we faced, at the beginning, was being short-staffed. It was required more people to be able to account for the demand of tasks and ideas we'd like to pursue. We solved this problem by opening an application process. You can have a look at our instagram: https://www.instagram.com/englishclubcg/
Story 2: My interest in Physics actually started with Chemistry. As a 6-year-old boy, I would ask my dad to print me a new periodic table every time I ran out of ways to set it up. But truth be told: at that time all I ever wanted to do was learn anything I found interesting. In Physics, one can never run out of curiosity and my inner-childhood never allowed me to do that. Throughout the years, I have been amazed by what humanity was able to do by just mastering Physics. "How does an airplane that weighs 440 tons fly anyway?" I wish I could say I have a lot of achievements I am proud of in Physics, except for in 9th grade (2019) when I was awarded a silver medal for my performance at the Brazilian Physics Olympiad (OBF), and being accepted into QubitxQubit's course "An introduction to Quantum Computing" with a 700 dollars scholarship (by IBM) to study quantum computing for 24 weeks (it's like I am living a dream).
Story 3: I am very fond of the free software community. But I only got to understand why it is important to fight for freedom of software when I started using GNU/Linux. In fact, I only got to understand many things when I started using GNU/Linux. The year was 2017, I knew almost nothing about computers. My mother bought a computer running Linux Mint operating system. Time has gone by, and despite the attempt of several people (some of them friends) trying to make me give up on Linux, I still had this curiosity to know why the system behaved differently than windows, what I could do with it, and why I felt so powerful using it. In 9th grade (2019), I studied and successfully learned English, using open source tools like anki, and several user manuals. Even more time has gone by, and I learned bash/shell, C, LaTeX, Org-mode, and Markdown. I learned the basics of many areas inside computer science, and then I realized my interest for computers had sparked. I learned how to run my own website
https://luispengler.github.io/site/html/README.html, I learned cool software should be open, leading me to start sharing telegram skins that I created https://luispengler.github.io/telegram-desktop-themes/html/README.html, and also start sharing a document with actions commited (not so cool actions) by the biggest technology companies https://luispengler.github.io/site/html/org-pages/spooky-tech.html

** JE
+ What are your favorite subjects in school and why? (300 chars.)
  My favorite subject in school is physics. I've always liked and studied physics since I was little. Physics allows me to apply my curiosity in a thousand different ways and come to one hundred different solutions. I like it because it is universally useful, and challenging.
+ What do you plan to study at the university? (300 chars.)
 I would like to double major in physics and computer science, since those are areas I enjoy studying. Double majoring in physics and computer science will give me a background compatible with many needed careers and research positions, mainly in the quantum computing field.
+ What is your biggest dream and what do you plan to do to achieve it? (300 chars.)
My biggest dream is to make useful contributions to science, and education. For that, I will need to improve my knowledge and always think in both short and long term.
+ How do you think becoming a Youth Ambassador can help you and your objectives in life? (300 chars.)
In JE I will improve my multidisciplinarity a lot by having learned about entrepreneurship, leadership, and potentially different cultures. By the end of the program, I will have more impactful ideas to contribute to my community projects.

* General questions
+ Descreva sua experiência com o inglês em terceira pessoa
Luís possui uma certificação B2-C1 (CEFR) pela American and British Academy, pesquisador nas áreas de língua inglesa, conversação e internacionalização institucional. Possui experiência como mentor de Inglês. Agora este estuda para o SAT e DET, em processo de candidatura para universidades americanas.
+ What are things you are doing now that relate to your major?
Qubit by Qubit by The coding School, Video editor senior, Physics teacher assistant (I've gotten a medal on OBF), Self-taught UNIX and FOSS-related content (I study FOSS-related content, including but not limited to, Linux workbench, Linux system administration, basic Git, window managers configuration, free and open source licensing, and Tor networking. I also developed skills regarding AWK, bash/shell, C, Python, LaTeX, Markdown, Org-mode, and Qiskit. All my public activities are available in my github profile).
+ RELATO BREVE DA SITUAÇÃO FAMILIAR: descreva a situação social, econômica, de moradia, transporte, condição de saúde dos membros do núcleo familiar e qual o motivo por estar solicitando o auxílio, assim como demais informações que acredita serem relevantes para uma análise do serviço social
Os meus pais estão separados e não tenho muito contato com ele, porque a minha mãe tem medida protetiva e as nossas visitas são assistidas. Moro com a minha mãe e os meus dois irmãos menores de idade. Atualmente a minha mãe esta desempregada e contamos apenas com a pensão alimentícia no valor de meio salário mínimo e r$ 400,00 do Auxílio Brasil. Utilizo transporte público para ir para a escola, ao médico, laboratório. Faço tratamento de uma doença autoimune chamada PTI, pelo SUS, mas às vezes a minha mãe paga alguns exames.
+ Explain the objectives of this social entrepreneurship initiative:* (500 chars.) [ENGLISH CLUB]
Our goal is to promote opportunities of development of the English language teaching-learning, integrating it to other areas of knowledge, and counting with teachers, students, and servants. To do so, we offer activities in the English language that contain the language, contributing to intellectual production, scientific, artistic and cultural of students and servants.

* Codelab
*USE YOUR SCHOOL EMAILLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
+ Por que você deseja se tornar um mentor no Code Lab? (Até 100 palavras)
Quero contribuir para a democratização do ensino de programação para jovens de todo Brasil, pois acredito ter grande

+ Informe seu nível de conhecimento na(s) linguagem(ns) que deseja ensinar, fornecendo o máximo de detalhes possível. *

+ Por favor, utilize esse espaço para dar mais detalhes a respeito da sua disponibilidade.
Se possível, gostaria de trabalhar diretamente com o aluno(a) por no máximo 2 horas por semana. Preferencialmente uma hora na quinta-feira a tarde/noite, estaria disponível entre as 17h-21h e outra hora no sábado/domingo esses mesmos horários.
No entanto, gostaria de usar cerca de duas horas por semana na elaboração de materiais introdutórios a programação em C, ou em algo que venho chamando "Programação em ambiente Linux: Bash/Shell + LaTeX e Markdown", que consistiria na melhor introdução possível a programação no ambiente Linux, abordando de jeito único os benefícios de se utilizar esse sistema operacional.
A ideia de se fazer duas calls por semana de 1h (esses horários na quinta/sábado/domingo) é para se desenvolver um método de ensino de programação que considere aulas de até 1h. Por isso também, considero trabalhar com apenas 1 aluno do nível iniciante.


* QIntern
+ 5, 8, 9, 13
** Requirements
+ 2 days per week
+ QC: Basic Quantum Gates and Algorithm, Basic Concept of Quantum/Classical Comunication, Familiarity with random number generators
+ Math: Linear Algebra, Matrix Operations
+ Coding: Programming in Python
+ Language: Advanced English, Ability to read and understand scientific papers and scientific terminology in the QC domain, Interest in popular culture

** 5 - Continuous variable quantum random number generators
+ 1 day per week
+ Familiarity with random number generators, linear algebra, matrix operations

** 8 - N-Queens Solver Implementation for Optimization of Communication System by Qiskit
+ 2 days per week
+ Basic Concept of Quantum Computing (quantum gates and algorithm), Basic Coding Skills on Python, Basic Concept of Quantum/Classical Communication

** 9 - References to Quantum Technologies in Cultural Artefacts
+ 1 day per week
+ They should have at least above average command of the English language. Some familiarity and interest in popular culture, and cultural works. Commitment to the scientific rigor of and interest toward qualitative research methods employed in social sciences.
+ The project requires some commitment by the interns, so please do not apply if you don’t have the time to read, write, attend meetings, and prepare presentations.

** 13 - Optimizing logistics using quantum computing
+ 1 day per week
+ Knowledge of basics of quantum computing, programming in Python, ability to read and understand scientific papers and scientific terminology in the QC domain (like in  https://drive.google.com/file/d/1xivRK-HWS28ANuh2A8BbUzmCVp4eXUyj/view), motivation to learn new things from the QC domain. Possibility to join weekly (online) meetings on Sundays at 13:00 CEST (This is 7 am)

** Question
+ What are your skills and experience related to quantum science, technology, etc?

I have basic knowledge on quantum mechanics, being sufficient for understanding of major physical phenomena that make quantum computing, information and communication possible. I can code in Python (also using Qiskit SDK), bash/shell, C, and some markdown languages like LaTeX, Markdown, and Org Mode. In Qiskit I can create quantum gates and run basic quantum algorithms (like Shor's, and Groover's). I also know how to use Git, GitHub, and GitLab (as well as any unix-like operating system). I know how to do matrix operations, and find the determinants of a matrix (giving me basic knowledge on linear algebra). Furthermore, I understand how most electronic components work and how to operate them, and have a good domain over topics on electricity and electronics. In addition, I can understand scientific papers and scientific terminology in the quantum computing domain, as well as in other topics in the quantum mechanics, and particle physics fields.

* Code Connects
** Emerging Technologies - July 11 - July 22 (Monday - Friday 1pm to 4am)
+ Week 1: - Python (learn about variables, conditionals, booleans, loops, functions, etc)
+ Week 2: - Learn about problems every day and some fields (AI, cybersecurity, healthcare +tech, web development + desgin), and at the end choose one to try to solve using the knowledge built on week 1
** Research - July 5 - August 5 (Monday - Friday 1pm to 5pm)
+ Week 1-2: - Training in data science, developing skills in R, data visualizations, data cleaning, data analysis
+ Week 3-5: - Research...

* Values exercise
** Top 10
+ intellect
+ laughter
+ freedom
+ security
+ knowledge
+ privacy
+ efficiency
+ helping others
+ curiosity
+ growth
** Top 5
+ freedom
+ helping others
+ curiosity
+ growth
+ laughter
** Top 3
+ freedom
+ helping others
+ curiosity
** Top 1
+ freedom

* Marcohort
+ Because I had these moments I see how it is important to share and today I think that these moments (sharing) are something important in your lfie.
+ Write NU and Tufts
