#+TITLE: Week 4 - my own writings
#+DESCRIPTION: Week 4 - my own writings
#+SETUPFILE: https://luispengler.github.io/site/org-html-themes/org/theme-readtheorg.setup
#+OPTIONS: nul:nil ^:{}

* Week 4 (Qubit by Qubit)
test \(E=mc^2\)
** RECAP:
*** Quantum mechanics:
+ Qubits have discrete states and we can use these 0s and 1s in computation.
+ In adition to being 0 or 1, qubits can also be in a superposition and therefore, can hold exponentionally more information than classical
+ Superposition powers: Process all possibilities of solving a problem at the same time.
+ Interference powers: Rules out incorrect possible solutions, making them interfere with each other destructively and correct ones interfere constructively.
- Quantum computers excel at finding one solution among massive amounts of possibilities.

** Quantum Gates and Measurement
*** Representing Qubits
+ Superconducting qubits (Google, IBM), trapped ion qubits (IONq), Photonics (PsiQuantum) are some types of qubits, but they all obey quantum mechanics laws as well as *having the same way to represent them.*
+ Represntation is a way to write down and show what's happening, without worring to much about the physics.
Ket notation and the Block sphere are two common ways to describe qubits instead of using arrows.

*** Ket Notation
+ 1 and 0 are not just numbers, they are *quantum states.* and to represent that, we use kets.
+ Anything inside | > it means it's a quantum state. Ex: |1>, |2> and Superposition of |0> and |1>
+ AKA bra-ket notation or Dirac notation.
**** Schrodinger's ket
+ |alive> + |dead>
+ In future weeks, we will be learning some math with kets.

*** the Block sphere
+ Qubits can be in more than three states (different than using arrow notation, that uses *Equal Superpostion*).
Show images of it...
+ Unequal superpositions are the ones that are not either 0, 1 or 50% superposition. It's like 30% of 0 and 70% of 1. They are like an unfair coin.

*** Quantum Gates
+ Quantum gates convert a qubit from one state to another.
+ The computations that quantum gates make can be visualized as rotations on the Bloch sphere.
+ There are a lot of gates. But we'll be focusing on 3 (X gate, H gate, Z gate) of them first, 2 of them today (H and X gate).
+ For gates, we will need a 3-D coordinate system. Like x,y,z. and we can place the Bloch sphere on this coordinate system.
+ |0> lies along z, as well as |1>. Equal superposition |0>+|1> lies along x axis.

**** The X gate
+ it gives the opposite of the input (hint: just like NOT gate in classical computing)
+ Input: |0> Output: |1>
+ Input: |1> Output: |0>
+ Its name is "X gate" because it does a rotation of 180ยบ around the X axis.

**** The H gate
+ AKA Hadamard gate
+ It is a purely quantum gate (has no classical equivalent) and only exists on quantum computers.
+ It creates a superposition.
+ Input: |0> Output: |+>
+ Input: |1> Output: |->
+ |+> and |-> are examples of superpositions.
+ It rotates 90ยบ on any axis, creating a superposition.
+ We will learn more math to understand the difference between the |+> and |-> states.
** Guest speaker:
Dr. Casey Berger, visiting assistant. Computational physics.
science fiction she's written: URSA MAJOR, FIRST LIGHT, DARK STARTS https://www.caseybergerbooks.com/
She studies superfluids.
