#+TITLE: Week 3 - my own writings on QubitxQubit lectures.
#+DESCRIPTION: Week 3 - my own writings on QubitxQubit lectures.
#+SETUPFILE: https://luispengler.github.io/site/org-html-themes/org/theme-readtheorg.setup
#+OPTIONS: nul:nil ^:{}

* Week 3 (Qubit by Qubit)

** RECAP:
*** Quantum properties:
*Discretness*: Energy can only take certain values.

*Superposition*: Qubits being in a combination of two(?) states at the same time.

*Interference*: The state of objects adding up or cancelling out.

*Entanglement*: One object's state depends on another object's state.

*Measurement*: The outcome is often random and obeserving (measuring) you can change it.

** Quantum mechanics: part 2
*** Wave-particle duality and the double-slit experiment.
+ Why do quantum objects show superposition, interference, and entanglemenet?
+ How should they be described (their behavior)?
+ Classical physics: things are either waves or particles. Which one of them should I use to describe what I see in my experiments?

  *Waves*:
  - Waves travel at a certain velocity.
  - Different kinds of waves have different speeds.
  - Sound waves are slower than light waves.
  - Waves interact with each other, they show *interference*. Interference can be constructive: two waves add together, or destructive: two waves cancel out.
    #+ATTR_HTML: alt: Double-slit :title Double-slit :style float:left;margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
    https://luispengler.github.io/site/doc/images/waterwave.jpg

  *Particles*:
  - Particles have mass.
  - Particles have a well-defined postion or location - they are *discrete*.
  - They move with a velocity.


*Double-slit experiment is used to decide if quantum objects behave like a wave or a particle*.
#+ATTR_HTML: alt: Double-slit :title Double-slit :style float:left;margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/double-slit.png

  - Particles would leave two lines on the wall behind the two slits (discrete spots and no interference)

  - Waves would leave a pattern of bright and dark lines, some waves are amplifying one another, while other waves are canceling out (interference).

*Throwing electrons*:
- Each electron is a *discrete* spot on the wall.
- After a certain amount of electrons, you get an *interference* pattern.
- A nice example of *particle-wave* duality on my opinion.
- This happens to *all quantum objects*
- In quantum, waves can behave as particles and particles can behave as waves.

*** Case study: how large can objects get and still be quantum?
+ [[https://www.phys.ens.fr/~nascimbene/enseignement/old/meca_q/td_2006_2007/td1/arndt_1999.pdf][Article]]: Wave-particle duality of C60 molecules - Markus Arndt, Olaf Naiz, Julian Vos-Andreae, Claudia Keller, Gerbrand van der Zouw & Anton Zeilinger.

  *State*:
  - A possible condition of the classical bit or qubit.

*Superposition and interference are very similar: both involve overlapping waves.*

*** Explaining discretization
In a guitar, a string can take only *specific shapes* when it vibrates.

Specific shapes are a result of *confinement*.

The idea of confinement also applys to quantum objects.

If you limit something's movement, it will also show the same kind of discretization (either a 0 or 1), just like a guitar's string.

What confines quantum objects?
- trapped ions quantum computers, AKA as some sort of artificial atoms.
- Superconductiing computers, confinements are virtually created.



*** The unanswered questions.
+ Entanglement: Why does it happen? Is there just a mysterious link between atoms or is it something most likely more tangible and physical that we can understand?
+ Why does measurument change the state of the qubit?
+ Why is quantum measurument random?
and many more...

*** Some interpretations
+ The Copenhangen Interpretation (Niels Bohr and colleagues). When a quantum state is measured, it collapses to one of the possible results of the measurument - the most accepted interpretation
+ The Many Worlds Interpretation (Hugh Everett). There is no collapse going on, but when you measure it, you are splitting into a new universe.
+ De Broglie-Bohm Interpretation, AKA Pilot wave theory. The wave and particle parts of the quantum object coexist, like a droplet bouncing on a puddle.

#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style float:left;margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/site/doc/images/broglie-bohm.png

** Lab 13:
Note to myself: keep an eye on LIGO Laser Interferometer Gravitational-wave obeservatory ;)

We used flytrap a bit on this week lab, a really cool thing. https://lab.quantumflytrap.com/lab

** Guest speaker:
Dr. Clarice Aiello, assistant professor of ECE, UCLA Quantum Biology Tech (QuBiT) Lab.
+ *Quantum sensing*: using quantum objects as sensors. It is proven mathematically that by using quantum objects as a sensor, your measurument is improved.
+ *Quantum biology*: There are quantum objects inside animals that we can use and apply to our own technology.
+ *Spin* is a merely quantum mechanical property that doesn't have a classical equivalent. It measures how well an object interact with a magnetic field.
+ There are some chemical reactions that are spin dependent. Ex: If a spin is measured by the environment to be in a state up, the chemical reaction continues to one branch. The same with the down state. And the final products of these states are different.
+ We got so much to learn with nature, as it controls quantum so well. Disease treatment is a way all this knowldege can be used.
+ Quantum bits can be controlled using magnetic field, same thing in quantum biology.
+ Birds, turtle, butterflies migrating feel and follow the magnetic field of earth (most accepted theory)
+ Quantum biology center out of UCLA. (wants to develop a quantum biology course - the first official one)
+ *Book*: Life on the edge; (introduction to quantum biology)
